{"metadata":{"platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0","unavailable":false}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPageViewEvent"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","kind":"typeIdentifier","text":"PageView"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"title":"sendPageViewEvent(_:)","role":"symbol","roleHeading":"Instance Method","extendedModule":"ZendeskSDK","externalID":"s:10ZendeskSDK0A0C17sendPageViewEventyyAA0dE0CYaKF","modules":[{"name":"ZendeskSDK"}]},"abstract":[{"text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPageViewEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pageView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","text":"PageView","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"PageView"},{"text":" object that contains information related to a user’s interactions e.g. the title of the page that was visited.","type":"text"}],"type":"paragraph"}],"name":"pageView"}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Throws : This will throw an error of type ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" in case of failure.","type":"text"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"url":"\/documentation\/zendesksdk\/zendesk","type":"topic","title":"Zendesk","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:)":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:)","abstract":[{"text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPageViewEvent"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","kind":"typeIdentifier","text":"PageView"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:)","title":"sendPageViewEvent(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView":{"url":"\/documentation\/zendesksdk\/pageview","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageView","kind":"identifier"}],"abstract":[{"text":"This object is used to provide session-based data to capture contextual information about an end user. This data is viewable inside","type":"text"},{"text":" ","type":"text"},{"text":"Agent Workspace.","type":"text"}],"type":"topic","title":"PageView","navigatorTitle":[{"text":"PageView","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"kind":"identifier","text":"Zendesk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/title","value":"ZDKPageView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/fragments","value":[{"text":"ZDKPageView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPageView"}]}]}]}