{"abstract":[{"text":"The new conversation button was clicked from the conversation list screen","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationList","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"role":"symbol","navigatorTitle":[{"text":"NewConversationSourceConversationList","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@NewConversationSource@NewConversationSourceConversationList","title":"NewConversationSource.conversationList"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationsource\/conversationlist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/newconversationsource\/conversationlist"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/conversationList","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationList"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","navigatorTitle":[{"kind":"identifier","text":"NewConversationSource"}],"url":"\/documentation\/zendesksdk\/newconversationsource","type":"topic","abstract":[{"type":"text","text":"Enum representing sources or locations where the new conversation button can be clicked."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationSource"}],"kind":"symbol","title":"NewConversationSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/conversationList":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/conversationList","navigatorTitle":[{"text":"NewConversationSourceConversationList","kind":"identifier"}],"abstract":[{"text":"The new conversation button was clicked from the conversation list screen","type":"text"}],"title":"NewConversationSource.conversationList","url":"\/documentation\/zendesksdk\/newconversationsource\/conversationlist","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"conversationList","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"NewConversationSourceConversationList","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"NewConversationSourceConversationList","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"NewConversationSourceConversationList"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NewConversationSource","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title"},{"value":[{"kind":"identifier","text":"NewConversationSource"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments"},{"value":[{"text":"NewConversationSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle"},{"value":"NewConversationSourceConversationList","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource~1conversationList\/title"},{"value":[{"text":"NewConversationSourceConversationList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource~1conversationList\/fragments"}]}]}