{"metadata":{"externalID":"s:10ZendeskSDK35NewConversationButtonClickedDetailsC03newD6SourceAcA0cdI0O_tcfc","title":"init(newConversationSource:)","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newConversationSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NewConversationSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ZendeskSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/init(newConversationSource:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/init(newconversationsource:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"newConversationSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NewConversationSource","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails/init(newConversationSource:)":{"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/init(newconversationsource:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/init(newConversationSource:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newConversationSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NewConversationSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource"},{"text":")","kind":"text"}],"title":"init(newConversationSource:)","abstract":[],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Details related to the event when the new conversation button is clicked."}],"title":"NewConversationButtonClickedDetails","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails","role":"symbol","type":"topic","navigatorTitle":[{"text":"NewConversationButtonClickedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationSource","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NewConversationSource","kind":"identifier"}],"title":"NewConversationSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","url":"\/documentation\/zendesksdk\/newconversationsource","abstract":[{"text":"Enum representing sources or locations where the new conversation button can be clicked.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKNewConversationButtonClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/navigatorTitle"},{"op":"replace","value":"NewConversationSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NewConversationSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NewConversationSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}