{"metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails(py)newConversationSource","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","text":"NewConversationSource"}],"title":"newConversationSource","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"newConversationSource"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"The source from which the new conversation button was clicked"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/newConversationSource","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","text":"NewConversationSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/newconversationsource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/newconversationsource"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails/newConversationSource":{"navigatorTitle":[{"text":"newConversationSource","kind":"identifier"}],"abstract":[{"type":"text","text":"The source from which the new conversation button was clicked"}],"url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/newconversationsource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/newConversationSource","title":"newConversationSource","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newConversationSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NewConversationSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Details related to the event when the new conversation button is clicked."}],"title":"NewConversationButtonClickedDetails","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails","role":"symbol","type":"topic","navigatorTitle":[{"text":"NewConversationButtonClickedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationSource","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NewConversationSource","kind":"identifier"}],"title":"NewConversationSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","url":"\/documentation\/zendesksdk\/newconversationsource","abstract":[{"text":"Enum representing sources or locations where the new conversation button can be clicked.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"newConversationSource","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"newConversationSource","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","text":"NewConversationSource","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"newConversationSource","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails~1newConversationSource\/title","value":"newConversationSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails~1newConversationSource\/fragments","value":[{"kind":"identifier","text":"newConversationSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/title","value":"ZDKNewConversationButtonClickedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title","value":"NewConversationSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments","value":[{"text":"NewConversationSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle","value":[{"text":"NewConversationSource","kind":"identifier"}],"op":"replace"}]}]}