{"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"articleTitle"}],"title":"articleTitle","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails(py)articleTitle","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleTitle","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/articleclickeddetails\/articletitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/articleclickeddetails\/articletitle"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails"]]},"abstract":[{"type":"text","text":"The article title (nullable)"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails/articleTitle":{"title":"articleTitle","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleTitle","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails\/articletitle","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"articleTitle","kind":"identifier"}],"abstract":[{"type":"text","text":"The article title (nullable)"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails":{"title":"ArticleClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleClickedDetails","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"articleTitle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"articleTitle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"articleTitle"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"articleTitle","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleTitle\/title"},{"op":"replace","value":[{"text":"articleTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleTitle\/fragments"},{"value":"ZDKArticleClickedDetails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/title"},{"value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/fragments"},{"value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}