{"metadata":{"role":"symbol","title":"NewConversationSource","navigatorTitle":[{"kind":"identifier","text":"NewConversationSource"}],"externalID":"c:@M@ZendeskSDK@E@NewConversationSource","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationSource"}],"symbolKind":"enum","roleHeading":"Enumeration"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/conversationList"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/description"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationsource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/newconversationsource"]}],"abstract":[{"text":"Enum representing sources or locations where the new conversation button can be clicked.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationSource"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","url":"\/documentation\/zendesksdk\/newconversationsource\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","navigatorTitle":[{"kind":"identifier","text":"NewConversationSource"}],"url":"\/documentation\/zendesksdk\/newconversationsource","type":"topic","abstract":[{"type":"text","text":"Enum representing sources or locations where the new conversation button can be clicked."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationSource"}],"kind":"symbol","title":"NewConversationSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/description":{"url":"\/documentation\/zendesksdk\/newconversationsource\/description","type":"topic","title":"description","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/description","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/newconversationsource\/init(rawvalue:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/RawRepresentable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/newconversationsource\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations"},"doc://com.zendesk.Zendesk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/conversationList":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/conversationList","navigatorTitle":[{"text":"NewConversationSourceConversationList","kind":"identifier"}],"abstract":[{"text":"The new conversation button was clicked from the conversation list screen","type":"text"}],"title":"NewConversationSource.conversationList","url":"\/documentation\/zendesksdk\/newconversationsource\/conversationlist","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"conversationList","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"NewConversationSource","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NewConversationSource"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"NewConversationSource","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/conversationList"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationSource"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"NewConversationSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NewConversationSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NewConversationSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle","op":"replace"},{"value":"NewConversationSourceConversationList","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource~1conversationList\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NewConversationSourceConversationList"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource~1conversationList\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}