{"abstract":[{"text":"Details of a proactive message that was clicked.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/init(proactiveMessageId:campaignId:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/campaignId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/proactiveMessageId"],"anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKProactiveMessageClickedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageClickedDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/proactivemessageclickeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/proactivemessageclickeddetails"]}],"kind":"symbol","metadata":{"symbolKind":"class","title":"ProactiveMessageClickedDetails","roleHeading":"Class","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageClickedDetails"}],"navigatorTitle":[{"text":"ProactiveMessageClickedDetails","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"kind":"relationships"}],"sections":[],"references":{"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails":{"navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageClickedDetails"}],"abstract":[{"type":"text","text":"Details of a proactive message that was clicked."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails","role":"symbol","type":"topic","title":"ProactiveMessageClickedDetails","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageClickedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails/campaignId":{"title":"campaignId","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/campaignId","abstract":[{"text":"The ID of the campaign for the proactive message","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"campaignId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"campaignId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails\/campaignid"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails/proactiveMessageId":{"abstract":[{"text":"The ID of the proactive message that was clicked","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"proactiveMessageId","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/proactiveMessageId","title":"proactiveMessageId","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails\/proactivemessageid","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails/init(proactiveMessageId:campaignId:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithProactiveMessageId:campaignId:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/init(proactiveMessageId:campaignId:)","role":"symbol","type":"topic","title":"init(proactiveMessageId:campaignId:)","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails\/init(proactivemessageid:campaignid:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"campaignId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKProactiveMessageClickedDetails","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/campaignId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/proactiveMessageId"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails\/init(proactiveMessageId:campaignId:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageClickedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKProactiveMessageClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/fragments"},{"op":"replace","value":[{"text":"ZDKProactiveMessageClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/navigatorTitle"},{"op":"replace","value":"campaignId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1campaignId\/title"},{"op":"replace","value":[{"text":"campaignId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1campaignId\/fragments"},{"op":"replace","value":"proactiveMessageId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1proactiveMessageId\/title"},{"op":"replace","value":[{"text":"proactiveMessageId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1proactiveMessageId\/fragments"},{"op":"replace","value":"initWithProactiveMessageId:campaignId:","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1init(proactiveMessageId:campaignId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithProactiveMessageId:campaignId:"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails~1init(proactiveMessageId:campaignId:)\/fragments"}]}]}