{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"],"type":"conformsTo"}],"abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKURLSource) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/urlsource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/urlsource"]}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/carousel","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/file","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/image","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/linkMessageAction","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/text","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/webViewMessageAction"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/RawRepresentable-Implementations"]}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"URLSource"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}],"title":"URLSource","symbolKind":"enum","externalID":"c:@M@ZendeskSDK@E@ZDKURLSource","modules":[{"name":"ZendeskSDK"}],"role":"symbol"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/image":{"url":"\/documentation\/zendesksdk\/urlsource\/image","title":"URLSource.image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceImage"}],"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"code":"image","type":"codeVoice"},{"type":"text","text":" message on the conversation screen."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/image","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/carousel":{"url":"\/documentation\/zendesksdk\/urlsource\/carousel","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/carousel","navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceCarousel"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carousel"}],"title":"URLSource.carousel","abstract":[{"type":"text","text":"User selected "},{"code":"URL","type":"codeVoice"},{"type":"text","text":" from a "},{"code":"carousel","type":"codeVoice"},{"type":"text","text":" message on the conversation screen."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/file":{"abstract":[{"text":"User selected ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" from a ","type":"text"},{"code":"file","type":"codeVoice"},{"text":" message on the conversation screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceFile"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/file","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"url":"\/documentation\/zendesksdk\/urlsource\/file","title":"URLSource.file"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/linkMessageAction":{"navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceLinkMessageAction"}],"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"link"},{"type":"text","text":" message button from a message on the conversation screen."}],"title":"URLSource.linkMessageAction","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkMessageAction"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/linkMessageAction","url":"\/documentation\/zendesksdk\/urlsource\/linkmessageaction","role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/webViewMessageAction":{"title":"URLSource.webViewMessageAction","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/webViewMessageAction","type":"topic","navigatorTitle":[{"text":"ZDKURLSourceWebViewMessageAction","kind":"identifier"}],"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"webView"},{"type":"text","text":" message button from a message on the conversation screen."}],"role":"symbol","url":"\/documentation\/zendesksdk\/urlsource\/webviewmessageaction","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewMessageAction","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/text":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"}],"role":"symbol","abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from "},{"type":"codeVoice","code":"text"},{"type":"text","text":" on the Conversation screen."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/text","title":"URLSource.text","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceText"}],"url":"\/documentation\/zendesksdk\/urlsource\/text"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/zendesksdk\/urlsource\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/RawRepresentable-Implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/init(rawValue:)":{"role":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/zendesksdk\/urlsource\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/zendesksdk\/urlsource\/equatable-implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"code":"URL","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","navigatorTitle":[{"kind":"identifier","text":"URLSource"}],"url":"\/documentation\/zendesksdk\/urlsource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}],"title":"URLSource"},"doc://com.zendesk.Zendesk/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.Zendesk\/SY","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKURLSource","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKURLSource"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKURLSource","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/carousel","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/file","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/image","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/linkMessageAction","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/text","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/webViewMessageAction"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKURLSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKURLSourceImage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1image\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1image\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1carousel\/title","value":"ZDKURLSourceCarousel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1carousel\/fragments","value":[{"text":"ZDKURLSourceCarousel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1file\/title","value":"ZDKURLSourceFile"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1file\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1linkMessageAction\/title","value":"ZDKURLSourceLinkMessageAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1linkMessageAction\/fragments","value":[{"text":"ZDKURLSourceLinkMessageAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1webViewMessageAction\/title","value":"ZDKURLSourceWebViewMessageAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1webViewMessageAction\/fragments","value":[{"text":"ZDKURLSourceWebViewMessageAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1text\/title","value":"ZDKURLSourceText"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1text\/fragments","value":[{"text":"ZDKURLSourceText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}]}]}]}