{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationDisplayed"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/zdknotificationdisplayed\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdknotificationdisplayed\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationDisplayed\/data","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"data","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayed(py)data","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"data"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"title":"NotificationDisplayedDetails","abstract":[{"type":"text","text":"Details of a notification that was displayed."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","navigatorTitle":[{"text":"NotificationDisplayedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKNotificationDisplayed":{"title":"ZDKNotificationDisplayed","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNotificationDisplayed","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdknotificationdisplayed","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationDisplayed","navigatorTitle":[{"text":"ZDKNotificationDisplayed","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKNotificationDisplayed/data":{"title":"data","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails"}],"url":"\/documentation\/zendesksdk\/zdknotificationdisplayed\/data","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationDisplayed\/data","navigatorTitle":[{"text":"data","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"data","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"data","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","kind":"typeIdentifier","text":"ZDKNotificationDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKNotificationDisplayedDetails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title"},{"value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationDisplayed\/title","value":"ZDKNotificationDisplayed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationDisplayed\/fragments","value":[{"kind":"identifier","text":"ZDKNotificationDisplayed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationDisplayed\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationDisplayed~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationDisplayed~1data\/fragments","value":[{"text":"data","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}