{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ZendeskSDK@E@AgentMessageSource","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"op","roleHeading":"Operator","extendedModule":"Swift","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"ZendeskSDK"}],"title":"!=(_:_:)"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/agentmessagesource\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/Equatable-Implementations"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/!=(_:_:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/agentmessagesource\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","title":"Equatable Implementations","type":"topic","url":"\/documentation\/zendesksdk\/agentmessagesource\/equatable-implementations","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/Equatable-Implementations","kind":"article"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource":{"title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/agentmessagesource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/title","value":"AgentMessageSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/fragments","value":[{"kind":"identifier","text":"AgentMessageSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/navigatorTitle","value":[{"text":"AgentMessageSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}