{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentCopilot"}],"roleHeading":"Case","title":"AgentMessageSource.agentCopilot","symbolKind":"case","role":"symbol","externalID":"c:@M@ZendeskSDK@E@AgentMessageSource@AgentMessageSourceAgentCopilot","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AgentMessageSourceAgentCopilot"}]},"abstract":[{"type":"text","text":"The agent’s message was generated from the Agent Copilot tool"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentCopilot"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentCopilot","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/agentmessagesource\/agentcopilot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/agentmessagesource\/agentcopilot"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource":{"title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/agentmessagesource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/agentCopilot":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentCopilot","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/agentmessagesource\/agentcopilot","abstract":[{"type":"text","text":"The agent’s message was generated from the Agent Copilot tool"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentCopilot","navigatorTitle":[{"text":"AgentMessageSourceAgentCopilot","kind":"identifier"}],"role":"symbol","title":"AgentMessageSource.agentCopilot"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AgentMessageSourceAgentCopilot","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AgentMessageSourceAgentCopilot"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"AgentMessageSourceAgentCopilot","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AgentMessageSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AgentMessageSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AgentMessageSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/navigatorTitle","op":"replace"},{"value":"AgentMessageSourceAgentCopilot","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentCopilot\/title","op":"replace"},{"value":[{"text":"AgentMessageSourceAgentCopilot","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentCopilot\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}