{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/agentmessagesource\/equatable-implementations"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ZendeskSDK"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource":{"title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/agentmessagesource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/!=(_:_:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/agentmessagesource\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/title","value":"AgentMessageSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/fragments","value":[{"text":"AgentMessageSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/navigatorTitle","value":[{"kind":"identifier","text":"AgentMessageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}