{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails(py)conversationId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"conversationId","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/conversationId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails"]]},"abstract":[{"type":"text","text":"The unique identifier of the conversation"}],"variants":[{"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/conversationid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/conversationid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/conversationId":{"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/conversationid","abstract":[{"text":"The unique identifier of the conversation","type":"text"}],"kind":"symbol","type":"topic","title":"conversationId","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/conversationId","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","abstract":[{"type":"text","text":"Details of a postback button that was clicked by the end user."}],"kind":"symbol","type":"topic","title":"PostbackButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"conversationId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"conversationId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","value":"ZDKPostbackButtonClickedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","value":[{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","value":[{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"}]}]}]}