{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/init(actionname:conversationid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/init(actionname:conversationid:)"]}],"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithActionName:conversationId:"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","title":"init(actionName:conversationId:)","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails(im)initWithActionName:conversationId:"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/init(actionName:conversationId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/init(actionName:conversationId:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithActionName:conversationId:"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/init(actionname:conversationid:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/init(actionName:conversationId:)","kind":"symbol","title":"init(actionName:conversationId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"type":"topic","abstract":[{"type":"text","text":"Details of a postback button that was clicked by the end user."}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"title":"PostbackButtonClickedDetails","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithActionName:conversationId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithActionName:conversationId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithActionName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"actionName"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1init(actionName:conversationId:)\/title","value":"initWithActionName:conversationId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1init(actionName:conversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithActionName:conversationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","value":"ZDKPostbackButtonClickedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}]}]}]}