{"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/urlsource\/linkmessageaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/urlsource\/linkmessageaction"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"User selected ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" from a ","type":"text"},{"code":"link","type":"codeVoice"},{"text":" message button from a message on the conversation screen.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"title":"URLSource.linkMessageAction","externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceLinkMessageAction","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linkMessageAction","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKURLSourceLinkMessageAction","kind":"identifier"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/linkMessageAction","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"linkMessageAction"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/linkMessageAction":{"title":"URLSource.linkMessageAction","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/linkMessageAction","url":"\/documentation\/zendesksdk\/urlsource\/linkmessageaction","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linkMessageAction","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"link"},{"type":"text","text":" message button from a message on the conversation screen."}],"navigatorTitle":[{"text":"ZDKURLSourceLinkMessageAction","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdk\/urlsource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","title":"URLSource","type":"topic","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKURLSourceLinkMessageAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceLinkMessageAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKURLSourceLinkMessageAction","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1linkMessageAction\/title","value":"ZDKURLSourceLinkMessageAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1linkMessageAction\/fragments","value":[{"text":"ZDKURLSourceLinkMessageAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"kind":"identifier","text":"ZDKURLSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}]}]}]}