{"metadata":{"modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate","title":"MessagingDelegate","role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingDelegate","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKMessagingDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/messagingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/messagingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate"},"abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)":{"type":"topic","title":"messaging(_:shouldHandleURL:from:)","required":true,"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)","navigatorTitle":[{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","defaultImplementations":1,"url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingDelegate"}],"title":"MessagingDelegate","url":"\/documentation\/zendesksdk\/messagingdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"ZDKMessagingDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessagingDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagingDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)\/title","op":"replace","value":"messaging:shouldHandleURL:from:"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:shouldHandleURL:from:"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title","op":"replace","value":"ZDKMessagingDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments","op":"replace","value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/navigatorTitle","op":"replace","value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}]}]}]}