{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/authenticationFailed","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/connectionStatusChanged","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAdded","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationOpened","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationStarted","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/messagesShown","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/sendMessageFailed","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/unreadMessageCountChanged"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"sections":[],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"]}],"metadata":{"title":"ZDKZendeskEvent","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"roleHeading":"Enumeration","modules":[{"name":"ZendeskSDK"}],"symbolKind":"enum","role":"symbol"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}]}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/Equatable-Implementations","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/equatable-implementations","kind":"article","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationStarted":{"navigatorTitle":[{"text":"ZDKZendeskEventConversationStarted","kind":"identifier"}],"title":"ZDKZendeskEvent.conversationStarted","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationStarted","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationstarted","type":"topic","abstract":[{"text":"Invoked when the conversation is started on the device.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationStarted","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/unreadMessageCountChanged":{"abstract":[{"text":"Invoked when there is a change to the current total number of unread messages.","type":"text"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/unreadmessagecountchanged","navigatorTitle":[{"text":"ZDKZendeskEventUnreadMessageCountChanged","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/unreadMessageCountChanged","type":"topic","title":"ZDKZendeskEvent.unreadMessageCountChanged","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadMessageCountChanged","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","kind":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"title":"ZDKZendeskEvent","role":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationOpened":{"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationopened","navigatorTitle":[{"text":"ZDKZendeskEventConversationOpened","kind":"identifier"}],"type":"topic","title":"ZDKZendeskEvent.conversationOpened","kind":"symbol","role":"symbol","abstract":[{"text":"Invoked when the conversation screen is opened.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationOpened","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationOpened","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/authenticationFailed":{"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/authenticationfailed","abstract":[{"type":"text","text":"Invoked when a rest call fails for authentication reasons."}],"title":"ZDKZendeskEvent.authenticationFailed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventAuthenticationFailed"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/authenticationFailed","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/connectionStatusChanged":{"type":"topic","title":"ZDKZendeskEvent.connectionStatusChanged","navigatorTitle":[{"text":"ZDKZendeskEventConnectionStatusChanged","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/connectionStatusChanged","abstract":[{"type":"text","text":"The SDK "},{"type":"codeVoice","code":"ConnectionStatus"},{"type":"text","text":" has changed due to an action or another event."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStatusChanged","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/connectionstatuschanged","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationAdded":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAdded","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationAdded"}],"abstract":[{"text":"Invoked when a conversation has been added.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConversationAdded"}],"title":"ZDKZendeskEvent.conversationAdded","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationadded","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/RawRepresentable-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.zendesk.Zendesk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/init(rawValue:)","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"title":"init(rawValue:)","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/sendMessageFailed":{"abstract":[{"text":"Invoked when a message fails to be sent.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/sendMessageFailed","title":"ZDKZendeskEvent.sendMessageFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessageFailed"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/sendmessagefailed","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventSendMessageFailed"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/messagesShown":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventMessagesShown"}],"type":"topic","title":"ZDKZendeskEvent.messagesShown","abstract":[{"type":"text","text":"Invoked when the messages shown to the user are updated."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/messagesShown","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/messagesshown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesShown"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/authenticationFailed","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/connectionStatusChanged","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAdded","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationOpened","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationStarted","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/messagesShown","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/sendMessageFailed","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/unreadMessageCountChanged"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationStarted\/title","value":"ZDKZendeskEventConversationStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationStarted\/fragments","value":[{"text":"ZDKZendeskEventConversationStarted","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1unreadMessageCountChanged\/title","value":"ZDKZendeskEventUnreadMessageCountChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1unreadMessageCountChanged\/fragments","value":[{"text":"ZDKZendeskEventUnreadMessageCountChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationOpened\/title","value":"ZDKZendeskEventConversationOpened"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationOpened\/fragments","value":[{"text":"ZDKZendeskEventConversationOpened","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1authenticationFailed\/title","value":"ZDKZendeskEventAuthenticationFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1authenticationFailed\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventAuthenticationFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1connectionStatusChanged\/title","value":"ZDKZendeskEventConnectionStatusChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1connectionStatusChanged\/fragments","value":[{"text":"ZDKZendeskEventConnectionStatusChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAdded\/title","value":"ZDKZendeskEventConversationAdded"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAdded\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationAdded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1sendMessageFailed\/title","value":"ZDKZendeskEventSendMessageFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1sendMessageFailed\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventSendMessageFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1messagesShown\/title","value":"ZDKZendeskEventMessagesShown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1messagesShown\/fragments","value":[{"text":"ZDKZendeskEventMessagesShown","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}