{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus"]]},"sections":[],"metadata":{"roleHeading":"Case","title":"ZendeskConnectionStatus.connectingRealtime","symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus@ZDKZendeskConnectionStatusConnectingRealtime","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connectingRealtime","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnectingRealtime"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connectingRealtime","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectingRealtime"},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectingrealtime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectingrealtime"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The SDK instance is establishing the realtime connection with the server.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connectingRealtime":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectingRealtime","type":"topic","title":"ZendeskConnectionStatus.connectingRealtime","abstract":[{"text":"The SDK instance is establishing the realtime connection with the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectingRealtime"}],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectingrealtime","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnectingRealtime","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"title":"ZendeskConnectionStatus","abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","type":"topic","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","role":"symbol","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskConnectionStatusConnectingRealtime","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ZDKZendeskConnectionStatusConnectingRealtime","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnectingRealtime"}],"platforms":["iOS"]}]}},{"value":"ZDKZendeskConnectionStatusConnectingRealtime","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectingRealtime\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKZendeskConnectionStatusConnectingRealtime","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectingRealtime\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","op":"replace","value":"ZDKZendeskConnectionStatus"},{"value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments"}]}]}