{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"messaging:shouldHandleURL:from:"}],"required":true,"symbolKind":"method","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate(im)messaging:shouldHandleURL:from:","modules":[{"name":"ZendeskSDK"}],"title":"messaging(_:shouldHandleURL:from:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"defaultImplementationsSections":[{"title":"MessagingDelegate Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18"],"anchor":"MessagingDelegate-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messaging","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" instance"}]}],"name":"messaging"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" the user actioned."}]}],"name":"url"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"source"},{"type":"text","text":" from which the user actioned the URL from."}]}],"name":"source"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if Messaging should handle the URL. Return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if there is a specified URL flow.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"Return ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" when there is no way to handle a specific URL and ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" will perform OS default behaviour of opening","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" in the default browser.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)-97e18":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier","text":"Messaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18","title":"messaging(_:shouldHandleURL:from:)","type":"topic","url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-97e18","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)":{"type":"topic","title":"messaging(_:shouldHandleURL:from:)","required":true,"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)","navigatorTitle":[{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","defaultImplementations":1,"url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"url":"\/documentation\/zendesksdk\/messaging","title":"Messaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingDelegate"}],"title":"MessagingDelegate","url":"\/documentation\/zendesksdk\/messagingdelegate"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"title":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}],"type":"topic","url":"\/documentation\/zendesksdk\/urlsource","role":"symbol","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"URLSource"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"messaging:shouldHandleURL:from:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:shouldHandleURL:from:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messaging:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","text":"ZDKMessaging"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldHandleURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","text":"ZDKURLSource"},{"kind":"text","text":") "},{"kind":"internalParam","text":"source"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"messaging","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":" instance","type":"text"}],"type":"paragraph"}]},{"name":"url","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" the user actioned.","type":"text"}],"type":"paragraph"}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"source","type":"codeVoice"},{"type":"text","text":" from which the user actioned the URL from."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if Messaging should handle the URL. Return "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if there is a specified URL flow."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"messaging:shouldHandleURL:from:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:shouldHandleURL:from:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)\/fragments"},{"value":"ZDKMessaging","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle"},{"value":"ZDKMessagingDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title"},{"value":[{"kind":"identifier","text":"ZDKMessagingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments"},{"value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/navigatorTitle"},{"value":"ZDKURLSource","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title"},{"value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments"},{"value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle"}]}]}