{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"ZendeskSDK","relatedModules":["Swift"]}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@ZendeskSDK@E@NewConversationSource","symbolKind":"method","extendedModule":"Swift","title":"hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]}},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdk\/newconversationsource\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hash(into:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/RawRepresentable-Implementations","url":"\/documentation\/zendesksdk\/newconversationsource\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/hash(into:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"role":"symbol","kind":"symbol","title":"hash(into:)","url":"\/documentation\/zendesksdk\/newconversationsource\/hash(into:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","navigatorTitle":[{"kind":"identifier","text":"NewConversationSource"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationSource","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/newconversationsource","role":"symbol","abstract":[{"type":"text","text":"Enum representing sources or locations where the new conversation button can be clicked."}],"title":"NewConversationSource","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title","op":"replace","value":"NewConversationSource"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments","op":"replace","value":[{"text":"NewConversationSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle","op":"replace","value":[{"text":"NewConversationSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}