{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/hashValue"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/hash(into:)"],"anchor":"Instance-Methods"}],"metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"ZendeskSDK"}],"roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","title":"ZDKZendeskEvent","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/hashValue":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hashValue","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/hashValue","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/hashvalue","role":"symbol","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/hash(into:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/hash(into:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/hash(into:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hash(into:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"}]}]}