{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/sendmessagefailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/sendmessagefailed"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/sendMessageFailed"},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"ZDKZendeskEventSendMessageFailed","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","title":"ZDKZendeskEvent.sendMessageFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendMessageFailed","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventSendMessageFailed","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendMessageFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"abstract":[{"text":"Invoked when a message fails to be sent.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/sendMessageFailed":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/sendMessageFailed","navigatorTitle":[{"text":"ZDKZendeskEventSendMessageFailed","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/sendmessagefailed","kind":"symbol","type":"topic","title":"ZDKZendeskEvent.sendMessageFailed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendMessageFailed","kind":"identifier"}],"abstract":[{"type":"text","text":"Invoked when a message fails to be sent."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","title":"ZDKZendeskEvent","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEventSendMessageFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskEventSendMessageFailed","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventSendMessageFailed"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1sendMessageFailed\/title","value":"ZDKZendeskEventSendMessageFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1sendMessageFailed\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventSendMessageFailed"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","op":"replace","value":"ZDKZendeskEvent"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}