{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/data","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails"}],"symbolKind":"property","navigatorTitle":[{"text":"data","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayed(py)data","title":"data","modules":[{"name":"ZendeskSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/data"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/data"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed/data":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"type":"topic","title":"data","url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/data"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","role":"symbol","title":"ProactiveMessageDisplayedDetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Details of a proactive message that was displayed."}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed":{"type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"title":"ZDKProactiveMessageDisplayed","navigatorTitle":[{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"data"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier","text":"ZDKProactiveMessageDisplayedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/title","value":"ZDKProactiveMessageDisplayedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/fragments","value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/navigatorTitle"},{"value":"ZDKProactiveMessageDisplayed","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/title"},{"value":[{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/fragments"},{"value":[{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/navigatorTitle"}]}]}