{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","text":"ArticleClickedDetails"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"data"}],"title":"data","symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","kind":"typeIdentifier","text":"ArticleClickedDetails"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClicked(py)data"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked\/data"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked\/data"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/data","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails":{"title":"ArticleClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleClickedDetails","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked/data":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/data","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","text":"ArticleClickedDetails","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkarticleclicked\/data","abstract":[],"type":"topic","title":"data","navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleClicked"}],"url":"\/documentation\/zendesksdk\/zdkarticleclicked","navigatorTitle":[{"kind":"identifier","text":"ZDKArticleClicked"}],"kind":"symbol","abstract":[],"type":"topic","title":"ZDKArticleClicked","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"data","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","text":"ZDKArticleClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/title","value":"ZDKArticleClickedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/fragments","value":[{"text":"ZDKArticleClickedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/navigatorTitle","value":[{"text":"ZDKArticleClickedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1data\/title","value":"data","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1data\/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/title","value":"ZDKArticleClicked","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/fragments","value":[{"text":"ZDKArticleClicked","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/navigatorTitle","value":[{"text":"ZDKArticleClicked","kind":"identifier"}],"op":"replace"}]}]}