{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"title":"timestamp","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClicked(py)timestamp","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked\/timestamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked\/timestamp"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/timestamp"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked/timestamp":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/timestamp","abstract":[],"title":"timestamp","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/zendesksdk\/zdkarticleclicked\/timestamp","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleClicked"}],"url":"\/documentation\/zendesksdk\/zdkarticleclicked","navigatorTitle":[{"kind":"identifier","text":"ZDKArticleClicked"}],"kind":"symbol","abstract":[],"type":"topic","title":"ZDKArticleClicked","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"timestamp"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"timestamp","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1timestamp\/fragments","op":"replace","value":[{"kind":"identifier","text":"timestamp"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/title","op":"replace","value":"ZDKArticleClicked"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/fragments","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/navigatorTitle","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]}]}]}