{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/!=(_:_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ZendeskSDK","relatedModules":["Swift"]}],"role":"symbol","symbolKind":"op","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"extendedModule":"Swift","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","roleHeading":"Operator"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/Equatable-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/!=(_:_:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"!=(_:_:)","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/!=(_:_:)","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/!=(_:_:)","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","title":"ZendeskConnectionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","value":"ZDKZendeskConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace"}]}]}