{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/role"},"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskmessage\/role"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskmessage\/role"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The role of the message - whether it is sent from the business or the user."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"role","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole","text":"ZendeskRole","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","title":"role","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage(py)role","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"role"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"role","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ZendeskRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","navigatorTitle":[{"kind":"identifier","text":"ZendeskMessage"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskmessage","title":"ZendeskMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskMessage"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole":{"type":"topic","title":"ZendeskRole","url":"\/documentation\/zendesksdk\/zendeskrole","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskRole","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZendeskRole","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/role":{"title":"role","abstract":[{"text":"The role of the message - whether it is sent from the business or the user.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"role"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZendeskRole","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole"}],"url":"\/documentation\/zendesksdk\/zendeskmessage\/role","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/role"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"role","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"role","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole","text":"ZDKZendeskRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title","value":"ZDKZendeskMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/title","value":"ZDKZendeskRole","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/fragments","value":[{"text":"ZDKZendeskRole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1role\/title","value":"role","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1role\/fragments","value":[{"text":"role","kind":"identifier"}],"op":"replace"}]}]}