{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/connectionStatusChanged","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/connectionstatuschanged"]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/connectionstatuschanged"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The SDK "},{"type":"codeVoice","code":"ConnectionStatus"},{"text":" has changed due to an action or another event.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionStatusChanged"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"ZDKZendeskEvent.connectionStatusChanged","symbolKind":"case","role":"symbol","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConnectionStatusChanged","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConnectionStatusChanged"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connectionStatusChanged","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","title":"ZDKZendeskEvent","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/zendesksdk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/connectionStatusChanged":{"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConnectionStatusChanged"}],"kind":"symbol","title":"ZDKZendeskEvent.connectionStatusChanged","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/connectionStatusChanged","abstract":[{"text":"The SDK ","type":"text"},{"type":"codeVoice","code":"ConnectionStatus"},{"text":" has changed due to an action or another event.","type":"text"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/connectionstatuschanged","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectionStatusChanged","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskEventConnectionStatusChanged","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKZendeskEventConnectionStatusChanged"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKZendeskEventConnectionStatusChanged","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","op":"replace","value":"ZDKZendeskEvent"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1connectionStatusChanged\/title","op":"replace","value":"ZDKZendeskEventConnectionStatusChanged"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1connectionStatusChanged\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventConnectionStatusChanged"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}