{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceText","title":"URLSource.text","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceText"}],"modules":[{"name":"ZendeskSDK"}],"role":"symbol"},"kind":"symbol","abstract":[{"text":"User selected ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" from ","type":"text"},{"code":"text","type":"codeVoice"},{"type":"text","text":" on the Conversation screen."}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/text","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/urlsource\/text"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/urlsource\/text"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","title":"ZendeskSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/text":{"role":"symbol","url":"\/documentation\/zendesksdk\/urlsource\/text","abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from "},{"code":"text","type":"codeVoice"},{"text":" on the Conversation screen.","type":"text"}],"kind":"symbol","title":"URLSource.text","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/text","navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceText"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","url":"\/documentation\/zendesksdk\/urlsource","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"URLSource","kind":"identifier"}],"abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"title":"URLSource","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKURLSourceText","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKURLSourceText"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKURLSourceText","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKURLSourceText","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1text\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1text\/fragments","value":[{"text":"ZDKURLSourceText","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKURLSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}