{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/isEqual(_:)"},"metadata":{"roleHeading":"Instance Method","title":"isEqual(_:)","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage(im)isEqual:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskmessage\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskmessage\/isequal(_:)"]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/isEqual(_:)":{"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/isEqual(_:)","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskmessage\/isequal(_:)","type":"topic","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"navigatorTitle":[{"kind":"identifier","text":"ZendeskMessage"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskMessage"}],"title":"ZendeskMessage","url":"\/documentation\/zendesksdk\/zendeskmessage","kind":"symbol","role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1isEqual(_:)\/fragments"},{"value":"ZDKZendeskMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle"}]}]}