{"metadata":{"title":"createMessaging(with:)","externalID":"s:10ZendeskSDK23MessagingSwiftUIFactoryP06createC04withAA0cD2UICAA0C17FactoryParametersC_tF","role":"symbol","roleHeading":"Instance Method","required":true,"symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters"},{"text":") -> ","kind":"text"},{"text":"MessagingSwiftUI","kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC"}]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory\/createMessaging(with:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/messagingswiftuifactory\/createmessaging(with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","text":"MessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIFactory":{"title":"MessagingSwiftUIFactory","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUIFactory","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MessagingSwiftUIFactory","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingswiftuifactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIFactory/createMessaging(with:)":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory\/createMessaging(with:)","title":"createMessaging(with:)","required":true,"type":"topic","url":"\/documentation\/zendesksdk\/messagingswiftuifactory\/createmessaging(with:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","type":"topic","kind":"symbol","abstract":[{"text":"The set of parameters to be provided to Messaging(SwiftUI)Factory ","type":"text"},{"code":"createMessaging","type":"codeVoice"},{"text":" to create an instance of ","type":"text"},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"text":".","type":"text"}],"title":"MessagingFactoryParameters","role":"symbol","navigatorTitle":[{"text":"MessagingFactoryParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingFactoryParameters","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"type":"topic","role":"symbol","kind":"symbol","title":"MessagingSwiftUI","navigatorTitle":[{"text":"MessagingSwiftUI","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUI","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingswiftui"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","op":"replace","value":"ZDKMessagingFactoryParameters"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","op":"replace","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/navigatorTitle","op":"replace","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}]}]}]}