{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/data","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"property","role":"symbol","title":"data","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssigned(py)data","navigatorTitle":[{"text":"data","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails","kind":"typeIdentifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned\/data"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned\/data"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned/data":{"title":"data","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/data","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned\/data","navigatorTitle":[{"text":"data","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","kind":"symbol","title":"ConversationAgentAssignedDetails","abstract":[],"type":"topic","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationAgentAssignedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationAgentAssignedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned":{"title":"ZDKConversationAgentAssigned","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"url":"\/documentation\/zendesksdk\/zdkconversationagentassigned","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"data","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"data"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKConversationAgentAssignedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails"},{"text":" * ","kind":"text"},{"text":"data","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1data\/title","value":"data","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1data\/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/title","value":"ZDKConversationAgentAssignedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/title","value":"ZDKConversationAgentAssigned","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/fragments","value":[{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"op":"replace"}]}]}