{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","kind":"typeIdentifier","text":"ConversationWithAgentRequestedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/data","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationWithAgentRequestedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"}],"roleHeading":"Instance Property","title":"data","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationWithAgentRequested(py)data","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"data","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested/data":{"title":"data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationWithAgentRequestedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/data","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/data","navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"kind":"symbol","title":"ConversationWithAgentRequestedDetails","abstract":[{"text":"Details of a conversation where an agent was requested.","type":"text"}],"url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested":{"url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested","type":"topic","navigatorTitle":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested","kind":"symbol","title":"ZDKConversationWithAgentRequested","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"data","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"data"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ConversationWithAgentRequestedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"data","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1data\/title"},{"op":"replace","value":[{"text":"data","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1data\/fragments"},{"op":"replace","value":"ConversationWithAgentRequestedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/title"},{"op":"replace","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/fragments"},{"op":"replace","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/navigatorTitle"},{"op":"replace","value":"ZDKConversationWithAgentRequested","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/title"},{"op":"replace","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/fragments"},{"op":"replace","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/navigatorTitle"}]}]}