{"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","title":"timestamp","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationWithAgentRequested(py)timestamp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/timestamp","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}],"abstract":[],"url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested","title":"ZDKConversationWithAgentRequested","type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested/timestamp":{"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"title":"timestamp","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/timestamp","abstract":[],"url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/timestamp"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"timestamp"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/title","value":"ZDKConversationWithAgentRequested","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/fragments","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/navigatorTitle"},{"op":"replace","value":"timestamp","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1timestamp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"timestamp"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1timestamp\/fragments"}]}]}