{"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/invalidate(clearstorage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendesk\/invalidate(clearstorage:)"]}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidate"},{"text":"(","kind":"text"},{"text":"clearStorage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Type Method","externalID":"c:@M@ZendeskSDK@objc(cs)Zendesk(cm)invalidateWithClearStorage:","platforms":[],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"invalidateWithClearStorage:"}],"role":"symbol","title":"invalidate(clearStorage:)"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(clearStorage:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidate","kind":"identifier"},{"kind":"text","text":"("},{"text":"clearStorage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean to invalidate storage deleting all its content."}]}],"name":"clearStorage"}],"kind":"parameters"}],"abstract":[{"text":"Invalidates the current instance of ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"text":" and clears storage when ","type":"text"},{"type":"codeVoice","code":"clearStorage"},{"text":" is true.","type":"text"},{"type":"text","text":" "},{"text":"After calling this method you will have to call ","type":"text"},{"type":"codeVoice","code":"Zendesk.initialize()"},{"type":"text","text":" again if you would like to use "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/invalidate(clearStorage:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(clearStorage:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Invalidates the current instance of "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" and clears storage when "},{"code":"clearStorage","type":"codeVoice"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"After calling this method you will have to call "},{"code":"Zendesk.initialize()","type":"codeVoice"},{"type":"text","text":" again if you would like to use "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdk\/zendesk\/invalidate(clearstorage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clearStorage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"invalidateWithClearStorage:"}],"role":"symbol","title":"invalidate(clearStorage:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"type":"topic","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"role":"symbol","title":"Zendesk","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"url":"\/documentation\/zendesksdk\/zendesk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"invalidateWithClearStorage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"invalidateWithClearStorage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"invalidateWithClearStorage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"clearStorage","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"invalidateWithClearStorage:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate(clearStorage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate(clearStorage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"invalidateWithClearStorage:","kind":"identifier"}]},{"value":"Zendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","op":"replace","value":[{"text":"Zendesk","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}