{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-5q2jt"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"Messaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"messaging","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" instance"}]}]},{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" the user actioned."}],"type":"paragraph"}]},{"name":"source","content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"source","type":"codeVoice"},{"type":"text","text":" from which the user actioned the URL from."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if Messaging should handle the URL. Return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if there is a specified URL flow.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when there is no way to handle a specific URL and "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" will perform OS default behaviour of opening"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" in the default browser."}],"type":"paragraph"}],"name":"Note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-97e18"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:10ZendeskSDK17MessagingDelegatePAAE9messaging_15shouldHandleURL4fromSbAA0C0C_10Foundation0H0VAA9URLSourceOtF","title":"messaging(_:shouldHandleURL:from:)","roleHeading":"Instance Method","extendedModule":"ZendeskSDK","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier","text":"Messaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ZendeskSDK"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"url":"\/documentation\/zendesksdk\/urlsource","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"title":"URLSource","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","kind":"symbol","url":"\/documentation\/zendesksdk\/messagingdelegate","title":"MessagingDelegate","role":"symbol","abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)-97e18":{"abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"title":"messaging(_:shouldHandleURL:from:)","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-97e18","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messaging","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"title":"Messaging","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)-5q2jt":{"url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-5q2jt","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-5q2jt","type":"topic","navigatorTitle":[{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"defaultImplementations":1,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"messaging(_:shouldHandleURL:from:)","required":true,"kind":"symbol","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title","value":"ZDKMessagingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessagingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"text":"ZDKMessaging","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)-5q2jt\/title","value":"messaging:shouldHandleURL:from:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)-5q2jt\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}]}]}]}