{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hashValue"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hash(into:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"RawRepresentable Implementations","role":"collectionGroup","modules":[{"name":"ZendeskSDK"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationsource\/rawrepresentable-implementations"]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/RawRepresentable-Implementations"},"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/hash(into:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hash(into:)","type":"topic","title":"hash(into:)","url":"\/documentation\/zendesksdk\/newconversationsource\/hash(into:)","kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource/hashValue":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource\/hashValue","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/newconversationsource\/hashvalue","title":"hashValue","abstract":[],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]}},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationSource":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationSource","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NewConversationSource","kind":"identifier"}],"title":"NewConversationSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationSource","url":"\/documentation\/zendesksdk\/newconversationsource","abstract":[{"text":"Enum representing sources or locations where the new conversation button can be clicked.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/title","value":"NewConversationSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/fragments","value":[{"kind":"identifier","text":"NewConversationSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationSource\/navigatorTitle","value":[{"text":"NewConversationSource","kind":"identifier"}],"op":"replace"}]}]}