{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/init(from:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","modules":[{"relatedModules":["Swift"],"name":"ZendeskSDK"}],"title":"init(from:)","externalID":"s:SYsSeRzSi8RawValueSYRtzrlE4fromxs7Decoder_p_tKcfc::SYNTHESIZED::c:@M@ZendeskSDK@E@ZDKZendeskRole","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"extendedModule":"Swift","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Decodable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":".","type":"text"}]}},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/zendeskrole\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","type":"topic","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole":{"url":"\/documentation\/zendesksdk\/zendeskrole","type":"topic","role":"symbol","abstract":[],"title":"ZendeskRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskRole"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","navigatorTitle":[{"kind":"identifier","text":"ZendeskRole"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/init(from:)":{"title":"init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/init(from:)","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskrole\/init(from:)","type":"topic","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Decodable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" is "},{"code":"Int","type":"codeVoice"},{"type":"text","text":"."}]}},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/RawRepresentable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/zendesksdk\/zendeskrole\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"}},"variantOverrides":[{"patch":[{"value":"ZDKZendeskRole","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}