{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadMessageCountChanged","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/unreadmessagecountchanged"]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/unreadmessagecountchanged"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/unreadMessageCountChanged","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"metadata":{"title":"ZDKZendeskEvent.unreadMessageCountChanged","symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventUnreadMessageCountChanged","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unreadMessageCountChanged","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventUnreadMessageCountChanged"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"role":"symbol"},"abstract":[{"text":"Invoked when there is a change to the current total number of unread messages.","type":"text"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent","kind":"symbol","abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}],"type":"topic","title":"ZDKZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/unreadMessageCountChanged":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/unreadMessageCountChanged","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/unreadmessagecountchanged","title":"ZDKZendeskEvent.unreadMessageCountChanged","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unreadMessageCountChanged","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventUnreadMessageCountChanged"}],"type":"topic","role":"symbol","abstract":[{"text":"Invoked when there is a change to the current total number of unread messages.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKZendeskEventUnreadMessageCountChanged","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventUnreadMessageCountChanged"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventUnreadMessageCountChanged"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","op":"replace","value":"ZDKZendeskEvent"},{"value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1unreadMessageCountChanged\/title","op":"replace","value":"ZDKZendeskEventUnreadMessageCountChanged"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1unreadMessageCountChanged\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventUnreadMessageCountChanged"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}