{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/getCurrentUser()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/getcurrentuser()"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCurrentUser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZendeskUser","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCurrentUser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","text":"ZendeskUser","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"getCurrentUser()","externalID":"s:10ZendeskSDK0A0C14getCurrentUserAA0aE0CSgyF","roleHeading":"Instance Method"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","title":"Zendesk","url":"\/documentation\/zendesksdk\/zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"role":"symbol","type":"topic","title":"ZendeskUser","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskuser","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/getCurrentUser()":{"title":"getCurrentUser()","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/getCurrentUser()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCurrentUser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZendeskUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"text":"?","kind":"text"}],"url":"\/documentation\/zendesksdk\/zendesk\/getcurrentuser()","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","type":"topic","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Zendesk","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"op":"replace","value":[{"text":"Zendesk","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments"},{"op":"replace","value":[{"text":"Zendesk","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle"},{"op":"replace","value":"ZDKZendeskUser","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title"},{"op":"replace","value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments"},{"op":"replace","value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/navigatorTitle"}]}]}