{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-4i6q0","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10ZendeskSDK0A0C17sendPageViewEvent_17completionHandleryAA0dE0C_ys6ResultOyyts5Error_pGctF","symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPageViewEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","text":"PageView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"sendPageViewEvent(_:completionHandler:)","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPageViewEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pageView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PageView","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"PageView","type":"codeVoice"},{"text":" object that contains information related to a user’s interactions","type":"text"},{"text":" ","type":"text"},{"text":"e.g. the title of the page that was visited.","type":"text"}]}],"name":"pageView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block that takes a "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" enum type. In the case of a success, nothing is returned."},{"type":"text","text":" "},{"type":"text","text":"In the case of a failure an "},{"code":"Error","type":"codeVoice"},{"type":"text","text":"is returned."}]}],"name":"completionHandler"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint."}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-4i6q0"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","title":"Zendesk","url":"\/documentation\/zendesksdk\/zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:completionHandler:)-4i6q0":{"title":"sendPageViewEvent(_:completionHandler:)","abstract":[{"text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint.","type":"text"}],"url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-4i6q0","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPageViewEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-4i6q0","role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView":{"navigatorTitle":[{"kind":"identifier","text":"PageView"}],"kind":"symbol","title":"PageView","role":"symbol","url":"\/documentation\/zendesksdk\/pageview","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageView"}],"type":"topic","abstract":[{"type":"text","text":"This object is used to provide session-based data to capture contextual information about an end user. This data is viewable inside"},{"type":"text","text":" "},{"type":"text","text":"Agent Workspace."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","type":"topic","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"Zendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"text":"Zendesk","kind":"identifier"}]},{"op":"replace","value":"ZDKPageView","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/title"},{"op":"replace","value":[{"text":"ZDKPageView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/fragments"},{"op":"replace","value":[{"text":"ZDKPageView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}