{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-9xzdy"]},{"paths":["\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-9xzdy"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"method","title":"sendPageViewEvent(_:completionHandler:)","extendedModule":"ZendeskSDK","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPageViewEvent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","text":"PageView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@CM@ZendeskSDK@objc(cs)Zendesk(im)sendPageViewEvent:completionHandler:","navigatorTitle":[{"text":"sendPageViewEvent:completionHandler:","kind":"identifier"}],"platforms":[]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-9xzdy","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendPageViewEvent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageView"},{"kind":"text","text":": "},{"text":"PageView","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"PageView","type":"codeVoice"},{"text":" object that contains information related to a user’s interactions","type":"text"},{"type":"text","text":" "},{"text":"e.g. the title of the page that was visited.","type":"text"}],"type":"paragraph"}],"name":"pageView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block that takes an optional "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" which will be non-nil in the case of a failure."}]}],"name":"completionHandler"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:completionHandler:)-9xzdy":{"title":"sendPageViewEvent(_:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-9xzdy","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendPageViewEvent"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","text":"PageView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-9xzdy","type":"topic","kind":"symbol","navigatorTitle":[{"text":"sendPageViewEvent:completionHandler:","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView":{"abstract":[{"text":"This object is used to provide session-based data to capture contextual information about an end user. This data is viewable inside","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Agent Workspace."}],"kind":"symbol","title":"PageView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PageView","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","type":"topic","url":"\/documentation\/zendesksdk\/pageview","role":"symbol","navigatorTitle":[{"text":"PageView","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"kind":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"type":"topic","title":"Zendesk","role":"symbol","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","url":"\/documentation\/zendesksdk\/zendesk","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Zendesk","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"sendPageViewEvent:completionHandler:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"sendPageViewEvent:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sendPageViewEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKPageView","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1sendPageViewEvent(_:completionHandler:)-9xzdy\/title","value":"sendPageViewEvent:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1sendPageViewEvent(_:completionHandler:)-9xzdy\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendPageViewEvent:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/title","op":"replace","value":"ZDKPageView"},{"op":"replace","value":[{"text":"ZDKPageView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/fragments"},{"value":"Zendesk","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}