{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","text":"MessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactory\/createmessaging(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messagingfactory\/createmessaging(with:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory\/createMessaging(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDK@objc(pl)MessagingFactory(im)createMessagingWith:","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters"},{"text":") -> ","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"createMessagingWith:"}],"symbolKind":"method","required":true,"role":"symbol","title":"createMessaging(with:)","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","url":"\/documentation\/zendesksdk\/messagingfactory","navigatorTitle":[{"text":"MessagingFactory","kind":"identifier"}],"title":"MessagingFactory","abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagingFactory","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory/createMessaging(with:)":{"abstract":[],"url":"\/documentation\/zendesksdk\/messagingfactory\/createmessaging(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters"},{"text":") -> ","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory\/createMessaging(with:)","title":"createMessaging(with:)","kind":"symbol","role":"symbol","required":true,"navigatorTitle":[{"text":"createMessagingWith:","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"abstract":[{"text":"The set of parameters to be provided to MessagingFactory ","type":"text"},{"code":"createMessaging","type":"codeVoice"},{"type":"text","text":" to create an instance of "},{"type":"codeVoice","code":"Messaging"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","role":"symbol","navigatorTitle":[{"text":"MessagingFactoryParameters","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","kind":"symbol","title":"MessagingFactoryParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactoryParameters"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Messaging","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"title":"Messaging","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk","role":"collection","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"createMessagingWith:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"createMessagingWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","text":"ZDKMessaging","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createMessagingWith:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","text":"ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"text":"MessagingFactory","kind":"identifier"}]},{"op":"replace","value":"createMessagingWith:","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory~1createMessaging(with:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory~1createMessaging(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createMessagingWith:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","op":"replace","value":"ZDKMessagingFactoryParameters"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"},{"value":"ZDKMessaging","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments"}]}]}