{"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/!=(_:_:)"],"generated":true}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"title":"Equatable Implementations","modules":[{"name":"ZendeskSDK"}],"role":"collectionGroup","roleHeading":"API Collection"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","title":"ZendeskConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskConnectionStatus"}],"abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","navigatorTitle":[{"kind":"identifier","text":"ZendeskConnectionStatus"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/!=(_:_:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKZendeskConnectionStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle"}]}]}