{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPageTitle:url:"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPageView(im)initWithPageTitle:url:","modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"init(pageTitle:url:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"pageTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView\/init(pageTitle:url:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"pageTitle","content":[{"inlineContent":[{"type":"text","text":"The title of the page that was viewed."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The location of the page that was viewed."}]}],"name":"url"}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"code":"PageView","type":"codeVoice"},{"text":" object that is used to provide session-based data associated to an end user.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/pageview\/init(pagetitle:url:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/pageview\/init(pagetitle:url:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView":{"type":"topic","kind":"symbol","title":"PageView","role":"symbol","navigatorTitle":[{"text":"PageView","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/pageview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageView","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","abstract":[{"type":"text","text":"This object is used to provide session-based data to capture contextual information about an end user. This data is viewable inside"},{"type":"text","text":" "},{"text":"Agent Workspace.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView/init(pageTitle:url:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPageTitle:url:"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView\/init(pageTitle:url:)","type":"topic","title":"init(pageTitle:url:)","abstract":[{"type":"codeVoice","code":"PageView"},{"type":"text","text":" object that is used to provide session-based data associated to an end user."}],"url":"\/documentation\/zendesksdk\/pageview\/init(pagetitle:url:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","title":"ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithPageTitle:url:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageTitle:url:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithPageTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/title","value":"ZDKPageView"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKPageView"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView~1init(pageTitle:url:)\/title","op":"replace","value":"initWithPageTitle:url:"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView~1init(pageTitle:url:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPageTitle:url:","kind":"identifier"}],"op":"replace"}]}]}