{"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/16ZendeskSDKLogger8LoggableP"]}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendesk"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messaging","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messagingSwiftUI"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-79141","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-7l829","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-29ava","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-63scj","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-48u24","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-55qal","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/removeEventObserver(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-4i6q0","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-9xzdy"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initializationPhase","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/instance"]},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(channelKey:messagingFactory:completionHandler:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:completionHandler:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(clearStorage:)"],"title":"Type Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/Loggable-Implementations"],"generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)Zendesk","symbolKind":"class","title":"Zendesk","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}]},"references":{"doc://com.zendesk.Zendesk/16ZendeskSDKLogger8LoggableP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/16ZendeskSDKLogger8LoggableP","title":"ZendeskSDKLogger.Loggable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)":{"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"Zendesk"},{"text":" for the given ","type":"text"},{"type":"codeVoice","code":"channelKey"},{"text":". A ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"},{"type":"text","text":" for UIKit or "},{"code":"MessagingSwiftUIFactory","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"for SwiftUI can be optionally passed here to add the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability. This method is an asynchronous call"},{"text":" ","type":"text"},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"code":"completionHandler","type":"codeVoice"},{"type":"text","text":" with the result."}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:completionhandler:)","title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withChannelKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"messagingSwiftUIFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP","text":"MessagingSwiftUIFactory"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:)":{"role":"symbol","type":"topic","kind":"symbol","title":"sendPageViewEvent(_:)","url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPageViewEvent"},{"text":"(","kind":"text"},{"text":"PageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)":{"role":"symbol","type":"topic","kind":"symbol","title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withChannelKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"text":"MessagingFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"?, "},{"text":"messagingSwiftUIFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingSwiftUIFactory","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"}],"abstract":[{"text":"Initializes ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" for the given "},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":". A "},{"code":"MessagingFactory","type":"codeVoice"},{"text":" for UIKit or ","type":"text"},{"code":"MessagingSwiftUIFactory","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"for SwiftUI can be optionally passed here to add the "},{"type":"codeVoice","code":"Messaging"},{"text":" capability. This method is an asynchronous call","type":"text"},{"type":"text","text":" "},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:completionHandler:)":{"role":"symbol","type":"topic","kind":"symbol","title":"initialize(withChannelKey:messagingFactory:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:completionhandler:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"code":"channelKey","type":"codeVoice"},{"text":". A ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"},{"text":" can be optionally passed here","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to add the "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"code":"completionHandler","type":"codeVoice"},{"type":"text","text":" with the result."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:completionHandler:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/instance":{"role":"symbol","type":"topic","kind":"symbol","title":"instance","url":"\/documentation\/zendesksdk\/zendesk\/instance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":": ","kind":"text"},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Optional property allows integrators to interact with the initialized "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/instance","navigatorTitle":[{"text":"instance","kind":"identifier"}]},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/invalidate()":{"role":"symbol","type":"topic","kind":"symbol","title":"invalidate()","deprecated":true,"url":"\/documentation\/zendesksdk\/zendesk\/invalidate()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidate"},{"text":"()","kind":"text"}],"abstract":[{"text":"Invalidates the current instance of ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"After calling this method you will have to call ","type":"text"},{"type":"codeVoice","code":"Zendesk.initialize()"},{"text":" again if you would like to use ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate()","navigatorTitle":[{"text":"invalidate","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/logoutUser(completionHandler:)-55qal":{"title":"logoutUser(completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/logoutuser(completionhandler:)-55qal","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"logoutUserWithCompletionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logoutUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-55qal","type":"topic","abstract":[{"type":"text","text":"Unauthenticate a user."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:completionHandler:)-9xzdy":{"role":"symbol","type":"topic","kind":"symbol","title":"sendPageViewEvent(_:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-9xzdy","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendPageViewEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","text":"PageView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-9xzdy","navigatorTitle":[{"text":"sendPageViewEvent:completionHandler:","kind":"identifier"}]},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/logoutUser()":{"role":"symbol","type":"topic","kind":"symbol","title":"logoutUser()","url":"\/documentation\/zendesksdk\/zendesk\/logoutuser()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logoutUser","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Unauthenticate a user."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser()"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/Loggable-Implementations":{"url":"\/documentation\/zendesksdk\/zendesk\/loggable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/Loggable-Implementations","role":"collectionGroup","type":"topic","title":"Loggable Implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/loginUser(with:completionHandler:)-63scj":{"role":"symbol","type":"topic","kind":"symbol","title":"loginUser(with:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-63scj","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ZendeskUser","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Authenticate a user."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-63scj"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/messagingSwiftUI":{"kind":"symbol","abstract":[{"text":"Optional property allows integrators to interact with the ","type":"text"},{"type":"codeVoice","code":"MessagingSwiftUI"},{"type":"text","text":" capability and its feature set."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingSwiftUI"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC"},{"text":"?","kind":"text"}],"url":"\/documentation\/zendesksdk\/zendesk\/messagingswiftui","type":"topic","title":"messagingSwiftUI","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messagingSwiftUI"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(channelKey:messagingFactory:completionHandler:)":{"url":"\/documentation\/zendesksdk\/zendesk\/initialize(channelkey:messagingfactory:completionhandler:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(channelKey:messagingFactory:completionHandler:)","abstract":[{"type":"text","text":"Initializes "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" for the given "},{"code":"channelKey","type":"codeVoice"},{"text":". A ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"},{"type":"text","text":" can be optionally passed here"},{"type":"text","text":" "},{"text":"to add the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"code":"completionHandler","type":"codeVoice"},{"type":"text","text":" with the result."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"channelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initializeWithChannelKey:messagingFactory:completionHandler:","kind":"identifier"}],"title":"initialize(channelKey:messagingFactory:completionHandler:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/invalidate(clearStorage:)":{"role":"symbol","type":"topic","kind":"symbol","title":"invalidate(clearStorage:)","url":"\/documentation\/zendesksdk\/zendesk\/invalidate(clearstorage:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"invalidate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clearStorage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invalidates the current instance of "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" and clears storage when "},{"type":"codeVoice","code":"clearStorage"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"After calling this method you will have to call "},{"type":"codeVoice","code":"Zendesk.initialize()"},{"type":"text","text":" again if you would like to use "},{"type":"codeVoice","code":"Zendesk"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(clearStorage:)","navigatorTitle":[{"text":"invalidateWithClearStorage:","kind":"identifier"}]},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/messaging":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"messaging","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messaging","url":"\/documentation\/zendesksdk\/zendesk\/messaging","abstract":[{"text":"Optional property allows integrators to interact with the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability"},{"text":" ","type":"text"},{"text":"and its feature set.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messaging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"kind":"text","text":"?"}],"title":"messaging"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/addEventObserver(_:_:)-7l829":{"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zendesk\/addeventobserver(_:_:)-7l829","title":"addEventObserver(_:_:)","abstract":[{"type":"text","text":"Add an event observer to observe events emitted from "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addEventObserver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"text":", ((","kind":"text"},{"text":"ZDKZendeskEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskEvent"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-7l829","navigatorTitle":[{"text":"addEventObserver::","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/loginUser(with:completionHandler:)-29ava":{"role":"symbol","type":"topic","kind":"symbol","title":"loginUser(with:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-29ava","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loginUser"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","text":"ZendeskUser","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Authenticate a user."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-29ava","navigatorTitle":[{"text":"loginUserWith:completionHandler:","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"}],"type":"topic","title":"initialize(withChannelKey:messagingFactory:)","kind":"symbol","abstract":[{"text":"Initializes ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"type":"codeVoice","code":"channelKey"},{"text":". A ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"},{"type":"text","text":" can be optionally passed here"},{"type":"text","text":" "},{"type":"text","text":"to add the "},{"code":"Messaging","type":"codeVoice"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/invalidate(_:)":{"url":"\/documentation\/zendesksdk\/zendesk\/invalidate(_:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(_:)","role":"symbol","abstract":[{"type":"text","text":"Invalidates the current instance of "},{"type":"codeVoice","code":"Zendesk"},{"text":" and clears storage when ","type":"text"},{"code":"clearStorage","type":"codeVoice"},{"type":"text","text":" is true."},{"text":" ","type":"text"},{"text":"After calling this method you will have to call ","type":"text"},{"code":"Zendesk.initialize()","type":"codeVoice"},{"type":"text","text":" again if you would like to use "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"invalidate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"title":"invalidate(_:)","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/loginUser(with:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:)","abstract":[{"type":"text","text":"Authenticate a user."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ZendeskUser","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdk\/zendesk\/loginuser(with:)","role":"symbol","kind":"symbol","type":"topic","title":"loginUser(with:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/logoutUser(completionHandler:)-48u24":{"title":"logoutUser(completionHandler:)","type":"topic","abstract":[{"type":"text","text":"Unauthenticate a user."}],"url":"\/documentation\/zendesksdk\/zendesk\/logoutuser(completionhandler:)-48u24","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logoutUser","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-48u24"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/sendPageViewEvent(_:completionHandler:)-4i6q0":{"type":"topic","kind":"symbol","title":"sendPageViewEvent(_:completionHandler:)","role":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/sendpageviewevent(_:completionhandler:)-4i6q0","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendPageViewEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"PageView","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPageView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-4i6q0","abstract":[{"text":"Send a page view event, that captures a specific user interaction, to the PageView endpoint.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initializationPhase":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initializationPhase","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationPhase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK19InitializationPhaseO","text":"InitializationPhase"}],"title":"initializationPhase","url":"\/documentation\/zendesksdk\/zendesk\/initializationphase","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/removeEventObserver(_:)":{"navigatorTitle":[{"kind":"identifier","text":"removeEventObserver:"}],"abstract":[{"type":"text","text":"Remove event observer to stop observing events emitted by from "},{"type":"codeVoice","code":"Zendesk"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeEventObserver","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s9AnyObjecta","kind":"typeIdentifier","text":"AnyObject"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"removeEventObserver(_:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/removeEventObserver(_:)","role":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/removeeventobserver(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/addEventObserver(_:_:)-79141":{"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zendesk\/addeventobserver(_:_:)-79141","title":"addEventObserver(_:_:)","abstract":[{"text":"Add an event observer to observe events emitted from ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventObserver"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject","kind":"typeIdentifier"},{"text":", (","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK0A5EventO","kind":"typeIdentifier","text":"ZendeskEvent"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-79141"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"title":"Zendesk","url":"\/documentation\/zendesksdk\/zendesk","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","type":"topic","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"Zendesk","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"Zendesk"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messaging"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-7l829","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-29ava","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-55qal","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/removeEventObserver(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/sendPageViewEvent(_:completionHandler:)-9xzdy"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(channelKey:messagingFactory:completionHandler:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate(clearStorage:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","value":"instance","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1instance\/title"},{"value":[{"text":"instance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1instance\/fragments"},{"op":"replace","value":"invalidate","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"invalidate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate()\/fragments"},{"value":"logoutUserWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1logoutUser(completionHandler:)-55qal\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1logoutUser(completionHandler:)-55qal\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logoutUserWithCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1sendPageViewEvent(_:completionHandler:)-9xzdy\/title","value":"sendPageViewEvent:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1sendPageViewEvent(_:completionHandler:)-9xzdy\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendPageViewEvent:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1initialize(channelKey:messagingFactory:completionHandler:)\/title","op":"replace","value":"initializeWithChannelKey:messagingFactory:completionHandler:"},{"value":[{"kind":"text","text":"+ "},{"text":"initializeWithChannelKey:messagingFactory:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1initialize(channelKey:messagingFactory:completionHandler:)\/fragments","op":"replace"},{"value":"invalidateWithClearStorage:","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate(clearStorage:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate(clearStorage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"invalidateWithClearStorage:","kind":"identifier"}],"op":"replace"},{"value":"messaging","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1messaging\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1messaging\/fragments","value":[{"text":"messaging","kind":"identifier"}]},{"op":"replace","value":"addEventObserver::","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1addEventObserver(_:_:)-7l829\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addEventObserver::","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1addEventObserver(_:_:)-7l829\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1loginUser(with:completionHandler:)-29ava\/title","value":"loginUserWith:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1loginUser(with:completionHandler:)-29ava\/fragments","value":[{"kind":"text","text":"- "},{"text":"loginUserWith:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1removeEventObserver(_:)\/title","value":"removeEventObserver:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeEventObserver:"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1removeEventObserver(_:)\/fragments"},{"value":"Zendesk","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","op":"replace"},{"value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}