{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messaging"]},{"paths":["\/documentation\/zendesksdk\/messaging"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","modules":[{"name":"ZendeskSDK"}],"title":"Messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKMessaging) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Messaging","kind":"identifier"}]}]}],"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationFields()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationTags()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/getUnreadMessageCount()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationFields(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationTags(_:)"]},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/delegate"],"title":"Type Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"},"references":{"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/messagingViewController()":{"abstract":[{"type":"text","text":"Retrieve a view controller that either displays a conversation or a list of conversations, depending on business logic."}],"type":"topic","title":"messagingViewController()","navigatorTitle":[{"kind":"identifier","text":"messagingViewController"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController()","kind":"symbol","url":"\/documentation\/zendesksdk\/messaging\/messagingviewcontroller()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingViewController"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/clearConversationTags()":{"title":"clearConversationTags()","kind":"symbol","url":"\/documentation\/zendesksdk\/messaging\/clearconversationtags()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearConversationTags","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationTags()","type":"topic","navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Clears all custom tags from storage."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/setConversationTags(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"abstract":[{"text":"Provide an array of tags.","type":"text"}],"title":"setConversationTags(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setConversationTags:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationTags(_:)","url":"\/documentation\/zendesksdk\/messaging\/setconversationtags(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/clearConversationFields()":{"url":"\/documentation\/zendesksdk\/messaging\/clearconversationfields()","abstract":[{"type":"text","text":"Clears all custom fields from storage."}],"role":"symbol","title":"clearConversationFields()","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationFields()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearConversationFields"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearConversationFields"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/setConversationFields(_:)":{"navigatorTitle":[{"text":"setConversationFields:","kind":"identifier"}],"abstract":[{"text":"Provide a dictionary of custom fields.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationFields(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationFields"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"url":"\/documentation\/zendesksdk\/messaging\/setconversationfields(_:)","title":"setConversationFields(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/delegate":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/delegate","url":"\/documentation\/zendesksdk\/messaging\/delegate","abstract":[{"type":"text","text":"Delegate that allows you to observe user interactions that happen in the SDK."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"MessagingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","kind":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/getUnreadMessageCount()":{"title":"getUnreadMessageCount()","url":"\/documentation\/zendesksdk\/messaging\/getunreadmessagecount()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUnreadMessageCount"}],"abstract":[{"text":"Returns the current total number of unread messages.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/getUnreadMessageCount()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUnreadMessageCount"},{"kind":"text","text":"() -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessaging/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessaging\/init","type":"topic","role":"symbol","title":"init","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkmessaging\/init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","url":"\/documentation\/zendesksdk\/messaging","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"role":"symbol","title":"Messaging","kind":"symbol"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKMessaging"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKMessaging"}],"op":"replace"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationFields()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationTags()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/getUnreadMessageCount()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController()","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationFields(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/setConversationTags(_:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessaging\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/delegate"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKMessaging"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1messagingViewController()\/title","op":"replace","value":"messagingViewController"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1messagingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"text":"messagingViewController","kind":"identifier"}],"op":"replace"},{"value":"clearConversationTags","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationTags()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationTags()\/fragments","value":[{"kind":"text","text":"- "},{"text":"clearConversationTags","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1setConversationTags(_:)\/title","value":"setConversationTags:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1setConversationTags(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConversationTags:"}]},{"op":"replace","value":"clearConversationFields","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationFields()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationFields()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearConversationFields"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1setConversationFields(_:)\/title","value":"setConversationFields:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1setConversationFields(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setConversationFields:","kind":"identifier"}]},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1delegate\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"value":"getUnreadMessageCount","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1getUnreadMessageCount()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1getUnreadMessageCount()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getUnreadMessageCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments"}]}]}