{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The SDK instance has no internet connection."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}]}]}],"metadata":{"navigatorTitle":[{"text":"ZDKZendeskConnectionStatusDisconnected","kind":"identifier"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}],"title":"ZendeskConnectionStatus.disconnected","roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus@ZDKZendeskConnectionStatusDisconnected"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/disconnected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/disconnected"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/disconnected"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"type":"topic","role":"symbol","title":"ZendeskConnectionStatus"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/disconnected":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The SDK instance has no internet connection."}],"type":"topic","title":"ZendeskConnectionStatus.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/disconnected","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/disconnected","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusDisconnected"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKZendeskConnectionStatusDisconnected","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskConnectionStatusDisconnected","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusDisconnected"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","value":"ZDKZendeskConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1disconnected\/title","value":"ZDKZendeskConnectionStatusDisconnected","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1disconnected\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusDisconnected"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}