{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The postback button action name"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/actionname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/actionname"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/actionName","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","symbolKind":"property","title":"actionName","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails(py)actionName","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"actionName"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/actionName":{"navigatorTitle":[{"text":"actionName","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The postback button action name"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/actionname","title":"actionName","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/actionName"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"role":"symbol","navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Details of a postback button that was clicked by the end user."}],"title":"PostbackButtonClickedDetails","url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"actionName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"actionName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"actionName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1actionName\/title","op":"replace","value":"actionName"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1actionName\/fragments","op":"replace","value":[{"text":"actionName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","op":"replace","value":"ZDKPostbackButtonClickedDetails"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","op":"replace","value":[{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}