{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","text":"MessagingDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"modules":[{"name":"ZendeskSDK"}],"title":"delegate","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(cpy)delegate","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate","text":"MessagingDelegate"},{"kind":"text","text":"?"}]},"sections":[],"abstract":[{"text":"Delegate that allows you to observe user interactions that happen in the SDK.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/delegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messaging\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messaging\/delegate"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","kind":"symbol","url":"\/documentation\/zendesksdk\/messagingdelegate","title":"MessagingDelegate","role":"symbol","abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messaging","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"title":"Messaging","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/delegate":{"role":"symbol","type":"topic","abstract":[{"text":"Delegate that allows you to observe user interactions that happen in the SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/delegate","url":"\/documentation\/zendesksdk\/messaging\/delegate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate","kind":"typeIdentifier","text":"MessagingDelegate"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<ZDKMessagingDelegate>","preciseIdentifier":"c:Qo@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKMessagingDelegate","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title","op":"replace"},{"value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments","op":"replace"},{"value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/navigatorTitle","op":"replace"},{"value":"ZDKMessaging","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1delegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1delegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}