{"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispatchEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKDispatchEvent","text":"DispatchEvent"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK26MessagingFactoryParametersC13dispatchEventAA08DispatchG0Cvp","role":"symbol","title":"dispatchEvent"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters\/dispatchevent"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dispatchEvent","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/DispatchEvent","text":"DispatchEvent","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKDispatchEvent","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/dispatchEvent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/DispatchEvent":{"url":"\/documentation\/zendesksdk\/dispatchevent","abstract":[{"type":"text","text":"A wrapper class for a block that takes "},{"code":"ZendeskEvent","type":"codeVoice"},{"type":"text","text":" type and returns "},{"code":"Void","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/DispatchEvent","title":"DispatchEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DispatchEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DispatchEvent","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/dispatchEvent":{"url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/dispatchevent","title":"dispatchEvent","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/dispatchEvent","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dispatchEvent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKDispatchEvent","text":"DispatchEvent","kind":"typeIdentifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactoryParameters"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactoryParameters"}],"title":"MessagingFactoryParameters","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","abstract":[{"type":"text","text":"The set of parameters to be provided to Messaging(SwiftUI)Factory "},{"code":"createMessaging","type":"codeVoice"},{"type":"text","text":" to create an instance of "},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/title","value":"ZDKDispatchEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/fragments","value":[{"kind":"identifier","text":"ZDKDispatchEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/navigatorTitle","value":[{"text":"ZDKDispatchEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","value":"ZDKMessagingFactoryParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/navigatorTitle","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}