{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ColorTheme","preciseIdentifier":"s:10ZendeskSDK10ColorThemeV","text":"ColorTheme"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"theme","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK10ColorThemeV","text":"ColorTheme","kind":"typeIdentifier"}],"title":"theme","externalID":"s:10ZendeskSDK26MessagingFactoryParametersC5themeAA10ColorThemeVvp","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters\/theme"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/theme","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/theme":{"title":"theme","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorTheme","preciseIdentifier":"s:10ZendeskSDK10ColorThemeV"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/theme","url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/theme","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactoryParameters"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactoryParameters"}],"title":"MessagingFactoryParameters","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","abstract":[{"type":"text","text":"The set of parameters to be provided to Messaging(SwiftUI)Factory "},{"code":"createMessaging","type":"codeVoice"},{"type":"text","text":" to create an instance of "},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ColorTheme":{"title":"ColorTheme","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdk\/colortheme","navigatorTitle":[{"kind":"identifier","text":"ColorTheme"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorTheme"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ColorTheme"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","value":"ZDKMessagingFactoryParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessagingFactoryParameters"}],"op":"replace"}]}]}