{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/image"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceImage","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceImage"}],"title":"URLSource.image"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"text":" from a ","type":"text"},{"code":"image","type":"codeVoice"},{"type":"text","text":" message on the conversation screen."}],"variants":[{"paths":["\/documentation\/zendesksdk\/urlsource\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/urlsource\/image"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/image":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/image","type":"topic","url":"\/documentation\/zendesksdk\/urlsource\/image","title":"URLSource.image","role":"symbol","abstract":[{"type":"text","text":"User selected "},{"code":"URL","type":"codeVoice"},{"text":" from a ","type":"text"},{"type":"codeVoice","code":"image"},{"type":"text","text":" message on the conversation screen."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKURLSourceImage"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","title":"ZendeskSDK","abstract":[],"url":"\/documentation\/zendesksdk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","type":"topic","url":"\/documentation\/zendesksdk\/urlsource","title":"URLSource","role":"symbol","abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"navigatorTitle":[{"text":"URLSource","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKURLSourceImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKURLSourceImage"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKURLSourceImage"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1image\/title","op":"replace","value":"ZDKURLSourceImage"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1image\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","op":"replace","value":"ZDKURLSource"},{"value":[{"kind":"identifier","text":"ZDKURLSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}