{"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/zdkproactivemessageclicked\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkproactivemessageclicked\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"data","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClicked(py)data","modules":[{"name":"ZendeskSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"data"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","text":"ProactiveMessageClickedDetails"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/data"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked/data":{"abstract":[],"url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked\/data","role":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/data","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","kind":"typeIdentifier"}],"title":"data"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked":{"url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"title":"ZDKProactiveMessageClicked"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails":{"navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageClickedDetails"}],"abstract":[{"type":"text","text":"Details of a proactive message that was clicked."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails","role":"symbol","type":"topic","title":"ProactiveMessageClickedDetails","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageClickedDetails"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"data"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKProactiveMessageClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails"},{"text":" * ","kind":"text"},{"text":"data","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","value":"ZDKProactiveMessageClicked","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/title"},{"op":"replace","value":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/fragments"},{"op":"replace","value":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/navigatorTitle"},{"op":"replace","value":"ZDKProactiveMessageClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/title"},{"op":"replace","value":[{"text":"ZDKProactiveMessageClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}