{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/conversationId"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The ID of the conversation associated with the notification","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails\/conversationid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails\/conversationid"]}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"symbolKind":"property","title":"conversationId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails(py)conversationId"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/conversationId":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/conversationId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"abstract":[{"text":"The ID of the conversation associated with the notification","type":"text"}],"type":"topic","title":"conversationId","url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/conversationid","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","abstract":[{"text":"Details of a notification that was displayed.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"NotificationDisplayedDetails","kind":"identifier"}],"title":"NotificationDisplayedDetails","type":"topic","url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"conversationId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"conversationId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title","value":"ZDKNotificationDisplayedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}