{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"init(proactiveMessageId:campaignId:)","role":"symbol","navigatorTitle":[{"text":"initWithProactiveMessageId:campaignId:","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"campaignId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails(im)initWithProactiveMessageId:campaignId:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"campaignId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/init(proactiveMessageId:campaignId:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/init(proactivemessageid:campaignid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/init(proactivemessageid:campaignid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails/init(proactiveMessageId:campaignId:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/init(proactiveMessageId:campaignId:)","url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/init(proactivemessageid:campaignid:)","abstract":[],"title":"init(proactiveMessageId:campaignId:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"campaignId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithProactiveMessageId:campaignId:","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails":{"role":"symbol","navigatorTitle":[{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails","abstract":[{"type":"text","text":"Details of a proactive message that was displayed."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","kind":"symbol","type":"topic","title":"ProactiveMessageDisplayedDetails"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithProactiveMessageId:campaignId:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithProactiveMessageId:campaignId:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithProactiveMessageId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"proactiveMessageId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"campaignId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"campaignId","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithProactiveMessageId:campaignId:","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1init(proactiveMessageId:campaignId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithProactiveMessageId:campaignId:"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1init(proactiveMessageId:campaignId:)\/fragments"},{"op":"replace","value":"ZDKProactiveMessageDisplayedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/title"},{"op":"replace","value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/fragments"},{"op":"replace","value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/navigatorTitle"}]}]}