{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/proactiveMessageId","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"proactiveMessageId"}],"title":"proactiveMessageId","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails(py)proactiveMessageId","symbolKind":"property"},"abstract":[{"text":"The ID of the proactive message that was displayed","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/proactivemessageid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/proactivemessageid"]}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails/proactiveMessageId":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/proactiveMessageId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"proactiveMessageId"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The ID of the proactive message that was displayed"}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/proactivemessageid","title":"proactiveMessageId"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails":{"role":"symbol","navigatorTitle":[{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails","abstract":[{"type":"text","text":"Details of a proactive message that was displayed."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","kind":"symbol","type":"topic","title":"ProactiveMessageDisplayedDetails"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"proactiveMessageId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"proactiveMessageId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"proactiveMessageId"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1proactiveMessageId\/title","value":"proactiveMessageId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1proactiveMessageId\/fragments","value":[{"text":"proactiveMessageId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/title","value":"ZDKProactiveMessageDisplayedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}]}]}]}