{"metadata":{"title":"messageReceivedTimestamp","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReceivedTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails(py)messageReceivedTimestamp","navigatorTitle":[{"text":"messageReceivedTimestamp","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageReceivedTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails\/messagereceivedtimestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails\/messagereceivedtimestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The timestamp when the message was received (Unix timestamp as Double)","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/messageReceivedTimestamp","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"abstract":[{"type":"text","text":"Details of a notification that was displayed."}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","navigatorTitle":[{"kind":"identifier","text":"NotificationDisplayedDetails"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","type":"topic","title":"NotificationDisplayedDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationDisplayedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/messageReceivedTimestamp":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageReceivedTimestamp"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/messagereceivedtimestamp","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/messageReceivedTimestamp","title":"messageReceivedTimestamp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReceivedTimestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"The timestamp when the message was received (Unix timestamp as Double)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"messageReceivedTimestamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageReceivedTimestamp"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"messageReceivedTimestamp","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title","value":"ZDKNotificationDisplayedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1messageReceivedTimestamp\/title","value":"messageReceivedTimestamp","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1messageReceivedTimestamp\/fragments","value":[{"text":"messageReceivedTimestamp","kind":"identifier"}],"op":"replace"}]}]}