{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/_onversationunreadcountchanged(id:timestamp:data:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","title":"ZendeskEvent.сonversationUnreadCountChanged(id:timestamp:data:)","externalID":"s:10ZendeskSDK0A5EventO0033onversationUnreadCountChanged_zsxyAC10Foundation4UUIDV_AE4DateVAA29ConversationUnreadCountChangeCtcACmF","modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"сonversationUnreadCountChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Invoked when the number of unread messages has changed"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/_onversationUnreadCountChanged(id:timestamp:data:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"сonversationUnreadCountChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationUnreadCountChange","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the event."}]}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp of the event."}]}],"name":"timestamp"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"total unread messages,"},{"type":"text","text":" "},{"type":"text","text":"conversationId - The unique identifier of the latest updated top active conversation,"},{"type":"text","text":" "},{"type":"text","text":"unreadCountInConversation - the number of unread messages in the latest updated top active conversation."}]}],"name":"including"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"title":"ConversationUnreadCountChange","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationunreadcountchange","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/_onversationUnreadCountChanged(id:timestamp:data:)":{"url":"\/documentation\/zendesksdk\/zendeskevent\/_onversationunreadcountchanged(id:timestamp:data:)","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/_onversationUnreadCountChanged(id:timestamp:data:)","abstract":[{"text":"Invoked when the number of unread messages has changed","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"сonversationUnreadCountChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged","kind":"typeIdentifier","text":"ConversationUnreadCountChange"},{"kind":"text","text":")"}],"title":"ZendeskEvent.сonversationUnreadCountChanged(id:timestamp:data:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title","op":"replace","value":"ZDKConversationUnreadCountChanged"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}]}]}]}