{"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationWithAgentRequested"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationWithAgentRequestedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"},{"kind":"text","text":")"}],"symbolKind":"case","title":"ZendeskEvent.conversationWithAgentRequested(id:timestamp:data:)","externalID":"s:10ZendeskSDK0A5EventO30conversationWithAgentRequestedyAC10Foundation4UUIDV_AE4DateVAA012ConversationefG7DetailsCtcACmF","role":"symbol","modules":[{"name":"ZendeskSDK"}]},"abstract":[{"text":"Invoked when a user starts waiting for an agent to join the conversation.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationWithAgentRequested(id:timestamp:data:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/conversationwithagentrequested(id:timestamp:data:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationWithAgentRequested","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationWithAgentRequestedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The unique identifier of the event (UUID).","type":"text"}],"type":"paragraph"}],"name":"id"},{"content":[{"inlineContent":[{"type":"text","text":"The timestamp when the event is fired."}],"type":"paragraph"}],"name":"timestamp"},{"content":[{"inlineContent":[{"type":"text","text":"Details including:"}],"type":"paragraph"}],"name":"data"}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"kind":"symbol","title":"ConversationWithAgentRequestedDetails","abstract":[{"text":"Details of a conversation where an agent was requested.","type":"text"}],"url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/conversationWithAgentRequested(id:timestamp:data:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Invoked when a user starts waiting for an agent to join the conversation.","type":"text"}],"title":"ZendeskEvent.conversationWithAgentRequested(id:timestamp:data:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationWithAgentRequested"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationWithAgentRequestedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails"},{"kind":"text","text":")"}],"url":"\/documentation\/zendesksdk\/zendeskevent\/conversationwithagentrequested(id:timestamp:data:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationWithAgentRequested(id:timestamp:data:)"}},"variantOverrides":[{"patch":[{"value":"ConversationWithAgentRequestedDetails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/title"},{"value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/fragments"},{"value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}