{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/newConversationButtonClicked(id:timestamp:data:)"},"metadata":{"externalID":"s:10ZendeskSDK0A5EventO28newConversationButtonClickedyAC10Foundation4UUIDV_AE4DateVAA03NewefG7DetailsCtcACmF","modules":[{"name":"ZendeskSDK"}],"title":"ZendeskEvent.newConversationButtonClicked(id:timestamp:data:)","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newConversationButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","text":"NewConversationButtonClickedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"abstract":[{"text":"Invoked when the new conversation button is clicked by the end-user.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/newconversationbuttonclicked(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","text":"NewConversationButtonClickedDetails"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the event (UUID).","type":"text"}]}]},{"name":"timestamp","content":[{"inlineContent":[{"text":"The timestamp when the button was clicked.","type":"text"}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details including:"},{"type":"text","text":" "},{"type":"text","text":"newConversationSource - The source from which the new conversation button was clicked (NewConversationSource)."}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/newConversationButtonClicked(id:timestamp:data:)":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newConversationButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails"},{"text":")","kind":"text"}],"title":"ZendeskEvent.newConversationButtonClicked(id:timestamp:data:)","url":"\/documentation\/zendesksdk\/zendeskevent\/newconversationbuttonclicked(id:timestamp:data:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/newConversationButtonClicked(id:timestamp:data:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Invoked when the new conversation button is clicked by the end-user."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","kind":"symbol","abstract":[{"text":"Details related to the event when the new conversation button is clicked.","type":"text"}],"url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails","type":"topic","navigatorTitle":[{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"title":"NewConversationButtonClickedDetails"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKNewConversationButtonClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/title"},{"op":"replace","value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}