{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/notificationDisplayed(id:timestamp:data:)"},"metadata":{"symbolKind":"case","role":"symbol","title":"ZendeskEvent.notificationDisplayed(id:timestamp:data:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails","text":"NotificationDisplayedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK0A5EventO21notificationDisplayedyAC10Foundation4UUIDV_AE4DateVAA012NotificationE7DetailsCtcACmF"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"id","content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the event (UUID)."}],"type":"paragraph"}]},{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp when the message was received that triggered the notification."}]}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"Details of the notification displayed including:","type":"text"},{"text":" ","type":"text"},{"text":"conversationId - The ID of the conversation associated with the notification (String),","type":"text"},{"text":" ","type":"text"},{"text":"messageReceivedTimestamp - The timestamp when the message was received (Double).","type":"text"}]}]}]}],"abstract":[{"text":"Invoked when a push notification has been displayed to the end-user.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/notificationdisplayed(id:timestamp:data:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","title":"NotificationDisplayedDetails","navigatorTitle":[{"text":"NotificationDisplayedDetails","kind":"identifier"}],"type":"topic","abstract":[{"text":"Details of a notification that was displayed.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/notificationDisplayed(id:timestamp:data:)":{"abstract":[{"text":"Invoked when a push notification has been displayed to the end-user.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdk\/zendeskevent\/notificationdisplayed(id:timestamp:data:)","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/notificationDisplayed(id:timestamp:data:)","title":"ZendeskEvent.notificationDisplayed(id:timestamp:data:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title","value":"ZDKNotificationDisplayedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKNotificationDisplayedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}