{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/postbackButtonClicked(id:timestamp:data:)"},"metadata":{"externalID":"s:10ZendeskSDK0A5EventO21postbackButtonClickedyAC10Foundation4UUIDV_AE4DateVAA08PostbackeF7DetailsCtcACmF","role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postbackButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","text":"PostbackButtonClickedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ZendeskEvent.postbackButtonClicked(id:timestamp:data:)","symbolKind":"case"},"abstract":[{"type":"text","text":"Invoked when a postback button has been clicked by the end-user."}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/postbackbuttonclicked(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postbackButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","text":"PostbackButtonClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the event (UUID)."}]}],"name":"id"},{"content":[{"inlineContent":[{"type":"text","text":"The timestamp when the event is fired."}],"type":"paragraph"}],"name":"timestamp"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details of the postback button clicked including:"},{"type":"text","text":" "},{"type":"text","text":"actionName - The postback button action name (String),"},{"type":"text","text":" "},{"type":"text","text":"conversationId - The unique identifier of the conversation (String)."}]}],"name":"data"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/postbackButtonClicked(id:timestamp:data:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/postbackButtonClicked(id:timestamp:data:)","url":"\/documentation\/zendesksdk\/zendeskevent\/postbackbuttonclicked(id:timestamp:data:)","title":"ZendeskEvent.postbackButtonClicked(id:timestamp:data:)","abstract":[{"type":"text","text":"Invoked when a postback button has been clicked by the end-user."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postbackButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","text":"PostbackButtonClickedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"title":"PostbackButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","abstract":[{"text":"Details of a postback button that was clicked by the end user.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","value":"ZDKPostbackButtonClickedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}]}]}]}