{"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageDisplayed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails"},{"kind":"text","text":")"}],"title":"ZendeskEvent.proactiveMessageDisplayed(id:timestamp:data:)","externalID":"s:10ZendeskSDK0A5EventO25proactiveMessageDisplayedyAC10Foundation4UUIDV_AE4DateVAA09ProactiveeF7DetailsCtcACmF","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ZendeskSDK"}]},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/proactivemessagedisplayed(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Invoked when a proactive message has been displayed to the end-user."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the event (UUID)."}]}]},{"name":"timestamp","content":[{"inlineContent":[{"type":"text","text":"The timestamp when the event is fired."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details of the proactive message displayed including:"},{"type":"text","text":" "},{"type":"text","text":"proactiveMessageId - The ID of the proactive message (String),"},{"type":"text","text":" "},{"type":"text","text":"campaignId - The ID of the campaign for the proactive message (String)."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/proactiveMessageDisplayed(id:timestamp:data:)"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails":{"kind":"symbol","abstract":[{"text":"Details of a proactive message that was displayed.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageDisplayedDetails"}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails","navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageDisplayedDetails"}],"type":"topic","role":"symbol","title":"ProactiveMessageDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/proactiveMessageDisplayed(id:timestamp:data:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/proactiveMessageDisplayed(id:timestamp:data:)","title":"ZendeskEvent.proactiveMessageDisplayed(id:timestamp:data:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Invoked when a proactive message has been displayed to the end-user."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageDisplayed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier","text":"ProactiveMessageDisplayedDetails"},{"kind":"text","text":")"}],"url":"\/documentation\/zendesksdk\/zendeskevent\/proactivemessagedisplayed(id:timestamp:data:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"title":"ZendeskEvent","navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/title","value":"ZDKProactiveMessageDisplayedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/fragments","value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayedDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}