{"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"metadata":{"role":"collection","title":"ZendeskSDK","externalID":"ZendeskSDK","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"ZendeskSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk"]}],"topicSections":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/DispatchEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationOpened","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"],"anchor":"Classes"},{"title":"Protocols","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory"],"anchor":"Protocols"},{"title":"Structures","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ColorTheme"],"anchor":"Structures"},{"title":"Variables","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionNumber","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionString"],"anchor":"Variables"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/InitializationPhase","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole"],"anchor":"Enumerations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"type":"topic","url":"\/documentation\/zendesksdk\/zendeskmessage","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","abstract":[],"kind":"symbol","title":"ZendeskMessage","role":"symbol","navigatorTitle":[{"text":"ZendeskMessage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}],"url":"\/documentation\/zendesksdk\/messagingfactory","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"kind":"symbol","abstract":[],"title":"MessagingFactory","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"title":"ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagesShown","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkmessagesshown","kind":"symbol","title":"ZDKMessagesShown","navigatorTitle":[{"text":"ZDKMessagesShown","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole":{"kind":"symbol","abstract":[],"title":"ZendeskRole","url":"\/documentation\/zendesksdk\/zendeskrole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskRole"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskRole"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"type":"topic","title":"MessagingDelegate","url":"\/documentation\/zendesksdk\/messagingdelegate","abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingDelegate"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","type":"topic","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ColorTheme":{"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/colortheme","role":"symbol","navigatorTitle":[{"text":"ColorTheme","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ColorTheme","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorTheme","kind":"identifier"}],"abstract":[],"title":"ColorTheme"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskVersionNumber":{"type":"topic","title":"ZendeskVersionNumber","url":"\/documentation\/zendesksdk\/zendeskversionnumber","abstract":[{"text":"Project version number for Zendesk.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZendeskVersionNumber"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionNumber"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","title":"Zendesk","url":"\/documentation\/zendesksdk\/zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIFactory":{"title":"MessagingSwiftUIFactory","navigatorTitle":[{"kind":"identifier","text":"MessagingSwiftUIFactory"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSwiftUIFactory"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuifactory"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSettings","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MessagingSettings","kind":"identifier"}],"title":"MessagingSettings","url":"\/documentation\/zendesksdk\/messagingsettings","kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"type":"topic","abstract":[{"text":"The set of parameters to be provided to Messaging(SwiftUI)Factory ","type":"text"},{"code":"createMessaging","type":"codeVoice"},{"text":" to create an instance of ","type":"text"},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","title":"MessagingFactoryParameters","role":"symbol","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactoryParameters"}],"navigatorTitle":[{"kind":"identifier","text":"MessagingFactoryParameters"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/DispatchEvent":{"role":"symbol","kind":"symbol","title":"DispatchEvent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/DispatchEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DispatchEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/dispatchevent","type":"topic","abstract":[{"text":"A wrapper class for a block that takes ","type":"text"},{"type":"codeVoice","code":"ZendeskEvent"},{"text":" type and returns ","type":"text"},{"type":"codeVoice","code":"Void"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DispatchEvent","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":".","type":"text"}],"title":"URLSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/urlsource","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationUnreadCountChange"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationUnreadCountChange"}],"kind":"symbol","type":"topic","role":"symbol","title":"ConversationUnreadCountChange","url":"\/documentation\/zendesksdk\/conversationunreadcountchange"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate":{"navigatorTitle":[{"text":"MessagingSwiftUIDelegate","kind":"identifier"}],"role":"symbol","title":"MessagingSwiftUIDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUIDelegate","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingswiftuidelegate","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"role":"symbol","type":"topic","title":"ZendeskUser","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskuser","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PageView":{"navigatorTitle":[{"kind":"identifier","text":"PageView"}],"kind":"symbol","title":"PageView","role":"symbol","url":"\/documentation\/zendesksdk\/pageview","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageView"}],"type":"topic","abstract":[{"type":"text","text":"This object is used to provide session-based data to capture contextual information about an end user. This data is viewable inside"},{"type":"text","text":" "},{"type":"text","text":"Agent Workspace."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted":{"type":"topic","title":"ZDKConversationStarted","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationstarted","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationStarted"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationStarted"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"url":"\/documentation\/zendesksdk\/messaging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"type":"topic","abstract":[],"title":"Messaging","role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/InitializationPhase":{"kind":"symbol","title":"InitializationPhase","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InitializationPhase","kind":"identifier"}],"navigatorTitle":[{"text":"InitializationPhase","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/zendesksdk\/initializationphase","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/InitializationPhase"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"abstract":[{"text":"A representation of the current connection status of the SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"title":"ZendeskConnectionStatus","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationOpened":{"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationOpened"}],"url":"\/documentation\/zendesksdk\/zdkconversationopened","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationOpened","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationOpened"}],"title":"ZDKConversationOpened","kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"navigatorTitle":[{"text":"MessagingSwiftUI","kind":"identifier"}],"role":"symbol","type":"topic","title":"MessagingSwiftUI","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUI","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingswiftui","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskVersionString":{"kind":"symbol","title":"ZendeskVersionString","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"ZendeskVersionString","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version string for Zendesk."}],"type":"topic","url":"\/documentation\/zendesksdk\/zendeskversionstring","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionString"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/DispatchEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PageView","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationOpened","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"],"title":"Classes","anchor":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory"],"title":"Protocols","anchor":"Protocols"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionNumber","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionString"],"title":"Variables","anchor":"Variables"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole"],"title":"Enumerations","anchor":"Enumerations"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title","value":"ZDKZendeskMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle","value":[{"text":"ZDKZendeskMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"kind":"identifier","text":"MessagingFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/navigatorTitle","value":[{"kind":"identifier","text":"MessagingFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/title","value":"ZDKMessagesShown","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/fragments","value":[{"kind":"identifier","text":"ZDKMessagesShown"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessagesShown"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/title","value":"ZDKZendeskRole","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/fragments","value":[{"text":"ZDKZendeskRole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/navigatorTitle","value":[{"text":"ZDKZendeskRole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title","value":"ZDKMessagingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments","value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/navigatorTitle","value":[{"text":"ZDKMessagingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionNumber\/title","value":"ZendeskVersionNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionNumber\/fragments","value":[{"text":"ZendeskVersionNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/title","value":"ZDKMessagingSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/navigatorTitle","value":[{"text":"ZDKMessagingSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","value":"ZDKMessagingFactoryParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingFactoryParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/navigatorTitle","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/title","value":"ZDKDispatchEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/fragments","value":[{"text":"ZDKDispatchEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1DispatchEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKDispatchEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title","value":"ZDKConversationUnreadCountChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title","value":"ZDKZendeskUser","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/title","value":"ZDKPageView","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/fragments","value":[{"text":"ZDKPageView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PageView\/navigatorTitle","value":[{"text":"ZDKPageView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/title","value":"ZDKConversationStarted","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/fragments","value":[{"kind":"identifier","text":"ZDKConversationStarted"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/navigatorTitle","value":[{"text":"ZDKConversationStarted","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessaging"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","value":"ZDKZendeskConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationOpened\/title","value":"ZDKConversationOpened","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationOpened\/fragments","value":[{"text":"ZDKConversationOpened","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationOpened\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationOpened"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionString\/title","value":"ZendeskVersionString","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionString\/fragments","value":[{"kind":"identifier","text":"ZendeskVersionString"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}