{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/log","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"s:16ZendeskSDKLogger8LoggablePAAE3logAA3Log_pvp::SYNTHESIZED::c:@M@ZendeskSDK@objc(cs)Zendesk","modules":[{"name":"ZendeskSDK","relatedModules":["ZendeskSDKLogger"]}],"roleHeading":"Instance Property","extendedModule":"ZendeskSDKLogger","title":"log","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:16ZendeskSDKLogger3LogP","kind":"typeIdentifier","text":"Log"}],"role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Loggable.log"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:16ZendeskSDKLogger3LogP","text":"Log","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/Loggable-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/log"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/log":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Log","kind":"typeIdentifier","preciseIdentifier":"s:16ZendeskSDKLogger3LogP"}],"title":"log","url":"\/documentation\/zendesksdk\/zendesk\/log","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/log","kind":"symbol","type":"topic","role":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","type":"topic","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/Loggable-Implementations":{"role":"collectionGroup","url":"\/documentation\/zendesksdk\/zendesk\/loggable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/Loggable-Implementations","title":"Loggable Implementations","abstract":[],"kind":"article"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","type":"topic","abstract":[{"text":"The entry point to execute SDK actions. To obtain an instance use ","type":"text"},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"title":"Zendesk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendesk","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}