{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"totalUnreadMessagesCount"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalUnreadMessagesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","role":"symbol","title":"totalUnreadMessagesCount","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged(py)totalUnreadMessagesCount","modules":[{"name":"ZendeskSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/totalUnreadMessagesCount"},"variants":[{"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange\/totalunreadmessagescount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange\/totalunreadmessagescount"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalUnreadMessagesCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/totalUnreadMessagesCount":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/totalUnreadMessagesCount","kind":"symbol","role":"symbol","title":"totalUnreadMessagesCount","abstract":[],"navigatorTitle":[{"text":"totalUnreadMessagesCount","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/totalunreadmessagescount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalUnreadMessagesCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdk\/conversationunreadcountchange","navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","title":"ConversationUnreadCountChange","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"totalUnreadMessagesCount","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"totalUnreadMessagesCount","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalUnreadMessagesCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"totalUnreadMessagesCount","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1totalUnreadMessagesCount\/title","op":"replace"},{"value":[{"text":"totalUnreadMessagesCount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1totalUnreadMessagesCount\/fragments","op":"replace"},{"op":"replace","value":"ZDKConversationUnreadCountChanged","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments"},{"op":"replace","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle"}]}]}