{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableInternalAnalytics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"enableInternalAnalytics(enabled:)","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(im)enableInternalAnalyticsWithEnabled:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableInternalAnalytics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"enableInternalAnalyticsWithEnabled:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/messaging\/enableinternalanalytics(enabled:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/messaging\/enableinternalanalytics(enabled:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/enableInternalAnalytics(enabled:)"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/enableInternalAnalytics(enabled:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/enableInternalAnalytics(enabled:)","title":"enableInternalAnalytics(enabled:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableInternalAnalytics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"enableInternalAnalyticsWithEnabled:","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messaging\/enableinternalanalytics(enabled:)","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messaging","title":"Messaging","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"enableInternalAnalyticsWithEnabled:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableInternalAnalyticsWithEnabled:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"enableInternalAnalyticsWithEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1enableInternalAnalytics(enabled:)\/title","op":"replace","value":"enableInternalAnalyticsWithEnabled:"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1enableInternalAnalytics(enabled:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableInternalAnalyticsWithEnabled:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace","value":"ZDKMessaging"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","op":"replace","value":[{"text":"ZDKMessaging","kind":"identifier"}]}]}]}