{"abstract":[{"type":"text","text":"Retrieve a view controller based on the specified messaging screen configuration."}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/messaging\/messagingviewcontroller(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"s:10ZendeskSDK9MessagingC23messagingViewControllerySo06UIViewF0CAA0C6ScreenOF","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK15MessagingScreenO","text":"MessagingScreen"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"role":"symbol","title":"messagingViewController(_:)","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messagingScreen","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MessagingScreen","preciseIdentifier":"s:10ZendeskSDK15MessagingScreenO","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingScreen"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The messaging screen configuration that determines which view to show:","type":"text"}]}],"name":"messagingScreen"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" instance configured according to the messaging screen","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Use your preferred presentation style (push, modal) to present the view.","type":"text"},{"text":" ","type":"text"},{"text":"You must embed the view controller in a UINavigationController if presenting modally.","type":"text"}]}]}],"kind":"content"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"url":"\/documentation\/zendesksdk\/messaging","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"role":"symbol","title":"Messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/messagingViewController(_:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController(_:)","url":"\/documentation\/zendesksdk\/messaging\/messagingviewcontroller(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessagingScreen","preciseIdentifier":"s:10ZendeskSDK15MessagingScreenO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Retrieve a view controller based on the specified messaging screen configuration.","type":"text"}],"title":"messagingViewController(_:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingScreen":{"navigatorTitle":[{"kind":"identifier","text":"MessagingScreen"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingScreen"}],"title":"MessagingScreen","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingScreen","url":"\/documentation\/zendesksdk\/messagingscreen","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKMessaging","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","op":"replace"},{"value":[{"text":"ZDKMessaging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","op":"replace"}]}]}