{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"  instance"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"Use your preferred presentation style (push, modal) to present the view."},{"type":"text","text":" "},{"type":"text","text":"You must embed the view controller in a UINavigationController if presenting modally."}],"type":"paragraph"}]},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If a user exists, their ‘default’ conversation is displayed."},{"type":"text","text":" "},{"type":"text","text":"If no user exists, user and conversation are created."}]}]}]}],"abstract":[{"type":"text","text":"Retrieve a view controller that either displays a conversation or a list of conversations, depending on business logic."}],"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"title":"messagingViewController()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messagingViewController"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(im)messagingViewController"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdk\/messaging\/messagingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/messaging\/messagingviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messaging","title":"Messaging","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/messagingViewController()":{"kind":"symbol","title":"messagingViewController()","abstract":[{"text":"Retrieve a view controller that either displays a conversation or a list of conversations, depending on business logic.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/messagingViewController()","navigatorTitle":[{"kind":"identifier","text":"messagingViewController"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/messaging\/messagingviewcontroller()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"messagingViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messagingViewController","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"messagingViewController"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":"  instance","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace","value":"ZDKMessaging"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessaging"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1messagingViewController()\/title","value":"messagingViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1messagingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagingViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}