{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkmessagesshown\/messages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkmessagesshown\/messages"]}],"metadata":{"symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"messages"}],"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessagesShown(py)messages","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messages"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage","kind":"typeIdentifier","text":"ZendeskMessage"},{"kind":"text","text":"]"}],"title":"messages"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/messages"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","text":"ZendeskMessage","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown":{"title":"ZDKMessagesShown","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkmessagesshown","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagesShown","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKMessagesShown","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"navigatorTitle":[{"kind":"identifier","text":"ZendeskMessage"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskMessage"}],"title":"ZendeskMessage","url":"\/documentation\/zendesksdk\/zendeskmessage","kind":"symbol","role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/messages":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZendeskMessage","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"messages"}],"url":"\/documentation\/zendesksdk\/zdkmessagesshown\/messages","title":"messages","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/messages","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"messages","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messages"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<ZDKZendeskMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"messages","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/title","value":"ZDKMessagesShown","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/fragments","value":[{"text":"ZDKMessagesShown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessagesShown"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title","value":"ZDKZendeskMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments","value":[{"text":"ZDKZendeskMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1messages\/title","value":"messages","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1messages\/fragments","value":[{"text":"messages","kind":"identifier"}],"op":"replace"}]}]}