{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loginUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"jwt","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","text":"ZendeskUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"jwt"},{"type":"text","text":" belonging to the user."}]}],"name":"jwt"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block that takes a "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" enum type. In the case of a success, a "},{"type":"codeVoice","code":"ZendeskUser"},{"text":" will be returned,","type":"text"},{"text":" ","type":"text"},{"text":"in the case of a failure an ","type":"text"},{"type":"codeVoice","code":"Error"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"metadata":{"symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loginUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"ZendeskUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","title":"loginUser(with:completionHandler:)","externalID":"s:10ZendeskSDK0A0C9loginUser4with17completionHandlerySS_ys6ResultOyAA0aD0Cs5Error_pGcSgtF","extendedModule":"ZendeskSDK","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Authenticate a user."}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-63scj"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-63scj","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk","role":"collection","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"title":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","title":"ZendeskUser","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZendeskUser"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/loginUser(with:completionHandler:)-63scj":{"abstract":[{"type":"text","text":"Authenticate a user."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loginUser"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"ZendeskUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-63scj","kind":"symbol","role":"symbol","title":"loginUser(with:completionHandler:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-63scj","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Zendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title","op":"replace","value":"ZDKZendeskUser"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments","value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"op":"replace"}]}]}