{"abstract":[{"type":"text","text":"Authenticate a user."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-29ava"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-29ava"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loginUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","kind":"typeIdentifier","text":"ZendeskUser"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"loginUserWith:completionHandler:","kind":"identifier"}],"externalID":"c:@CM@ZendeskSDK@objc(cs)Zendesk(im)loginUserWith:completionHandler:","platforms":[],"title":"loginUser(with:completionHandler:)","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loginUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"jwt","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"text":"ZendeskUser","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"jwt"},{"text":" belonging to the user.","type":"text"}],"type":"paragraph"}],"name":"jwt"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block that takes an optional "},{"type":"codeVoice","code":"ZendeskUser"},{"text":" which will be non-nil in the case of a success,","type":"text"},{"text":" ","type":"text"},{"text":"and an optional ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" which will be non-nil in the case of a failure.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-29ava","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","title":"ZendeskUser","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZendeskUser"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"title":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/loginUser(with:completionHandler:)-29ava":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loginUser"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"text":"ZendeskUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","abstract":[{"text":"Authenticate a user.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/loginUser(with:completionHandler:)-29ava","title":"loginUser(with:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/loginuser(with:completionhandler:)-29ava","navigatorTitle":[{"text":"loginUserWith:completionHandler:","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk","role":"collection","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"loginUserWith:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loginUserWith:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loginUserWith:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"jwt"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ZendeskSDK@objc(cs)ZDKZendeskUser#*$objc(cs)NSError)","text":"void (^)(ZDKZendeskUser *, NSError *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ZDKZendeskUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskUser"}]},{"value":"Zendesk","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}]},{"value":"loginUserWith:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1loginUser(with:completionHandler:)-29ava\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1loginUser(with:completionHandler:)-29ava\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loginUserWith:completionHandler:","kind":"identifier"}],"op":"replace"}]}]}