{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addEventObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"observer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ZDKZendeskEvent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskEvent"},{"kind":"text","text":", "},{"text":"AnyObject","kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The object in which events will be received."}],"type":"paragraph"}],"name":"observer"},{"content":[{"inlineContent":[{"type":"text","text":"A block that receives a "},{"type":"codeVoice","code":"ZDKZendeskEvent"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-7l829"},"abstract":[{"text":"Add an event observer to observe events emitted from ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"title":"addEventObserver(_:_:)","platforms":[],"externalID":"c:@CM@ZendeskSDK@objc(cs)Zendesk(im)addEventObserver::","modules":[{"name":"ZendeskSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"addEventObserver::","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addEventObserver"},{"kind":"text","text":"("},{"text":"AnyObject","kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta"},{"text":", ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskEvent","text":"ZDKZendeskEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"extendedModule":"ZendeskSDK"},"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/addeventobserver(_:_:)-7l829"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendesk\/addeventobserver(_:_:)-7l829"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/addEventObserver(_:_:)-7l829":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addEventObserver"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"text":", ((","kind":"text"},{"text":"ZDKZendeskEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/addEventObserver(_:_:)-7l829","kind":"symbol","role":"symbol","title":"addEventObserver(_:_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addEventObserver::"}],"abstract":[{"type":"text","text":"Add an event observer to observe events emitted from "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdk\/zendesk\/addeventobserver(_:_:)-7l829"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"title":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdk\/zendesk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","title":"ZDKZendeskEvent","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/zendesksdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"addEventObserver::","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addEventObserver::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"addEventObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":" "},{"text":":","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#$@M@ZendeskSDK@E@ZDKZendeskEvent#*Qo)","text":"void (^)(enum ZDKZendeskEvent, id)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"addEventObserver::","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1addEventObserver(_:_:)-7l829\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1addEventObserver(_:_:)-7l829\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"addEventObserver::","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]}]}]}