{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/user"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskrole\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskrole\/user"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The message is authored by a user."}],"metadata":{"symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskRoleUser"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"title":"ZendeskRole.user","roleHeading":"Case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskRole@ZDKZendeskRoleUser","role":"symbol"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/user":{"url":"\/documentation\/zendesksdk\/zendeskrole\/user","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/user","role":"symbol","type":"topic","title":"ZendeskRole.user","kind":"symbol","abstract":[{"text":"The message is authored by a user.","type":"text"}],"navigatorTitle":[{"text":"ZDKZendeskRoleUser","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole":{"navigatorTitle":[{"text":"ZendeskRole","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdk\/zendeskrole","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskRole","kind":"identifier"}],"title":"ZendeskRole","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"title":"ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskRoleUser","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskRoleUser"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKZendeskRoleUser","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKZendeskRoleUser","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1user\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskRoleUser"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1user\/fragments"},{"op":"replace","value":"ZDKZendeskRole","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}