{"abstract":[{"type":"text","text":"Invoked when the conversation is started on the device."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationStarted","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationStarted","navigatorTitle":[{"text":"ZDKZendeskEventConversationStarted","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationStarted","kind":"identifier"}],"role":"symbol","title":"ZDKZendeskEvent.conversationStarted"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationStarted","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationStarted":{"title":"ZDKZendeskEvent.conversationStarted","abstract":[{"text":"Invoked when the conversation is started on the device.","type":"text"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationstarted","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationStarted","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConversationStarted"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationStarted"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","title":"ZDKZendeskEvent","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEventConversationStarted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskEventConversationStarted","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventConversationStarted"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationStarted\/title","value":"ZDKZendeskEventConversationStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationStarted\/fragments","value":[{"text":"ZDKZendeskEventConversationStarted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}