{"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/notificationdisplayed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/notificationdisplayed"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Invoked when a push notification has been displayed to the end-user.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/notificationDisplayed"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationDisplayed"}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventNotificationDisplayed","navigatorTitle":[{"text":"ZDKZendeskEventNotificationDisplayed","kind":"identifier"}],"role":"symbol","symbolKind":"case","title":"ZDKZendeskEvent.notificationDisplayed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationDisplayed"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case"},"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/notificationDisplayed":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/notificationDisplayed","abstract":[{"type":"text","text":"Invoked when a push notification has been displayed to the end-user."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventNotificationDisplayed"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationDisplayed"}],"type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/notificationdisplayed","role":"symbol","title":"ZDKZendeskEvent.notificationDisplayed"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","title":"ZDKZendeskEvent","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskEventNotificationDisplayed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKZendeskEventNotificationDisplayed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventNotificationDisplayed"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKZendeskEventNotificationDisplayed","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1notificationDisplayed\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskEventNotificationDisplayed"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1notificationDisplayed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}