{"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessageclicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessageclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Invoked when a proactive message has been clicked by the end-user.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageClicked","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/proactiveMessageClicked","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventProactiveMessageClicked","title":"ZDKZendeskEvent.proactiveMessageClicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageClicked"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"ZDKZendeskEventProactiveMessageClicked","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/proactiveMessageClicked":{"type":"topic","title":"ZDKZendeskEvent.proactiveMessageClicked","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventProactiveMessageClicked"}],"abstract":[{"text":"Invoked when a proactive message has been clicked by the end-user.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/proactiveMessageClicked","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessageclicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageClicked"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","title":"ZDKZendeskEvent","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKZendeskEventProactiveMessageClicked"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKZendeskEventProactiveMessageClicked","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKZendeskEventProactiveMessageClicked"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1proactiveMessageClicked\/title","op":"replace","value":"ZDKZendeskEventProactiveMessageClicked"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1proactiveMessageClicked\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventProactiveMessageClicked"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","op":"replace","value":"ZDKZendeskEvent"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}]}]}]}