{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"totalUnreadMessagesCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"unreadCountInConversation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange\/init(totalunreadmessagescount:conversationid:unreadcountinconversation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","role":"symbol","externalID":"s:10ZendeskSDK29ConversationUnreadCountChangeC05totald8MessagesE014conversationId06unreade2InC0ACSi_SSSgSitcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"totalUnreadMessagesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"unreadCountInConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"ZendeskSDK"}],"symbolKind":"init"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"title":"ConversationUnreadCountChange","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationunreadcountchange","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/init(totalunreadmessagescount:conversationid:unreadcountinconversation:)","role":"symbol","title":"init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"totalUnreadMessagesCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"unreadCountInConversation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title","value":"ZDKConversationUnreadCountChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}],"op":"replace"}]}]}