{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"],"kind":"relationships"}],"sections":[],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ZendeskSDK"}],"symbolKind":"enum","title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@AgentMessageSource","navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentMessageSource"}]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentCopilot","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentWorkspace"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/zendesksdk\/agentmessagesource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/agentmessagesource"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/description":{"url":"\/documentation\/zendesksdk\/agentmessagesource\/description","title":"description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/description"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/zendesksdk\/agentmessagesource\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/RawRepresentable-Implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/init(rawValue:)":{"url":"\/documentation\/zendesksdk\/agentmessagesource\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/init(rawValue:)"},"doc://com.zendesk.Zendesk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/agentWorkspace":{"url":"\/documentation\/zendesksdk\/agentmessagesource\/agentworkspace","title":"AgentMessageSource.agentWorkspace","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentWorkspace","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AgentMessageSourceAgentWorkspace","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The agent’s message was generated from the Agent Workspace"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentWorkspace"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/agentCopilot":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentCopilot","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/agentmessagesource\/agentcopilot","abstract":[{"type":"text","text":"The agent’s message was generated from the Agent Copilot tool"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentCopilot","navigatorTitle":[{"text":"AgentMessageSourceAgentCopilot","kind":"identifier"}],"role":"symbol","title":"AgentMessageSource.agentCopilot"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource":{"title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/agentmessagesource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","title":"Equatable Implementations","type":"topic","url":"\/documentation\/zendesksdk\/agentmessagesource\/equatable-implementations","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/Equatable-Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AgentMessageSource","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AgentMessageSource"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AgentMessageSource"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentCopilot","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource\/agentWorkspace"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentMessageSource"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AgentMessageSourceAgentWorkspace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentWorkspace\/title"},{"op":"replace","value":[{"text":"AgentMessageSourceAgentWorkspace","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentWorkspace\/fragments"},{"op":"replace","value":"AgentMessageSourceAgentCopilot","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentCopilot\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AgentMessageSourceAgentCopilot"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource~1agentCopilot\/fragments"},{"op":"replace","value":"AgentMessageSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AgentMessageSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/fragments"},{"op":"replace","value":[{"text":"AgentMessageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}