{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKArticleClickedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"role":"symbol","title":"ArticleClickedDetails","symbolKind":"class","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","navigatorTitle":[{"text":"ArticleClickedDetails","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Class"},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/init(articleId:articleTitle:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleTitle"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"variants":[{"paths":["\/documentation\/zendesksdk\/articleclickeddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/articleclickeddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails/articleId":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"articleId","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleId","navigatorTitle":[{"text":"articleId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier of the article"}],"type":"topic","url":"\/documentation\/zendesksdk\/articleclickeddetails\/articleid"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails/articleTitle":{"title":"articleTitle","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleTitle","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails\/articletitle","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"articleTitle","kind":"identifier"}],"abstract":[{"type":"text","text":"The article title (nullable)"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails/init(articleId:articleTitle:)":{"url":"\/documentation\/zendesksdk\/articleclickeddetails\/init(articleid:articletitle:)","type":"topic","kind":"symbol","title":"init(articleId:articleTitle:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"articleId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"articleTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/init(articleId:articleTitle:)","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails":{"title":"ArticleClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleClickedDetails","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKArticleClickedDetails","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails\/articleTitle"],"anchor":"Instance-Properties","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKArticleClickedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"articleId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"articleId"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleId\/fragments"},{"op":"replace","value":"articleTitle","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleTitle\/title"},{"op":"replace","value":[{"text":"articleTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails~1articleTitle\/fragments"},{"op":"replace","value":"ZDKArticleClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/title"},{"op":"replace","value":[{"text":"ZDKArticleClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}