{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged","symbolKind":"class","navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}],"title":"ConversationUnreadCountChange"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/totalUnreadMessagesCount","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/unreadCountInConversation"],"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationUnreadCountChanged) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/init(totalunreadmessagescount:conversationid:unreadcountinconversation:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"totalUnreadMessagesCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"unreadCountInConversation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"type":"topic","title":"init(totalUnreadMessagesCount:conversationId:unreadCountInConversation:)","kind":"symbol"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/totalUnreadMessagesCount":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/totalUnreadMessagesCount","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/totalunreadmessagescount","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalUnreadMessagesCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","title":"totalUnreadMessagesCount","navigatorTitle":[{"kind":"identifier","text":"totalUnreadMessagesCount"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/unreadCountInConversation":{"role":"symbol","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/unreadcountinconversation","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/unreadCountInConversation","kind":"symbol","navigatorTitle":[{"text":"unreadCountInConversation","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadCountInConversation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","title":"unreadCountInConversation","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/conversationId":{"navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"conversationId","role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/conversationid","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/conversationId","abstract":[],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"type":"topic","role":"symbol","title":"ConversationUnreadCountChange","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","url":"\/documentation\/zendesksdk\/conversationunreadcountchange"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ZDKConversationUnreadCountChanged","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/totalUnreadMessagesCount","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/unreadCountInConversation"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationUnreadCountChanged"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1totalUnreadMessagesCount\/title","value":"totalUnreadMessagesCount","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1totalUnreadMessagesCount\/fragments","value":[{"kind":"identifier","text":"totalUnreadMessagesCount"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1unreadCountInConversation\/title","value":"unreadCountInConversation","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1unreadCountInConversation\/fragments","value":[{"text":"unreadCountInConversation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1conversationId\/title","value":"conversationId","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title","value":"ZDKConversationUnreadCountChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}],"op":"replace"}]}]}