{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/init(conversationId:url:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/url"],"title":"Instance Properties"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"title":"ConversationExtensionOpenedDetails","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/conversationextensionopeneddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationextensionopeneddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails/init(conversationId:url:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/init(conversationId:url:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails\/init(conversationid:url:)","title":"init(conversationId:url:)","kind":"symbol"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails/conversationId":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/conversationId","kind":"symbol","title":"conversationId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails\/conversationid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"conversationId"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails":{"url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"title":"ConversationExtensionOpenedDetails","navigatorTitle":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails/url":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/url","url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails\/url","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"url","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"url","type":"topic"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ConversationExtensionOpenedDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ConversationExtensionOpenedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails\/url"],"title":"Instance Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionOpenedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails~1conversationId\/title","value":"conversationId","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/title","value":"ConversationExtensionOpenedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/fragments","value":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails~1url\/fragments","value":[{"kind":"identifier","text":"url"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}