{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails"},"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationServedByAgentDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationServedByAgentDetails"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationServedByAgentDetails","title":"ConversationServedByAgentDetails","modules":[{"name":"ZendeskSDK"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/zendesksdk\/conversationservedbyagentdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationservedbyagentdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/init(agentDisplayName:agentId:agentMessageSource:conversationId:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentDisplayName","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentMessageSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/conversationId"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationServedByAgentDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationServedByAgentDetails","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/agentDisplayName":{"abstract":[{"text":"The display name of the agent serving the conversation","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentDisplayName","navigatorTitle":[{"text":"agentDisplayName","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/agentdisplayname","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentDisplayName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"agentDisplayName","type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/agentId":{"kind":"symbol","role":"symbol","abstract":[{"text":"Unique identifier string for the agent","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentId","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/agentid","title":"agentId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"agentId"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/agentMessageSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentMessageSource","role":"symbol","navigatorTitle":[{"text":"agentMessageSource","kind":"identifier"}],"title":"agentMessageSource","abstract":[{"text":"Enum indicating the source or tool context of the agent’s message","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/agentmessagesource","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agentMessageSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@AgentMessageSource","text":"AgentMessageSource","kind":"typeIdentifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/init(agentDisplayName:agentId:agentMessageSource:conversationId:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/init(agentDisplayName:agentId:agentMessageSource:conversationId:)","role":"symbol","title":"init(agentDisplayName:agentId:agentMessageSource:conversationId:)","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/init(agentdisplayname:agentid:agentmessagesource:conversationid:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agentDisplayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"agentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"agentMessageSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgentMessageSource","preciseIdentifier":"c:@M@ZendeskSDK@E@AgentMessageSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationServedByAgentDetails"}],"title":"ConversationServedByAgentDetails","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServedByAgentDetails"}]},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/conversationId":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/conversationId","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/conversationid","type":"topic","abstract":[{"text":"Unique identifier for the conversation being served by the agent","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"title":"conversationId","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKConversationServedByAgentDetails","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationServedByAgentDetails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentDisplayName","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/agentMessageSource","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/conversationId"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"agentDisplayName","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentDisplayName\/title","op":"replace"},{"value":[{"text":"agentDisplayName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentDisplayName\/fragments","op":"replace"},{"value":"agentId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"agentId"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentId\/fragments","op":"replace"},{"value":"agentMessageSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentMessageSource\/title","op":"replace"},{"value":[{"text":"agentMessageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1agentMessageSource\/fragments","op":"replace"},{"value":"ZDKConversationServedByAgentDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationServedByAgentDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/fragments","op":"replace"},{"value":[{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/navigatorTitle","op":"replace"},{"value":"conversationId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1conversationId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"conversationId"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails~1conversationId\/fragments","op":"replace"}]}]}