{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"metadata":{"title":"ZDKArticleClicked","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClicked","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleClicked"}],"modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKArticleClicked"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/timestamp"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkarticleclicked"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKArticleClicked","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleClicked"}],"url":"\/documentation\/zendesksdk\/zdkarticleclicked","navigatorTitle":[{"kind":"identifier","text":"ZDKArticleClicked"}],"kind":"symbol","abstract":[],"type":"topic","title":"ZDKArticleClicked","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked/timestamp":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/timestamp","abstract":[],"title":"timestamp","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/zendesksdk\/zdkarticleclicked\/timestamp","kind":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked/data":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/data","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","text":"ArticleClickedDetails","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkarticleclicked\/data","abstract":[],"type":"topic","title":"data","navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKArticleClicked/id":{"title":"id","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/id","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/zendesksdk\/zdkarticleclicked\/id"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKArticleClicked"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKArticleClicked\/timestamp"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleClicked"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/title","op":"replace","value":"ZDKArticleClicked"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/fragments","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked\/navigatorTitle","op":"replace","value":[{"text":"ZDKArticleClicked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1timestamp\/fragments","op":"replace","value":[{"text":"timestamp","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1data\/title","op":"replace","value":"data"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1data\/fragments","op":"replace","value":[{"text":"data","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1id\/title","op":"replace","value":"id"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKArticleClicked~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}