{"sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/timestamp"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionOpened","kind":"identifier"}]}]}],"metadata":{"role":"symbol","title":"ZDKConversationExtensionOpened","symbolKind":"class","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionOpened","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Class","navigatorTitle":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationextensionopened"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationextensionopened"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened/data":{"title":"data","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationextensionopened\/data","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/data","abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkconversationextensionopened","role":"symbol","navigatorTitle":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened","title":"ZDKConversationExtensionOpened"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened/id":{"kind":"symbol","navigatorTitle":[{"text":"id","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/id","url":"\/documentation\/zendesksdk\/zdkconversationextensionopened\/id","title":"id","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened/timestamp":{"title":"timestamp","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationextensionopened\/timestamp","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/timestamp","abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}]},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationExtensionOpened"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationExtensionOpened"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/timestamp"],"anchor":"Instance-Properties","title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionOpened","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1data\/title","op":"replace","value":"data"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1data\/fragments","op":"replace","value":[{"kind":"identifier","text":"data"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/title","op":"replace","value":"ZDKConversationExtensionOpened"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/fragments","op":"replace","value":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1id\/title","op":"replace","value":"id"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1timestamp\/fragments","op":"replace","value":[{"kind":"identifier","text":"timestamp"}]}]}]}