{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayed","role":"symbol","navigatorTitle":[{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","title":"ZDKProactiveMessageDisplayed","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkproactivemessagedisplayed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkproactivemessagedisplayed"]}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/timestamp"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKProactiveMessageDisplayed"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed":{"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"title":"ZDKProactiveMessageDisplayed","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed","url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed","role":"symbol","navigatorTitle":[{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed/timestamp":{"title":"timestamp","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"type":"topic","url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/timestamp","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/timestamp","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"role":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed/id":{"type":"topic","url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/id","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"kind":"symbol","title":"id","abstract":[]},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageDisplayed/data":{"kind":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/zendesksdk\/zdkproactivemessagedisplayed\/data","title":"data","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","kind":"typeIdentifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKProactiveMessageDisplayed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayed"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayed"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageDisplayed\/timestamp"],"generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageDisplayed","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/title","value":"ZDKProactiveMessageDisplayed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1id\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageDisplayed~1data\/fragments","value":[{"kind":"identifier","text":"data"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}