{"metadata":{"title":"ZDKProactiveMessageClicked","roleHeading":"Class","symbolKind":"class","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClicked","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageClicked","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKProactiveMessageClicked"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkproactivemessageclicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkproactivemessageclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/timestamp"],"title":"Instance Properties","anchor":"Instance-Properties"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageClicked","kind":"identifier"}],"title":"ZDKProactiveMessageClicked","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked","url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked","kind":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked/timestamp":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked\/timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/timestamp","abstract":[],"title":"timestamp","role":"symbol","type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked/data":{"navigatorTitle":[{"text":"data","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/data","type":"topic","kind":"symbol","role":"symbol","abstract":[],"title":"data","url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked\/data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKProactiveMessageClicked/id":{"url":"\/documentation\/zendesksdk\/zdkproactivemessageclicked\/id","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/id","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"title":"id","navigatorTitle":[{"text":"id","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKProactiveMessageClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageClicked"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKProactiveMessageClicked\/timestamp"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKProactiveMessageClicked"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/title","value":"ZDKProactiveMessageClicked"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/fragments","value":[{"text":"ZDKProactiveMessageClicked","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKProactiveMessageClicked"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1id\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKProactiveMessageClicked~1id\/fragments","value":[{"text":"id","kind":"identifier"}]}]}]}