{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/init(from:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/init(id:role:timestamp:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/role","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/timestamp"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/isEqual(_:)"],"generated":true}],"metadata":{"title":"ZendeskMessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZendeskMessage"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/Se","doc:\/\/com.zendesk.Zendesk\/SE","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKZendeskMessage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/id":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"id"},{"type":"text","text":" of the message."}],"type":"topic","url":"\/documentation\/zendesksdk\/zendeskmessage\/id","navigatorTitle":[{"kind":"identifier","text":"id"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/id","title":"id","role":"symbol"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.Zendesk/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SE","title":"Swift.Encodable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/role":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The role of the message - whether it is sent from the business or the user."}],"url":"\/documentation\/zendesksdk\/zendeskmessage\/role","title":"role","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/role","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole","kind":"typeIdentifier","text":"ZendeskRole"}],"navigatorTitle":[{"kind":"identifier","text":"role"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/init(id:role:timestamp:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskRole","text":"ZendeskRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithId:role:timestamp:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","title":"init(id:role:timestamp:)","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/init(id:role:timestamp:)","url":"\/documentation\/zendesksdk\/zendeskmessage\/init(id:role:timestamp:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/isEqual(_:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/zendesksdk\/zendeskmessage\/isequal(_:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"role":"symbol","type":"topic","title":"ZendeskMessage","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZendeskMessage","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskmessage"},"doc://com.zendesk.Zendesk/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/Se","title":"Swift.Decodable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/timestamp":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/timestamp","url":"\/documentation\/zendesksdk\/zendeskmessage\/timestamp","role":"symbol","title":"timestamp","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"abstract":[{"text":"The date the message was created at.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/init(from:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/init(from:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","url":"\/documentation\/zendesksdk\/zendeskmessage\/init(from:)"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskMessage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/role","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/timestamp"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/init(id:role:timestamp:)","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskMessage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"id","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1id\/title"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1id\/fragments"},{"value":"role","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1role\/title"},{"value":[{"text":"role","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1role\/fragments"},{"value":"initWithId:role:timestamp:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1init(id:role:timestamp:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:role:timestamp:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1init(id:role:timestamp:)\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1isEqual(_:)\/fragments"},{"value":"ZDKZendeskMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title"},{"value":[{"text":"ZDKZendeskMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments"},{"value":[{"text":"ZDKZendeskMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1timestamp\/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1timestamp\/fragments"}]}]}