{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAgentAssigned","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Invoked when an agent assigned to the conversation.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAgentAssigned"},"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationAgentAssigned"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationAgentAssigned","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConversationAgentAssigned"}],"role":"symbol","title":"ZDKZendeskEvent.conversationAgentAssigned"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationagentassigned"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationagentassigned"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationAgentAssigned":{"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationagentassigned","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAgentAssigned","kind":"identifier"}],"abstract":[{"type":"text","text":"Invoked when an agent assigned to the conversation."}],"navigatorTitle":[{"text":"ZDKZendeskEventConversationAgentAssigned","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAgentAssigned","kind":"symbol","role":"symbol","title":"ZDKZendeskEvent.conversationAgentAssigned"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"type":"topic","kind":"symbol","title":"ZDKZendeskEvent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskEventConversationAgentAssigned","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKZendeskEventConversationAgentAssigned"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventConversationAgentAssigned"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKZendeskEventConversationAgentAssigned","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAgentAssigned\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskEventConversationAgentAssigned"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAgentAssigned\/fragments"},{"value":"ZDKZendeskEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}]}]}