{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensiondisplayed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensiondisplayed"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationExtensionDisplayed","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"sections":[],"metadata":{"title":"ZDKZendeskEvent.conversationExtensionDisplayed","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionDisplayed"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationExtensionDisplayed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationExtensionDisplayed"}]},"abstract":[{"text":"Invoked when a conversation extension content has been displayed to the end-user.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionDisplayed","kind":"identifier"}]}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"title":"ZDKZendeskEvent","kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationExtensionDisplayed":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationExtensionDisplayed","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Invoked when a conversation extension content has been displayed to the end-user."}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensiondisplayed","title":"ZDKZendeskEvent.conversationExtensionDisplayed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionDisplayed","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKZendeskEventConversationExtensionDisplayed","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKZendeskEventConversationExtensionDisplayed","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionDisplayed"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKZendeskEventConversationExtensionDisplayed","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationExtensionDisplayed\/title","value":"ZDKZendeskEventConversationExtensionDisplayed","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationExtensionDisplayed\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionDisplayed"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}