{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationWithAgentRequested"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationwithagentrequested"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationwithagentrequested"]}],"metadata":{"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationWithAgentRequested","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationWithAgentRequested"}],"roleHeading":"Case","title":"ZDKZendeskEvent.conversationWithAgentRequested","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskEventConversationWithAgentRequested","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationWithAgentRequested","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when an agente is requested"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","role":"symbol","title":"ZDKZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationWithAgentRequested":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationWithAgentRequested","kind":"identifier"}],"title":"ZDKZendeskEvent.conversationWithAgentRequested","navigatorTitle":[{"text":"ZDKZendeskEventConversationWithAgentRequested","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationwithagentrequested","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationWithAgentRequested","role":"symbol","abstract":[{"type":"text","text":"Invoked when an agente is requested"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKZendeskEventConversationWithAgentRequested"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKZendeskEventConversationWithAgentRequested","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKZendeskEventConversationWithAgentRequested","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","op":"replace","value":"ZDKZendeskEvent"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationWithAgentRequested\/title","op":"replace","value":"ZDKZendeskEventConversationWithAgentRequested"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationWithAgentRequested\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationWithAgentRequested"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}