{"abstract":[{"text":"Invoked when a push notification has been opened by the end user.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/notificationopened"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/notificationopened"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/notificationOpened","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationOpened"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"metadata":{"title":"ZDKZendeskEvent.notificationOpened","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationOpened","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventNotificationOpened","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskEventNotificationOpened","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/notificationOpened":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/notificationOpened","navigatorTitle":[{"text":"ZDKZendeskEventNotificationOpened","kind":"identifier"}],"abstract":[{"text":"Invoked when a push notification has been opened by the end user.","type":"text"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/notificationopened","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationOpened","kind":"identifier"}],"type":"topic","role":"symbol","title":"ZDKZendeskEvent.notificationOpened"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"type":"topic","kind":"symbol","title":"ZDKZendeskEvent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskEventNotificationOpened","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventNotificationOpened"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKZendeskEventNotificationOpened"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKZendeskEventNotificationOpened","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1notificationOpened\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventNotificationOpened"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1notificationOpened\/fragments"},{"op":"replace","value":"ZDKZendeskEvent","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}