{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postbackButtonClicked"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventPostbackButtonClicked","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"ZDKZendeskEventPostbackButtonClicked","kind":"identifier"}],"title":"ZDKZendeskEvent.postbackButtonClicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postbackButtonClicked"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/postbackButtonClicked"},"abstract":[{"type":"text","text":"Invoked when a postback button has been clicked by the end-user."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/postbackbuttonclicked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/postbackbuttonclicked"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/postbackButtonClicked":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/postbackButtonClicked","title":"ZDKZendeskEvent.postbackButtonClicked","abstract":[{"type":"text","text":"Invoked when a postback button has been clicked by the end-user."}],"navigatorTitle":[{"text":"ZDKZendeskEventPostbackButtonClicked","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/postbackbuttonclicked","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postbackButtonClicked","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"type":"topic","url":"\/documentation\/zendesksdk\/zdkzendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","role":"symbol","title":"ZDKZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKZendeskEventPostbackButtonClicked","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskEventPostbackButtonClicked","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKZendeskEventPostbackButtonClicked"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1postbackButtonClicked\/title","value":"ZDKZendeskEventPostbackButtonClicked","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1postbackButtonClicked\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventPostbackButtonClicked"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}