{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageDisplayed","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"abstract":[{"text":"Invoked when a proactive message has been displayed to the end-user.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessagedisplayed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessagedisplayed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/proactiveMessageDisplayed","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"ZDKZendeskEvent.proactiveMessageDisplayed","roleHeading":"Case","navigatorTitle":[{"text":"ZDKZendeskEventProactiveMessageDisplayed","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventProactiveMessageDisplayed","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageDisplayed","kind":"identifier"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/proactiveMessageDisplayed":{"title":"ZDKZendeskEvent.proactiveMessageDisplayed","navigatorTitle":[{"text":"ZDKZendeskEventProactiveMessageDisplayed","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/proactivemessagedisplayed","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/proactiveMessageDisplayed","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageDisplayed","kind":"identifier"}],"abstract":[{"type":"text","text":"Invoked when a proactive message has been displayed to the end-user."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"type":"topic","kind":"symbol","title":"ZDKZendeskEvent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskEventProactiveMessageDisplayed","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventProactiveMessageDisplayed"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKZendeskEventProactiveMessageDisplayed","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKZendeskEventProactiveMessageDisplayed","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1proactiveMessageDisplayed\/title"},{"value":[{"text":"ZDKZendeskEventProactiveMessageDisplayed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1proactiveMessageDisplayed\/fragments"},{"value":"ZDKZendeskEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}