{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/invalidate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendesk\/invalidate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invalidates the current instance of "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"After calling this method you will have to call "},{"type":"codeVoice","code":"Zendesk.initialize()"},{"type":"text","text":" again if you would like to use "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"title":"invalidate()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ZendeskSDK@objc(cs)Zendesk(cm)invalidate","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"invalidate"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","title":"ZendeskSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"role":"symbol","title":"Zendesk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"url":"\/documentation\/zendesksdk\/zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/invalidate()":{"role":"symbol","title":"invalidate()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates the current instance of "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"After calling this method you will have to call "},{"type":"codeVoice","code":"Zendesk.initialize()"},{"type":"text","text":" again if you would like to use "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/invalidate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidate"}],"url":"\/documentation\/zendesksdk\/zendesk\/invalidate()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"invalidate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"invalidate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate()\/title","value":"invalidate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1invalidate()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"invalidate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}