{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked\/data","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked"]]},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","text":"NewConversationButtonClickedDetails"}],"roleHeading":"Instance Property","title":"data","externalID":"c:@M@ZendeskSDK@objc(cs)NewConversationButtonClicked(py)data","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"data"}],"modules":[{"name":"ZendeskSDK"}]},"variants":[{"paths":["\/documentation\/zendesksdk\/newconversationbuttonclicked\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/newconversationbuttonclicked\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","text":"NewConversationButtonClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails":{"type":"topic","title":"NewConversationButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","abstract":[{"text":"Details related to the event when the new conversation button is clicked.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClicked":{"type":"topic","url":"\/documentation\/zendesksdk\/newconversationbuttonclicked","title":"NewConversationButtonClicked","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClicked","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked","navigatorTitle":[{"text":"NewConversationButtonClicked","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClicked/data":{"type":"topic","url":"\/documentation\/zendesksdk\/newconversationbuttonclicked\/data","title":"data","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","text":"NewConversationButtonClickedDetails","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked\/data","navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"data","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"data"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKNewConversationButtonClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKNewConversationButtonClickedDetails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/title"},{"value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/fragments"},{"value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/navigatorTitle","op":"replace"},{"value":"NewConversationButtonClicked","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NewConversationButtonClicked"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/fragments","op":"replace"},{"value":[{"text":"NewConversationButtonClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/navigatorTitle","op":"replace"},{"value":"data","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked~1data\/title","op":"replace"},{"value":[{"kind":"identifier","text":"data"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked~1data\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}