{"metadata":{"roleHeading":"Case","title":"ZendeskConnectionStatus.connectedRealtime","symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectedRealtime"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus@ZDKZendeskConnectionStatusConnectedRealtime","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus"]]},"abstract":[{"text":"The SDK instance is connected to the internet and has a connection established with the server.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectedrealtime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectedrealtime"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectedRealtime","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectedRealtime"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connectedRealtime":{"kind":"symbol","abstract":[{"text":"The SDK instance is connected to the internet and has a connection established with the server.","type":"text"}],"type":"topic","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectedrealtime","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectedRealtime","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectedRealtime","kind":"identifier"}],"title":"ZendeskConnectionStatus.connectedRealtime"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","kind":"symbol","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A representation of the current connection status of the SDK.","type":"text"}],"navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"title":"ZendeskConnectionStatus","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskConnectionStatusConnectedRealtime","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}]}]}},{"value":"ZDKZendeskConnectionStatusConnectedRealtime","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectedRealtime\/title"},{"op":"replace","value":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectedRealtime\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","value":"ZDKZendeskConnectionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}