{"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"text":" from a ","type":"text"},{"code":"carousel","type":"codeVoice"},{"type":"text","text":" message on the conversation screen."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"carousel"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/urlsource\/carousel"]},{"paths":["\/documentation\/zendesksdk\/urlsource\/carousel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/carousel","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"URLSource.carousel","role":"symbol","externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceCarousel","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"carousel","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKURLSourceCarousel","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","abstract":[],"role":"collection","url":"\/documentation\/zendesksdk","type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/carousel":{"title":"URLSource.carousel","navigatorTitle":[{"text":"ZDKURLSourceCarousel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdk\/urlsource\/carousel","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/carousel","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"carousel"},{"type":"text","text":" message on the conversation screen."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"carousel"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLSource"}],"navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdk\/urlsource","title":"URLSource"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKURLSourceCarousel","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKURLSourceCarousel"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKURLSourceCarousel","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKURLSourceCarousel","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1carousel\/title"},{"value":[{"kind":"identifier","text":"ZDKURLSourceCarousel"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1carousel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"}]}]}