{"variants":[{"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters\/conversationkit"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"externalID":"s:10ZendeskSDK26MessagingFactoryParametersC15conversationKit0a15SDKConversationG0012ConversationG0_pvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationKit","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC0P"}],"role":"symbol","title":"conversationKit","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/conversationKit"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationKit","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC0P","kind":"typeIdentifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","type":"topic","kind":"symbol","abstract":[{"text":"The set of parameters to be provided to Messaging(SwiftUI)Factory ","type":"text"},{"code":"createMessaging","type":"codeVoice"},{"text":" to create an instance of ","type":"text"},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"text":".","type":"text"}],"title":"MessagingFactoryParameters","role":"symbol","navigatorTitle":[{"text":"MessagingFactoryParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingFactoryParameters","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/conversationKit":{"abstract":[],"url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/conversationkit","title":"conversationKit","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationKit","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC0P"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/conversationKit"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKMessagingFactoryParameters","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title"},{"op":"replace","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments"},{"op":"replace","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}