{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingSwiftUI","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"messaging","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"MessagingSwiftUI","type":"codeVoice"},{"text":" instance","type":"text"}]}]},{"name":"url","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" the user actioned.","type":"text"}],"type":"paragraph"}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"source","type":"codeVoice"},{"type":"text","text":" from which the user actioned the URL from."}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if MessagingSwiftUI should handle the URL. Return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if there is a specified URL flow.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when there is no way to handle a specific URL and ","type":"text"},{"code":"MessagingSwiftUI","type":"codeVoice"},{"text":" will perform OS default behaviour of opening","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" in the default browser.","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-4qszl"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-1bf33"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","extendedModule":"ZendeskSDK","role":"symbol","modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK24MessagingSwiftUIDelegatePAAE9messaging_15shouldHandleURL4fromSbAA0cD2UIC_10Foundation0I0VAA9URLSourceOtF","symbolKind":"method","title":"messaging(_:shouldHandleURL:from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessagingSwiftUI","kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"url":"\/documentation\/zendesksdk\/urlsource","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"title":"URLSource","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate","abstract":[],"type":"topic","kind":"symbol","title":"MessagingSwiftUIDelegate","role":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSwiftUIDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MessagingSwiftUIDelegate"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUI","kind":"identifier"}],"navigatorTitle":[{"text":"MessagingSwiftUI","kind":"identifier"}],"title":"MessagingSwiftUI","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","url":"\/documentation\/zendesksdk\/messagingswiftui","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)-1bf33":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-1bf33","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-1bf33","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"messaging(_:shouldHandleURL:from:)","abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"defaultImplementations":1,"required":true},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)-4qszl":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-4qszl","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"messaging(_:shouldHandleURL:from:)","abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"}]}]}