{"metadata":{"modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK0A0C16messagingSwiftUIAA09MessagingdE0CSgvp","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"messagingSwiftUI","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingSwiftUI","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"abstract":[{"text":"Optional property allows integrators to interact with the ","type":"text"},{"type":"codeVoice","code":"MessagingSwiftUI"},{"text":" capability and its feature set.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingSwiftUI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"This will be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" is not enabled in the account’s admin settings or the"},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultMessagingSwiftUIFactory"},{"type":"text","text":" was not passed in the "},{"type":"codeVoice","code":"initialize"},{"type":"text","text":" method."}],"type":"paragraph"}],"style":"note","type":"aside"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messagingSwiftUI"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/messagingswiftui"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/messagingSwiftUI":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messagingSwiftUI","title":"messagingSwiftUI","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/messagingswiftui","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingSwiftUI","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Optional property allows integrators to interact with the "},{"type":"codeVoice","code":"MessagingSwiftUI"},{"type":"text","text":" capability and its feature set."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUI","kind":"identifier"}],"navigatorTitle":[{"text":"MessagingSwiftUI","kind":"identifier"}],"title":"MessagingSwiftUI","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","url":"\/documentation\/zendesksdk\/messagingswiftui","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendesk","title":"Zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"value":"Zendesk","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Zendesk"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","op":"replace"},{"value":[{"text":"Zendesk","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}