{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"messaging"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"Messaging"},{"kind":"text","text":"?"}],"title":"messaging","symbolKind":"property","externalID":"c:@M@ZendeskSDK@objc(cs)Zendesk(py)messaging"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messaging","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optional property allows integrators to interact with the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability"},{"type":"text","text":" "},{"type":"text","text":"and its feature set."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"Messaging"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"This will be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" is not enabled in the account’s admin settings or the","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultMessagingFactory"},{"text":" was not passed in the ","type":"text"},{"type":"codeVoice","code":"initialize"},{"text":" method.","type":"text"}]}],"type":"aside","style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/messaging"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendesk\/messaging"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messaging","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"title":"Messaging","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendesk","title":"Zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/messaging":{"navigatorTitle":[{"text":"messaging","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendesk\/messaging","role":"symbol","title":"messaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/messaging","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Optional property allows integrators to interact with the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability"},{"type":"text","text":" "},{"type":"text","text":"and its feature set."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"messaging"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messaging"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKMessaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messaging"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","op":"replace","value":"Zendesk"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","op":"replace","value":[{"text":"Zendesk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Zendesk"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1messaging\/title","op":"replace","value":"messaging"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1messaging\/fragments","op":"replace","value":[{"kind":"identifier","text":"messaging"}]}]}]}