{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ZendeskSDK"}],"title":"ZendeskVersionString","symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZendeskVersionString"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskVersionString"}],"externalID":"c:@ZendeskVersionString","roleHeading":"Global Variable"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZendeskVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Project version string for Zendesk.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionString","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskversionstring"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","abstract":[],"role":"collection","url":"\/documentation\/zendesksdk","type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskVersionString":{"navigatorTitle":[{"kind":"identifier","text":"ZendeskVersionString"}],"url":"\/documentation\/zendesksdk\/zendeskversionstring","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskVersionString","kind":"symbol","abstract":[{"type":"text","text":"Project version string for Zendesk."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZendeskVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"type":"topic","title":"ZendeskVersionString","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZendeskVersionString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZendeskVersionString","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"ZendeskVersionString","kind":"identifier"},{"kind":"text","text":"[]"}],"languages":["occ"]}]},"op":"replace"},{"value":"ZendeskVersionString","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionString\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskVersionString\/fragments","value":[{"text":"ZendeskVersionString","kind":"identifier"}]}]}]}