{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The SDK instance is connected to the internet.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connected","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"role":"symbol","symbolKind":"case","title":"ZendeskConnectionStatus.connected","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus@ZDKZendeskConnectionStatusConnected","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnected","kind":"identifier"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"title":"ZendeskConnectionStatus","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"abstract":[{"text":"A representation of the current connection status of the SDK.","type":"text"}],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connected":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"title":"ZendeskConnectionStatus.connected","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The SDK instance is connected to the internet."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connected","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connected","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnected","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskConnectionStatusConnected","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnected"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKZendeskConnectionStatusConnected","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKZendeskConnectionStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title"},{"value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle"},{"value":"ZDKZendeskConnectionStatusConnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connected\/title"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnected"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connected\/fragments"}]}]}