{"metadata":{"role":"symbol","externalID":"s:10ZendeskSDK24MessagingSwiftUIDelegateP9messaging_15shouldHandleURL4fromSbAA0cD2UIC_10Foundation0I0VAA9URLSourceOtF","required":true,"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"ZendeskSDK"}],"title":"messaging(_:shouldHandleURL:from:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate"]]},"defaultImplementationsSections":[{"anchor":"MessagingSwiftUIDelegate-Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl"],"title":"MessagingSwiftUIDelegate Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-1bf33","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messaging","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"MessagingSwiftUI","type":"codeVoice"},{"type":"text","text":" instance"}],"type":"paragraph"}],"name":"messaging"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" the user actioned."}]}],"name":"url"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" from which the user actioned the URL from.","type":"text"}]}],"name":"source"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if MessagingSwiftUI should handle the URL. Return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if there is a specified URL flow.","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Return ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" when there is no way to handle a specific URL and "},{"type":"codeVoice","code":"MessagingSwiftUI"},{"type":"text","text":" will perform OS default behaviour of opening"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" in the default browser."}]}]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-1bf33"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)-4qszl":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl","role":"symbol","kind":"symbol","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-4qszl","title":"messaging(_:shouldHandleURL:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate","title":"MessagingSwiftUIDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUIDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MessagingSwiftUIDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"role":"symbol","abstract":[],"title":"MessagingSwiftUI","type":"topic","url":"\/documentation\/zendesksdk\/messagingswiftui","navigatorTitle":[{"text":"MessagingSwiftUI","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUI","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","role":"symbol","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"code":"URL","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"URLSource"}],"title":"URLSource","kind":"symbol","url":"\/documentation\/zendesksdk\/urlsource","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)-1bf33":{"title":"messaging(_:shouldHandleURL:from:)","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-1bf33","type":"topic","abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"required":true,"kind":"symbol","defaultImplementations":1,"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-1bf33"}},"variantOverrides":[{"patch":[{"value":"ZDKURLSource","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title"},{"value":[{"kind":"identifier","text":"ZDKURLSource"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments"},{"value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}