{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationbuttonclicked\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/newconversationbuttonclicked\/id"]}],"metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)NewConversationButtonClicked(py)id","navigatorTitle":[{"kind":"identifier","text":"id"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","title":"id"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked\/id","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClicked/id":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked\/id","url":"\/documentation\/zendesksdk\/newconversationbuttonclicked\/id","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClicked":{"role":"symbol","type":"topic","title":"NewConversationButtonClicked","url":"\/documentation\/zendesksdk\/newconversationbuttonclicked","navigatorTitle":[{"kind":"identifier","text":"NewConversationButtonClicked"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClicked","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationButtonClicked"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"id","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked~1id\/title"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked~1id\/fragments"},{"value":"NewConversationButtonClicked","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/title"},{"value":[{"text":"NewConversationButtonClicked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/fragments"},{"value":[{"text":"NewConversationButtonClicked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClicked\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}