{"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"title":"ConversationAgentAssignedDetails","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","navigatorTitle":[{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationAgentAssignedDetails"}],"modules":[{"name":"ZendeskSDK"}],"symbolKind":"class"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/init(conversationId:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/conversationId"],"title":"Instance Properties","anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationAgentAssignedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/conversationagentassigneddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/conversationagentassigneddetails"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails/init(conversationId:)":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/init(conversationId:)","title":"init(conversationId:)","role":"symbol","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails\/init(conversationid:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails/conversationId":{"role":"symbol","title":"conversationId","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/conversationId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails\/conversationid","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"conversationId"}]},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails":{"navigatorTitle":[{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationagentassigneddetails","role":"symbol","title":"ConversationAgentAssignedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","type":"topic"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKConversationAgentAssignedDetails","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKConversationAgentAssignedDetails","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/conversationId"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails~1conversationId\/title","op":"replace","value":"conversationId"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails~1conversationId\/fragments","op":"replace","value":[{"kind":"identifier","text":"conversationId"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/title","op":"replace","value":"ZDKConversationAgentAssignedDetails"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationAgentAssignedDetails","kind":"identifier"}]}]}]}