{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/init(conversationId:url:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/url"],"anchor":"Instance-Properties","generated":true}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","title":"ConversationExtensionDisplayedDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"kind":"relationships","type":"conformsTo"}],"abstract":[{"text":"Details of a conversation extension that was displayed to the end user.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationExtensionDisplayedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails/conversationId":{"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/conversationid","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/conversationId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"conversationId","kind":"symbol","abstract":[{"type":"text","text":"The unique identifier of the conversation"}],"role":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails/url":{"navigatorTitle":[{"text":"url","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The URL of the conversation extension"}],"url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/url","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/url","title":"url","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails/init(conversationId:url:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/init(conversationid:url:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConversationId:url:"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/init(conversationId:url:)","title":"init(conversationId:url:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails":{"navigatorTitle":[{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","title":"ConversationExtensionDisplayedDetails","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Details of a conversation extension that was displayed to the end user."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationExtensionDisplayedDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConversationExtensionDisplayedDetails"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/url"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/init(conversationId:url:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationExtensionDisplayedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1url\/fragments","value":[{"text":"url","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1init(conversationId:url:)\/title","value":"initWithConversationId:url:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1init(conversationId:url:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConversationId:url:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/title","value":"ZDKConversationExtensionDisplayedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/fragments","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}]}]}]}