{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/init(conversationId:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/conversationId"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails"},"kind":"symbol","abstract":[{"type":"text","text":"Details of a conversation where an agent was requested."}],"metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails","title":"ConversationWithAgentRequestedDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"symbolKind":"class"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/zendesksdk\/conversationwithagentrequesteddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationwithagentrequesteddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails/conversationId":{"type":"topic","role":"symbol","title":"conversationId","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/conversationId","abstract":[{"text":"The unique identifier of the conversation","type":"text"}],"url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails\/conversationid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}]},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails/init(conversationId:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/init(conversationId:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"init(conversationId:)","url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails\/init(conversationid:)"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails":{"navigatorTitle":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","abstract":[{"type":"text","text":"Details of a conversation where an agent was requested."}],"title":"ConversationWithAgentRequestedDetails","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}]},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ConversationWithAgentRequestedDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/conversationId"],"anchor":"Instance-Properties","title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/title","value":"ConversationWithAgentRequestedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/fragments","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/navigatorTitle","value":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}