{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/newconversationbuttonclickeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/newconversationbuttonclickeddetails"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails"},"abstract":[{"text":"Details related to the event when the new conversation button is clicked.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKNewConversationButtonClickedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNewConversationButtonClickedDetails","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewConversationButtonClickedDetails"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"NewConversationButtonClickedDetails"}],"role":"symbol","title":"NewConversationButtonClickedDetails"},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/init(newConversationSource:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/newConversationSource"]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails/init(newConversationSource:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newConversationSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","text":"NewConversationSource","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/init(newconversationsource:)","title":"init(newConversationSource:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/init(newConversationSource:)","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails/newConversationSource":{"title":"newConversationSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/newConversationSource","type":"topic","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails\/newconversationsource","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationSource"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@NewConversationSource","kind":"typeIdentifier","text":"NewConversationSource"}],"navigatorTitle":[{"kind":"identifier","text":"newConversationSource"}],"abstract":[{"type":"text","text":"The source from which the new conversation button was clicked"}]},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NewConversationButtonClickedDetails":{"type":"topic","title":"NewConversationButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails","abstract":[{"text":"Details related to the event when the new conversation button is clicked.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"NewConversationButtonClickedDetails","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdk\/newconversationbuttonclickeddetails"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKNewConversationButtonClickedDetails","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NewConversationButtonClickedDetails\/newConversationSource"]}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"newConversationSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails~1newConversationSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"newConversationSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails~1newConversationSource\/fragments"},{"op":"replace","value":"ZDKNewConversationButtonClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/title"},{"op":"replace","value":[{"text":"ZDKNewConversationButtonClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNewConversationButtonClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NewConversationButtonClickedDetails\/navigatorTitle"}]}]}