{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","title":"NotificationDisplayedDetails","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationDisplayedDetails","modules":[{"name":"ZendeskSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationDisplayedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"NotificationDisplayedDetails"}]},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/init(conversationId:messageReceivedTimestamp:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/messageReceivedTimestamp"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Details of a notification that was displayed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKNotificationDisplayedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/messageReceivedTimestamp":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageReceivedTimestamp"}],"abstract":[{"text":"The timestamp when the message was received (Unix timestamp as Double)","type":"text"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/messagereceivedtimestamp","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/messageReceivedTimestamp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReceivedTimestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"messageReceivedTimestamp","kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"abstract":[{"type":"text","text":"Details of a notification that was displayed."}],"navigatorTitle":[{"kind":"identifier","text":"NotificationDisplayedDetails"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","title":"NotificationDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/init(conversationId:messageReceivedTimestamp:)":{"abstract":[],"type":"topic","title":"init(conversationId:messageReceivedTimestamp:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageReceivedTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/init(conversationid:messagereceivedtimestamp:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/init(conversationId:messageReceivedTimestamp:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/conversationId":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/conversationId","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/conversationid","abstract":[{"type":"text","text":"The ID of the conversation associated with the notification"}],"navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"title":"conversationId","type":"topic"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKNotificationDisplayedDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/messageReceivedTimestamp"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1messageReceivedTimestamp\/title","value":"messageReceivedTimestamp"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1messageReceivedTimestamp\/fragments","value":[{"text":"messageReceivedTimestamp","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title","value":"ZDKNotificationDisplayedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKNotificationDisplayedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNotificationDisplayedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1conversationId\/title","value":"conversationId","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}],"op":"replace"}]}]}