{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/init(actionName:conversationId:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/actionName","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/conversationId"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKPostbackButtonClickedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Details of a postback button that was clicked by the end user."}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostbackButtonClickedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"PostbackButtonClickedDetails"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","symbolKind":"class","title":"PostbackButtonClickedDetails","role":"symbol","modules":[{"name":"ZendeskSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/postbackbuttonclickeddetails"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/actionName":{"navigatorTitle":[{"kind":"identifier","text":"actionName"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/actionname","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","kind":"symbol","title":"actionName","abstract":[{"text":"The postback button action name","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/actionName"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/init(actionName:conversationId:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/init(actionName:conversationId:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/init(actionname:conversationid:)","kind":"symbol","navigatorTitle":[{"text":"initWithActionName:conversationId:","kind":"identifier"}],"abstract":[],"title":"init(actionName:conversationId:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails/conversationId":{"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails\/conversationid","title":"conversationId","abstract":[{"type":"text","text":"The unique identifier of the conversation"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/conversationId","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"title":"PostbackButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","abstract":[{"text":"Details of a postback button that was clicked by the end user.","type":"text"}],"role":"symbol"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ZDKPostbackButtonClickedDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/actionName","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/conversationId"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails\/init(actionName:conversationId:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1actionName\/title","value":"actionName","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1actionName\/fragments","value":[{"kind":"identifier","text":"actionName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1init(actionName:conversationId:)\/title","value":"initWithActionName:conversationId:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1init(actionName:conversationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithActionName:conversationId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1conversationId\/title","value":"conversationId","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails~1conversationId\/fragments","value":[{"kind":"identifier","text":"conversationId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","value":"ZDKPostbackButtonClickedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}