{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/init(proactiveMessageId:campaignId:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/campaignId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/proactiveMessageId"],"generated":true,"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/proactivemessagedisplayeddetails"]}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"ProactiveMessageDisplayedDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageDisplayedDetails","symbolKind":"class","navigatorTitle":[{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKProactiveMessageDisplayedDetails) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageDisplayedDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Details of a proactive message that was displayed."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails/campaignId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"campaignId"}],"title":"campaignId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"campaignId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"The ID of the campaign for the proactive message","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/campaignid","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/campaignId"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails":{"kind":"symbol","abstract":[{"text":"Details of a proactive message that was displayed.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageDisplayedDetails"}],"url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails","navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageDisplayedDetails"}],"type":"topic","role":"symbol","title":"ProactiveMessageDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails/init(proactiveMessageId:campaignId:)":{"abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"campaignId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithProactiveMessageId:campaignId:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/init(proactiveMessageId:campaignId:)","title":"init(proactiveMessageId:campaignId:)","role":"symbol","url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/init(proactivemessageid:campaignid:)","type":"topic"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageDisplayedDetails/proactiveMessageId":{"title":"proactiveMessageId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/proactivemessagedisplayeddetails\/proactivemessageid","abstract":[{"type":"text","text":"The ID of the proactive message that was displayed"}],"role":"symbol","navigatorTitle":[{"text":"proactiveMessageId","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/proactiveMessageId"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKProactiveMessageDisplayedDetails","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayedDetails"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageDisplayedDetails"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/campaignId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/proactiveMessageId"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageDisplayedDetails\/init(proactiveMessageId:campaignId:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKProactiveMessageDisplayedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"campaignId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1campaignId\/title"},{"value":[{"kind":"identifier","text":"campaignId"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1campaignId\/fragments","op":"replace"},{"value":"ZDKProactiveMessageDisplayedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/title","op":"replace"},{"value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/fragments","op":"replace"},{"value":[{"text":"ZDKProactiveMessageDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails\/navigatorTitle","op":"replace"},{"value":"initWithProactiveMessageId:campaignId:","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1init(proactiveMessageId:campaignId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithProactiveMessageId:campaignId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1init(proactiveMessageId:campaignId:)\/fragments","op":"replace"},{"value":"proactiveMessageId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1proactiveMessageId\/title","op":"replace"},{"value":[{"text":"proactiveMessageId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageDisplayedDetails~1proactiveMessageId\/fragments","op":"replace"}]}]}