{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/timestamp"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"title":"ZDKConversationAgentAssigned","modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssigned","symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationAgentAssigned","kind":"identifier"}]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned/data":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationAgentAssignedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"title":"data","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/data","role":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned\/data"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned/id":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned\/id","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/id","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"title":"id"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned":{"navigatorTitle":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"title":"ZDKConversationAgentAssigned"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned/timestamp":{"abstract":[],"title":"timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/timestamp","type":"topic","role":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned\/timestamp","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKConversationAgentAssigned","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/timestamp"],"generated":true,"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationAgentAssigned"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"data","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1data\/title"},{"value":[{"text":"data","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1data\/fragments"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1id\/title"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1id\/fragments"},{"value":"ZDKConversationAgentAssigned","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/title"},{"value":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/fragments"},{"value":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/navigatorTitle"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1timestamp\/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1timestamp\/fragments"}]}]}