{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"type":"conformsTo"}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationWithAgentRequested","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}],"symbolKind":"class","role":"symbol","title":"ZDKConversationWithAgentRequested"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkconversationwithagentrequested"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/timestamp"],"anchor":"Instance-Properties"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested":{"type":"topic","url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested","title":"ZDKConversationWithAgentRequested","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}]},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested/timestamp":{"url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/timestamp","type":"topic","title":"timestamp","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/timestamp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested/data":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/data","url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/data","title":"data","navigatorTitle":[{"kind":"identifier","text":"data"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationWithAgentRequestedDetails","text":"ConversationWithAgentRequestedDetails"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationWithAgentRequested/id":{"kind":"symbol","role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"url":"\/documentation\/zendesksdk\/zdkconversationwithagentrequested\/id","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/id"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationWithAgentRequested"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationWithAgentRequested\/timestamp"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationWithAgentRequested"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/title","op":"replace","value":"ZDKConversationWithAgentRequested"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/fragments","op":"replace","value":[{"text":"ZDKConversationWithAgentRequested","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationWithAgentRequested"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1timestamp\/title","op":"replace","value":"timestamp"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1timestamp\/fragments","op":"replace","value":[{"kind":"identifier","text":"timestamp"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1data\/title","op":"replace","value":"data"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1data\/fragments","op":"replace","value":[{"kind":"identifier","text":"data"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1id\/title","op":"replace","value":"id"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationWithAgentRequested~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}