{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/messages","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/timestamp"],"generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagesShown","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagesShown","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessagesShown","role":"symbol","title":"ZDKMessagesShown","roleHeading":"Class","navigatorTitle":[{"text":"ZDKMessagesShown","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkmessagesshown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkmessagesshown"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/messages":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ZendeskMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/messages","type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdk\/zdkmessagesshown\/messages","navigatorTitle":[{"text":"messages","kind":"identifier"}],"title":"messages"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKMessagesShown"}],"url":"\/documentation\/zendesksdk\/zdkmessagesshown","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKMessagesShown"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","title":"ZDKMessagesShown","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/timestamp":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/zendesksdk\/zdkmessagesshown\/timestamp","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/timestamp","title":"timestamp","kind":"symbol"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/id":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"}],"role":"symbol","title":"id","navigatorTitle":[{"kind":"identifier","text":"id"}],"kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdk\/zdkmessagesshown\/id"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/conversationId":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"conversationId","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/conversationId","type":"topic","url":"\/documentation\/zendesksdk\/zdkmessagesshown\/conversationid"},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKMessagesShown","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKMessagesShown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKMessagesShown","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/messages","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/timestamp"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKMessagesShown"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"messages","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1messages\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1messages\/fragments","value":[{"text":"messages","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/title","value":"ZDKMessagesShown","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/fragments","value":[{"kind":"identifier","text":"ZDKMessagesShown"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/navigatorTitle","value":[{"text":"ZDKMessagesShown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1timestamp\/title","value":"timestamp","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1id\/title","value":"id","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1conversationId\/title","value":"conversationId","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}],"op":"replace"}]}]}