{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkpostbackbuttonclicked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkpostbackbuttonclicked"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/timestamp"],"anchor":"Instance-Properties"}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"modules":[{"name":"ZendeskSDK"}],"title":"ZDKPostbackButtonClicked","role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClicked","symbolKind":"class"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"abstract":[],"url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked","title":"ZDKPostbackButtonClicked","role":"symbol"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked/id":{"role":"symbol","type":"topic","title":"id","navigatorTitle":[{"text":"id","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/id","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/id","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}]},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked/data":{"type":"topic","navigatorTitle":[{"text":"data","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/data","title":"data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","text":"PostbackButtonClickedDetails","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/data","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked/timestamp":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/timestamp","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/timestamp","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"title":"timestamp"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKPostbackButtonClicked"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/data","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/timestamp"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPostbackButtonClicked","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/title","value":"ZDKPostbackButtonClicked","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackButtonClicked"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/navigatorTitle","value":[{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1id\/title","value":"id","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1data\/title","value":"data","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1data\/fragments","value":[{"kind":"identifier","text":"data"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1timestamp\/title","value":"timestamp","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"timestamp"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1timestamp\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}