{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","text":"ArticleClickedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the event (UUID).","type":"text"}]}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The timestamp when the event is fired.","type":"text"}]}],"name":"timestamp"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details of the article clicked including:"},{"type":"text","text":" "},{"type":"text","text":"articleId - The unique identifier of the article (String),"},{"type":"text","text":" "},{"type":"text","text":"articleTitle - The article title (String, nullable)."}]}],"name":"data"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/articleclicked(id:timestamp:data:)"]}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails","text":"ArticleClickedDetails"},{"kind":"text","text":")"}],"roleHeading":"Case","externalID":"s:10ZendeskSDK0A5EventO14articleClickedyAC10Foundation4UUIDV_AE4DateVAA07ArticleE7DetailsCtcACmF","title":"ZendeskEvent.articleClicked(id:timestamp:data:)"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/articleClicked(id:timestamp:data:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Invoked when an end-user clicks on an article."}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/articleClicked(id:timestamp:data:)":{"title":"ZendeskEvent.articleClicked(id:timestamp:data:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ArticleClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKArticleClickedDetails"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when an end-user clicks on an article."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/articleClicked(id:timestamp:data:)","url":"\/documentation\/zendesksdk\/zendeskevent\/articleclicked(id:timestamp:data:)","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ArticleClickedDetails":{"title":"ArticleClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ArticleClickedDetails","role":"symbol","url":"\/documentation\/zendesksdk\/articleclickeddetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ArticleClickedDetails","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/title","value":"ZDKArticleClickedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ArticleClickedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKArticleClickedDetails"}],"op":"replace"}]}]}