{"kind":"symbol","metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","title":"ZendeskEvent.conversationExtensionOpened(id:timestamp:data:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionOpened","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:10ZendeskSDK0A5EventO27conversationExtensionOpenedyAC10Foundation4UUIDV_AE4DateVAA012ConversationeF7DetailsCtcACmF","roleHeading":"Case"},"sections":[],"abstract":[{"text":"Invoked when a conversation extension is opened by an end-user.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/conversationextensionopened(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationExtensionOpened(id:timestamp:data:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionOpened","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","text":"ConversationExtensionOpenedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"UUID - The unique identifier of the event","type":"text"}]}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Date - The timestamp when the event is fired","type":"text"}]}],"name":"timestamp"},{"content":[{"type":"paragraph","inlineContent":[{"text":"ConversationExtensionOpenedDetails - Details of the conversation extension:","type":"text"}]}],"name":"data"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/conversationExtensionOpened(id:timestamp:data:)":{"abstract":[{"type":"text","text":"Invoked when a conversation extension is opened by an end-user."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationExtensionOpened"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier","text":"ConversationExtensionOpenedDetails"},{"kind":"text","text":")"}],"title":"ZendeskEvent.conversationExtensionOpened(id:timestamp:data:)","type":"topic","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskevent\/conversationextensionopened(id:timestamp:data:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationExtensionOpened(id:timestamp:data:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails":{"url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"title":"ConversationExtensionOpenedDetails","navigatorTitle":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ConversationExtensionOpenedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/title"},{"op":"replace","value":[{"text":"ConversationExtensionOpenedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/fragments"},{"op":"replace","value":[{"text":"ConversationExtensionOpenedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/navigatorTitle"}]}]}