{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationExtensionDisplayed(id:timestamp:data:)","interfaceLanguage":"swift"},"abstract":[{"text":"Invoked when a conversation extension content has been displayed to the end-user.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/conversationextensiondisplayed(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"case","role":"symbol","title":"ZendeskEvent.conversationExtensionDisplayed(id:timestamp:data:)","externalID":"s:10ZendeskSDK0A5EventO30conversationExtensionDisplayedyAC10Foundation4UUIDV_AE4DateVAA012ConversationeF7DetailsCtcACmF","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails"},{"text":")","kind":"text"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationExtensionDisplayed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","text":"ConversationExtensionDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the event (UUID).","type":"text"}]}]},{"name":"timestamp","content":[{"inlineContent":[{"type":"text","text":"The timestamp when the event is fired."}],"type":"paragraph"}]},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"Details of the conversation extension displayed including:"},{"type":"text","text":" "},{"type":"text","text":"conversationId - The unique identifier of the conversation (String),"},{"type":"text","text":" "},{"type":"text","text":"url - The URL of the conversation extension (String)."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/conversationExtensionDisplayed(id:timestamp:data:)":{"type":"topic","abstract":[{"text":"Invoked when a conversation extension content has been displayed to the end-user.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationExtensionDisplayed(id:timestamp:data:)","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskevent\/conversationextensiondisplayed(id:timestamp:data:)","title":"ZendeskEvent.conversationExtensionDisplayed(id:timestamp:data:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionDisplayed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","text":"ConversationExtensionDisplayedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"title":"ConversationExtensionDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails","type":"topic","abstract":[{"type":"text","text":"Details of a conversation extension that was displayed to the end user."}],"navigatorTitle":[{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/title","value":"ZDKConversationExtensionDisplayedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKConversationExtensionDisplayedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}],"op":"replace"}]}]}