{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Invoked when an agent assigned to the conversation."}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationAgentAssigned(id:timestamp:data:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/conversationagentassigned(id:timestamp:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationAgentAssigned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"UUID - The unique identifier of the event","type":"text"}]}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Date - The timestamp when the event is fired"}]}],"name":"timestamp"},{"content":[{"inlineContent":[{"type":"text","text":"ConversationAgentAssignedDetails - Details of the Agent assigned to conversation:"},{"type":"text","text":" "},{"type":"text","text":"conversationId - The unique identifier of the conversation"}],"type":"paragraph"}],"name":"data"}]}],"metadata":{"externalID":"s:10ZendeskSDK0A5EventO25conversationAgentAssignedyAC10Foundation4UUIDV_AE4DateVAA012ConversationeF7DetailsCtcACmF","modules":[{"name":"ZendeskSDK"}],"title":"ZendeskEvent.conversationAgentAssigned(id:timestamp:data:)","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationAgentAssigned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails"},{"kind":"text","text":")"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","kind":"symbol","title":"ConversationAgentAssignedDetails","abstract":[],"type":"topic","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationAgentAssignedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationAgentAssignedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/conversationAgentAssigned(id:timestamp:data:)":{"title":"ZendeskEvent.conversationAgentAssigned(id:timestamp:data:)","abstract":[{"text":"Invoked when an agent assigned to the conversation.","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskevent\/conversationagentassigned(id:timestamp:data:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAgentAssigned","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssignedDetails","text":"ConversationAgentAssignedDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationAgentAssigned(id:timestamp:data:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/title","value":"ZDKConversationAgentAssignedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/fragments","value":[{"text":"ZDKConversationAgentAssignedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}],"op":"replace"}]}]}