{"metadata":{"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","externalID":"s:10ZendeskSDK0A5EventO25conversationServedByAgentyAC10Foundation4UUIDV_AE4DateVAA012ConversationefG7DetailsCtcACmF","role":"symbol","title":"ZendeskEvent.conversationServedByAgent(id:timestamp:data:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationServedByAgent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationServedByAgentDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationServedByAgentDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/conversationservedbyagent(id:timestamp:data:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Invoked when a conversation is served by an agent (agent sends first message).","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationServedByAgent(id:timestamp:data:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationServedByAgent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails","text":"ConversationServedByAgentDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationServedByAgentDetails"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"id","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the event (UUID)."}]}]},{"name":"timestamp","content":[{"inlineContent":[{"type":"text","text":"The timestamp when the event is fired."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details of the conversation served by agent including:"},{"type":"text","text":" "},{"type":"text","text":"agentDisplayName - The display name of the agent (String),"},{"type":"text","text":" "},{"type":"text","text":"agentId - Unique identifier for the agent (String),"},{"type":"text","text":" "},{"type":"text","text":"agentMessageSource - Source\/tool context of agent’s message (AgentMessageSource),"},{"type":"text","text":" "},{"type":"text","text":"conversationId - Unique identifier for the conversation (String)."}]}]}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/conversationServedByAgent(id:timestamp:data:)":{"title":"ZendeskEvent.conversationServedByAgent(id:timestamp:data:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationServedByAgent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationServedByAgentDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationServedByAgentDetails"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invoked when a conversation is served by an agent (agent sends first message)."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/conversationServedByAgent(id:timestamp:data:)","url":"\/documentation\/zendesksdk\/zendeskevent\/conversationservedbyagent(id:timestamp:data:)","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationServedByAgentDetails"}],"title":"ConversationServedByAgentDetails","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServedByAgentDetails"}]}},"variantOverrides":[{"patch":[{"value":"ZDKConversationServedByAgentDetails","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/title"},{"value":[{"kind":"identifier","text":"ZDKConversationServedByAgentDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/fragments"},{"value":[{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}