{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/messagesShown(id:timestamp:conversationId:messages:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Invoked when the messages shown to the user are updated."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagesShown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage","text":"ZendeskMessage","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"id","content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the event."}],"type":"paragraph"}]},{"name":"timestamp","content":[{"inlineContent":[{"text":"The timestamp of the event.","type":"text"}],"type":"paragraph"}]},{"name":"conversationId","content":[{"inlineContent":[{"text":"The id of the conversation that the messages belong to.","type":"text"}],"type":"paragraph"}]},{"name":"messages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"ZendeskMessage"},{"type":"text","text":" that are displayed in the conversation."}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagesShown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ZendeskMessage","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK0A5EventO13messagesShownyAC10Foundation4UUIDV_AE4DateVSSSayAA0A7MessageCGtcACmF","title":"ZendeskEvent.messagesShown(id:timestamp:conversationId:messages:)"},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskevent\/messagesshown(id:timestamp:conversationid:messages:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"role":"symbol","type":"topic","title":"ZendeskMessage","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZendeskMessage","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskmessage"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/messagesShown(id:timestamp:conversationId:messages:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagesShown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage","text":"ZendeskMessage","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Invoked when the messages shown to the user are updated.","type":"text"}],"url":"\/documentation\/zendesksdk\/zendeskevent\/messagesshown(id:timestamp:conversationid:messages:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/messagesShown(id:timestamp:conversationId:messages:)","title":"ZendeskEvent.messagesShown(id:timestamp:conversationId:messages:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title","op":"replace","value":"ZDKZendeskMessage"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments","op":"replace","value":[{"text":"ZDKZendeskMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}