{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Invoked when a proactive message has been clicked by the end-user."}],"metadata":{"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","title":"ZendeskEvent.proactiveMessageClicked(id:timestamp:data:)","externalID":"s:10ZendeskSDK0A5EventO23proactiveMessageClickedyAC10Foundation4UUIDV_AE4DateVAA09ProactiveeF7DetailsCtcACmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","text":"ProactiveMessageClickedDetails"},{"kind":"text","text":")"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/proactiveMessageClicked(id:timestamp:data:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/proactivemessageclicked(id:timestamp:data:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","text":"ProactiveMessageClickedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the event (UUID).","type":"text"}]}],"name":"id"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp when the proactive message was clicked."}]}],"name":"timestamp"},{"content":[{"inlineContent":[{"text":"Details of the proactive message clicked including:","type":"text"},{"text":" ","type":"text"},{"text":"proactiveMessageId - The ID of the proactive message (String),","type":"text"},{"text":" ","type":"text"},{"text":"campaignId - The ID of the campaign for the proactive message (String).","type":"text"}],"type":"paragraph"}],"name":"data"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskEvent"}],"type":"topic","role":"symbol","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","url":"\/documentation\/zendesksdk\/zendeskevent","title":"ZendeskEvent"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ProactiveMessageClickedDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageClickedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/proactivemessageclickeddetails","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ProactiveMessageClickedDetails","title":"ProactiveMessageClickedDetails","abstract":[{"type":"text","text":"Details of a proactive message that was clicked."}],"navigatorTitle":[{"text":"ProactiveMessageClickedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/proactiveMessageClicked(id:timestamp:data:)":{"abstract":[{"type":"text","text":"Invoked when a proactive message has been clicked by the end-user."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKProactiveMessageClickedDetails","kind":"typeIdentifier","text":"ProactiveMessageClickedDetails"},{"kind":"text","text":")"}],"title":"ZendeskEvent.proactiveMessageClicked(id:timestamp:data:)","type":"topic","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskevent\/proactivemessageclicked(id:timestamp:data:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/proactiveMessageClicked(id:timestamp:data:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/title","op":"replace","value":"ZDKProactiveMessageClickedDetails"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ProactiveMessageClickedDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageClickedDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}