{"metadata":{"symbolKind":"property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails(py)conversationId","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"conversationId","navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/conversationId"},"abstract":[{"text":"The unique identifier of the conversation","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/conversationid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/conversationid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails/conversationId":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/conversationId","navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier of the conversation"}],"title":"conversationId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/conversationid","role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"title":"ConversationExtensionDisplayedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails","type":"topic","abstract":[{"type":"text","text":"Details of a conversation extension that was displayed to the end user."}],"navigatorTitle":[{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"conversationId","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"conversationId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"conversationId","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1conversationId\/title"},{"value":[{"text":"conversationId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1conversationId\/fragments"},{"value":"ZDKConversationExtensionDisplayedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/title","op":"replace"},{"value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/fragments","op":"replace"},{"value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/navigatorTitle","op":"replace"}]}]}