{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier","text":"ConversationExtensionOpenedDetails"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"data"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionOpened(py)data","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier","text":"ConversationExtensionOpenedDetails"}],"symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"title":"data"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/data","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkconversationextensionopened\/data"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkconversationextensionopened\/data"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened/data":{"title":"data","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationextensionopened\/data","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened\/data","abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"data","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionOpened":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkconversationextensionopened","role":"symbol","navigatorTitle":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionOpened","title":"ZDKConversationExtensionOpened"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionOpenedDetails":{"url":"\/documentation\/zendesksdk\/conversationextensionopeneddetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"title":"ConversationExtensionOpenedDetails","navigatorTitle":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"data","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"data"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ConversationExtensionOpenedDetails","text":"ConversationExtensionOpenedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1data\/title","value":"data","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened~1data\/fragments","value":[{"kind":"identifier","text":"data"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/title","value":"ZDKConversationExtensionOpened","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/fragments","value":[{"kind":"identifier","text":"ZDKConversationExtensionOpened"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionOpened\/navigatorTitle","value":[{"text":"ZDKConversationExtensionOpened","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/title","value":"ConversationExtensionOpenedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/fragments","value":[{"text":"ConversationExtensionOpenedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionOpenedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationExtensionOpenedDetails"}],"op":"replace"}]}]}