{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationTags()"},"metadata":{"modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(im)clearConversationTags","symbolKind":"method","title":"clearConversationTags()"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdk\/messaging\/clearconversationtags()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/messaging\/clearconversationtags()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Clears all custom tags from storage.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"title":"Messaging","kind":"symbol","url":"\/documentation\/zendesksdk\/messaging","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","abstract":[],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/clearConversationTags()":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationTags()","abstract":[{"type":"text","text":"Clears all custom tags from storage."}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/messaging\/clearconversationtags()","navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clearConversationTags()","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearConversationTags"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationTags()\/title","value":"clearConversationTags"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationTags()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}