{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"webView"},{"type":"text","text":" message button from a message on the conversation screen."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"metadata":{"navigatorTitle":[{"text":"ZDKURLSourceWebViewMessageAction","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewMessageAction","kind":"identifier"}],"title":"URLSource.webViewMessageAction","role":"symbol","modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceWebViewMessageAction","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/webViewMessageAction"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewMessageAction","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/urlsource\/webviewmessageaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/urlsource\/webviewmessageaction"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/webViewMessageAction":{"kind":"symbol","navigatorTitle":[{"text":"ZDKURLSourceWebViewMessageAction","kind":"identifier"}],"title":"URLSource.webViewMessageAction","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewMessageAction","kind":"identifier"}],"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"webView"},{"type":"text","text":" message button from a message on the conversation screen."}],"url":"\/documentation\/zendesksdk\/urlsource\/webviewmessageaction","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/webViewMessageAction","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"url":"\/documentation\/zendesksdk\/urlsource","kind":"symbol","type":"topic","title":"URLSource","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"navigatorTitle":[{"text":"URLSource","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKURLSourceWebViewMessageAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceWebViewMessageAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKURLSourceWebViewMessageAction"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1webViewMessageAction\/title","value":"ZDKURLSourceWebViewMessageAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1webViewMessageAction\/fragments","value":[{"kind":"identifier","text":"ZDKURLSourceWebViewMessageAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}