{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"ZendeskSDK","relatedModules":["Swift"]}],"title":"hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"Swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/hash(into:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","title":"ZendeskConnectionStatus","role":"symbol","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","type":"topic","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/RawRepresentable-Implementations":{"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/rawrepresentable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/hash(into:)":{"abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"type":"topic","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/hash(into:)","title":"hash(into:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/hash(into:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","value":"ZDKZendeskConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}