{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/notificationopeneddetails\/init(conversationid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/notificationopeneddetails\/init(conversationid:)"]}],"metadata":{"title":"init(conversationId:)","modules":[{"name":"ZendeskSDK"}],"role":"symbol","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpenedDetails(im)initWithConversationId:","symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithConversationId:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails\/init(conversationId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationOpenedDetails":{"url":"\/documentation\/zendesksdk\/notificationopeneddetails","kind":"symbol","abstract":[{"type":"text","text":"Details of a notification that was opened by the end user."}],"title":"NotificationOpenedDetails","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails","type":"topic","navigatorTitle":[{"text":"NotificationOpenedDetails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationOpenedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationOpenedDetails/init(conversationId:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithConversationId:"}],"type":"topic","kind":"symbol","title":"init(conversationId:)","url":"\/documentation\/zendesksdk\/notificationopeneddetails\/init(conversationid:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails\/init(conversationId:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithConversationId:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConversationId:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/title","value":"ZDKNotificationOpenedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/fragments","value":[{"text":"ZDKNotificationOpenedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNotificationOpenedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails~1init(conversationId:)\/title","value":"initWithConversationId:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails~1init(conversationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConversationId:","kind":"identifier"}],"op":"replace"}]}]}