{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"accountDescription","role":"symbol","modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK17MessagingSettingsC18accountDescriptionSSSgvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingsettings\/accountdescription"]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/accountDescription","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings":{"url":"\/documentation\/zendesksdk\/messagingsettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSettings","kind":"identifier"}],"title":"MessagingSettings","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","type":"topic","abstract":[],"navigatorTitle":[{"text":"MessagingSettings","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings/accountDescription":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/accountDescription","title":"accountDescription","type":"topic","url":"\/documentation\/zendesksdk\/messagingsettings\/accountdescription","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","url":"\/documentation\/zendesksdk","abstract":[],"type":"topic","title":"ZendeskSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/title","op":"replace","value":"ZDKMessagingSettings"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/fragments","op":"replace","value":[{"text":"ZDKMessagingSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKMessagingSettings"}]}]}]}