{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"sections":[],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"ZDKZendeskEventConversationAdded","kind":"identifier"}],"title":"ZDKZendeskEvent.conversationAdded","symbolKind":"case","role":"symbol","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationAdded","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAdded","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAdded","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationadded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationadded"]}],"abstract":[{"text":"Invoked when a conversation has been added.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAdded","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"kind":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent","type":"topic","title":"ZDKZendeskEvent","abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","url":"\/documentation\/zendesksdk","abstract":[],"type":"topic","title":"ZendeskSDK","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationAdded":{"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationadded","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKZendeskEventConversationAdded","kind":"identifier"}],"role":"symbol","title":"ZDKZendeskEvent.conversationAdded","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationAdded","abstract":[{"text":"Invoked when a conversation has been added.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationAdded","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEventConversationAdded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKZendeskEventConversationAdded","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventConversationAdded"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAdded\/title","value":"ZDKZendeskEventConversationAdded"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationAdded\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationAdded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}