{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withChannelKey"},{"text":" ","kind":"text"},{"text":"channelKey","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"messagingSwiftUIFactory"},{"text":": ","kind":"text"},{"text":"MessagingSwiftUIFactory","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP"},{"text":"? = nil, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key of your Messaging iOS channel"}]}],"name":"channelKey"},{"name":"messagingFactory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional parameter to include the "},{"type":"codeVoice","code":"Messaging"},{"text":" UIKit capability, pass an initialized ","type":"text"},{"type":"codeVoice","code":"DefaultMessagingFactory"},{"type":"text","text":" here."}]}]},{"content":[{"inlineContent":[{"text":"Optional parameter to include the ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" SwiftUI capability,"},{"text":" ","type":"text"},{"type":"text","text":"pass an initialized "},{"type":"codeVoice","code":"DefaultMessagingSwiftUIFactory"},{"type":"text","text":" here."}],"type":"paragraph"}],"name":"messagingSwiftUIFactory"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"A block that takes a ","type":"text"},{"code":"Result","type":"codeVoice"},{"text":" enum type. In the case of a success, a ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" "},{"type":"text","text":"instance will be returned, in the case of a failure an "},{"code":"Error","type":"codeVoice"},{"text":" type.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"This method must complete successfully before "},{"code":"Zendesk.instance","type":"codeVoice"},{"type":"text","text":" can be called."},{"type":"text","text":" "},{"text":"After a successful call has been made, calling it again with the same ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"text":" will succeed immediately","type":"text"},{"type":"text","text":" "},{"type":"text","text":"without performing a network call."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Attention"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"messagingSwiftUIFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP","kind":"typeIdentifier","text":"MessagingSwiftUIFactory"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"externalID":"s:10ZendeskSDK0A0C10initialize14withChannelKey16messagingFactory0G14SwiftUIFactory17completionHandlerySS_AA09MessagingH0_pSgAA0miJ0_pSgys6ResultOyACs5Error_pGctFZ","modules":[{"name":"ZendeskSDK"}],"symbolKind":"method","platforms":[{"introducedAt":"14.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false}],"title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","role":"symbol","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:completionhandler:)"]}],"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":". A "},{"code":"MessagingFactory","type":"codeVoice"},{"text":" for UIKit or ","type":"text"},{"code":"MessagingSwiftUIFactory","type":"codeVoice"},{"type":"text","text":" "},{"text":"for SwiftUI can be optionally passed here to add the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"code":"completionHandler","type":"codeVoice"},{"type":"text","text":" with the result."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)":{"url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:completionhandler:)","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:completionHandler:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes "},{"code":"Zendesk","type":"codeVoice"},{"text":" for the given ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":". A "},{"code":"MessagingFactory","type":"codeVoice"},{"type":"text","text":" for UIKit or "},{"code":"MessagingSwiftUIFactory","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"for SwiftUI can be optionally passed here to add the "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messagingSwiftUIFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP","text":"MessagingSwiftUIFactory"},{"kind":"text","text":"?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/zendesksdk","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk","title":"Zendesk","type":"topic","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"title":"MessagingFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessagingFactory"}],"url":"\/documentation\/zendesksdk\/messagingfactory"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIFactory":{"kind":"symbol","navigatorTitle":[{"text":"MessagingSwiftUIFactory","kind":"identifier"}],"title":"MessagingSwiftUIFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSwiftUIFactory"}],"url":"\/documentation\/zendesksdk\/messagingswiftuifactory"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory"},{"op":"replace","value":[{"kind":"identifier","text":"MessagingFactory"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}