{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskrole"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskrole"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/Se","doc:\/\/com.zendesk.Zendesk\/SE","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKZendeskRole) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskRole"}]}]}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskRole"}],"role":"symbol","title":"ZendeskRole","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskRole"}],"roleHeading":"Enumeration","symbolKind":"enum"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/business","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/user"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/user":{"url":"\/documentation\/zendesksdk\/zendeskrole\/user","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/user","role":"symbol","type":"topic","title":"ZendeskRole.user","kind":"symbol","abstract":[{"text":"The message is authored by a user.","type":"text"}],"navigatorTitle":[{"text":"ZDKZendeskRoleUser","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/zendeskrole\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/RawRepresentable-Implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/Equatable-Implementations":{"url":"\/documentation\/zendesksdk\/zendeskrole\/equatable-implementations","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/Equatable-Implementations"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/SY":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/business":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"business"}],"url":"\/documentation\/zendesksdk\/zendeskrole\/business","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskRoleBusiness"}],"abstract":[{"type":"text","text":"The message is authored by the business."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/business","title":"ZendeskRole.business"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole/init(rawValue:)":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/zendesksdk\/zendeskrole\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/init(rawValue:)"},"doc://com.zendesk.Zendesk/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/Se","title":"Swift.Decodable"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SE","title":"Swift.Encodable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskRole":{"navigatorTitle":[{"text":"ZendeskRole","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdk\/zendeskrole","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskRole","kind":"identifier"}],"title":"ZendeskRole","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"ZDKZendeskRole","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKZendeskRole","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/business","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskRole\/user"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1user\/title","value":"ZDKZendeskRoleUser","op":"replace"},{"op":"replace","value":[{"text":"ZDKZendeskRoleUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1user\/fragments"},{"op":"replace","value":"ZDKZendeskRoleBusiness","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1business\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole~1business\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskRoleBusiness"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/title","value":"ZDKZendeskRole","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/fragments","value":[{"text":"ZDKZendeskRole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskRole\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskRole"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}