{"sections":[],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connected","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectedRealtime","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectingRealtime","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/disconnected"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/stringValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/Equatable-Implementations","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ZendeskSDK"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","title":"ZendeskConnectionStatus","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH","doc:\/\/com.zendesk.Zendesk\/SY"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKZendeskConnectionStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskConnectionStatus"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskconnectionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connectingRealtime":{"title":"ZendeskConnectionStatus.connectingRealtime","kind":"symbol","abstract":[{"type":"text","text":"The SDK instance is establishing the realtime connection with the server."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectingRealtime","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectingrealtime","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectingRealtime","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnectingRealtime","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/stringValue":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/stringValue","abstract":[],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/stringvalue","title":"stringValue"},"doc://com.zendesk.Zendesk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SY"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connectedRealtime":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectedRealtime"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectedRealtime","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnectedRealtime"}],"abstract":[{"type":"text","text":"The SDK instance is connected to the internet and has a connection established with the server."}],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connectedrealtime","title":"ZendeskConnectionStatus.connectedRealtime"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskConnectionStatus"}],"title":"ZendeskConnectionStatus","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","navigatorTitle":[{"kind":"identifier","text":"ZendeskConnectionStatus"}],"abstract":[{"type":"text","text":"A representation of the current connection status of the SDK."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/RawRepresentable-Implementations":{"type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/RawRepresentable-Implementations","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/connected":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusConnected","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK instance is connected to the internet."}],"title":"ZendeskConnectionStatus.connected","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/connected"},"doc://com.zendesk.Zendesk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/disconnected":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskConnectionStatusDisconnected","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/disconnected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}],"abstract":[{"text":"The SDK instance has no internet connection.","type":"text"}],"title":"ZendeskConnectionStatus.disconnected","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/disconnected"},"doc://com.zendesk.Zendesk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/init(rawValue:)":{"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/init(rawvalue:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus/Equatable-Implementations":{"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus\/equatable-implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/Equatable-Implementations","title":"Equatable Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ZDKZendeskConnectionStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connected","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectedRealtime","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/connectingRealtime","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus\/disconnected"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskConnectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectingRealtime\/title","op":"replace","value":"ZDKZendeskConnectionStatusConnectingRealtime"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectingRealtime\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatusConnectingRealtime"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectedRealtime\/title","op":"replace","value":"ZDKZendeskConnectionStatusConnectedRealtime"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connectedRealtime\/fragments","op":"replace","value":[{"text":"ZDKZendeskConnectionStatusConnectedRealtime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title","op":"replace","value":"ZDKZendeskConnectionStatus"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connected\/title","op":"replace","value":"ZDKZendeskConnectionStatusConnected"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1connected\/fragments","op":"replace","value":[{"text":"ZDKZendeskConnectionStatusConnected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1disconnected\/title","op":"replace","value":"ZDKZendeskConnectionStatusDisconnected"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus~1disconnected\/fragments","op":"replace","value":[{"text":"ZDKZendeskConnectionStatusDisconnected","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}