{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationFields()","interfaceLanguage":"swift"},"abstract":[{"text":"Clears all custom fields from storage.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearConversationFields","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messaging\/clearconversationfields()"]},{"paths":["\/documentation\/zendesksdk\/messaging\/clearconversationfields()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"clearConversationFields","kind":"identifier"}],"title":"clearConversationFields()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearConversationFields"},{"text":"()","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(im)clearConversationFields"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","url":"\/documentation\/zendesksdk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/zendesksdk\/messaging","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"title":"Messaging","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/clearConversationFields()":{"url":"\/documentation\/zendesksdk\/messaging\/clearconversationfields()","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/clearConversationFields()","title":"clearConversationFields()","abstract":[{"text":"Clears all custom fields from storage.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearConversationFields","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"clearConversationFields","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"clearConversationFields"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearConversationFields","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"clearConversationFields","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","value":"ZDKMessaging","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKMessaging"}]},{"value":"clearConversationFields","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationFields()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clearConversationFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1clearConversationFields()\/fragments"}]}]}