{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/messagingsettings\/enabled"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"enabled","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"s:10ZendeskSDK17MessagingSettingsC7enabledSbvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/enabled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSettings"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/zendesksdk\/messagingsettings","navigatorTitle":[{"kind":"identifier","text":"MessagingSettings"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","title":"MessagingSettings","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings/enabled":{"url":"\/documentation\/zendesksdk\/messagingsettings\/enabled","type":"topic","title":"enabled","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/enabled","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/title","op":"replace","value":"ZDKMessagingSettings"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessagingSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/navigatorTitle","op":"replace","value":[{"text":"ZDKMessagingSettings","kind":"identifier"}]}]}]}