{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/timestamp"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationStarted"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"ZDKConversationStarted","role":"symbol","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationStarted"}],"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationStarted","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationStarted"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkconversationstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkconversationstarted"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","type":"topic","role":"collection"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.Zendesk/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted/timestamp":{"kind":"symbol","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[],"title":"timestamp","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/timestamp","url":"\/documentation\/zendesksdk\/zdkconversationstarted\/timestamp"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted/conversationId":{"type":"topic","url":"\/documentation\/zendesksdk\/zdkconversationstarted\/conversationid","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"conversationId","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/conversationId","role":"symbol","navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationStarted"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted","url":"\/documentation\/zendesksdk\/zdkconversationstarted","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationStarted"}],"title":"ZDKConversationStarted","kind":"symbol"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted/id":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/id","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdk\/zdkconversationstarted\/id","type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}],"role":"symbol","title":"id"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationStarted"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationStarted"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKConversationStarted","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/conversationId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/id","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/timestamp"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationStarted","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"timestamp","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1timestamp\/title"},{"op":"replace","value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1timestamp\/fragments"},{"op":"replace","value":"conversationId","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1conversationId\/title"},{"op":"replace","value":[{"text":"conversationId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1conversationId\/fragments"},{"op":"replace","value":"ZDKConversationStarted","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationStarted"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationStarted"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/navigatorTitle"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1id\/title"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1id\/fragments"}]}]}