{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"messagingSettings","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","text":"MessagingSettings","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingSettings"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessagingSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingSettings"}],"roleHeading":"Instance Property","role":"symbol","title":"messagingSettings","externalID":"s:10ZendeskSDK26MessagingFactoryParametersC17messagingSettingsAA0cG0Cvp","symbolKind":"property","modules":[{"name":"ZendeskSDK"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters\/messagingsettings"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/messagingSettings","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/messagingSettings":{"title":"messagingSettings","role":"symbol","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/messagingsettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagingSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingSettings","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingSettings"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/messagingSettings"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","kind":"symbol","title":"MessagingFactoryParameters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessagingFactoryParameters"}],"type":"topic","navigatorTitle":[{"text":"MessagingFactoryParameters","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingfactoryparameters","abstract":[{"type":"text","text":"The set of parameters to be provided to Messaging(SwiftUI)Factory "},{"code":"createMessaging","type":"codeVoice"},{"text":" to create an instance of ","type":"text"},{"type":"codeVoice","code":"Messaging(SwiftUI)"},{"type":"text","text":"."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSettings"}],"type":"topic","title":"MessagingSettings","role":"symbol","navigatorTitle":[{"text":"MessagingSettings","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","kind":"symbol","url":"\/documentation\/zendesksdk\/messagingsettings"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/zendesksdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","value":"ZDKMessagingFactoryParameters","op":"replace"},{"op":"replace","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/title","value":"ZDKMessagingSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/fragments","value":[{"text":"ZDKMessagingSettings","kind":"identifier"}]}]}]}