{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKZendeskUser) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser","modules":[{"name":"ZendeskSDK"}],"role":"symbol","navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"title":"ZendeskUser"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/Se","doc:\/\/com.zendesk.Zendesk\/SE","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"kind":"relationships"}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/init(from:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/authenticationType","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/externalId","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/id"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdk\/zendeskuser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendeskuser"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/authenticationType":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationType","preciseIdentifier":"s:25ZendeskSDKConversationKit18AuthenticationTypeO","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The authentication type of the "},{"code":"User","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/authenticationType","type":"topic","url":"\/documentation\/zendesksdk\/zendeskuser\/authenticationtype","title":"authenticationType","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/init(from:)","type":"topic","url":"\/documentation\/zendesksdk\/zendeskuser\/init(from:)","abstract":[],"role":"symbol"},"doc://com.zendesk.Zendesk/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/SE","title":"Swift.Encodable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/id":{"title":"id","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zendeskuser\/id","abstract":[{"type":"text","text":"The id of the "},{"code":"User","type":"codeVoice"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/id"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/externalId":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/externalId","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser\/externalid","abstract":[{"text":"The external id of the ","type":"text"},{"type":"codeVoice","code":"User"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"externalId"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Zendesk/SH":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Zendesk/SQ":{"identifier":"doc:\/\/com.zendesk.Zendesk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"title":"ZendeskUser","navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","abstract":[]},"doc://com.zendesk.Zendesk/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Zendesk\/Se","title":"Swift.Decodable"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKZendeskUser","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKZendeskUser"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskUser","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKZendeskUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title"},{"value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskUser"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/navigatorTitle"}]}]}