{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ZendeskSDK"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationAgentAssigned(py)timestamp","symbolKind":"property","roleHeading":"Instance Property","title":"timestamp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationagentassigned\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/timestamp","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned/timestamp":{"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkconversationagentassigned\/timestamp","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned\/timestamp","title":"timestamp"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationAgentAssigned":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkconversationagentassigned","abstract":[],"kind":"symbol","role":"symbol","title":"ZDKConversationAgentAssigned","type":"topic","navigatorTitle":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationAgentAssigned"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"timestamp","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timestamp"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"timestamp","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1timestamp\/title"},{"op":"replace","value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned~1timestamp\/fragments"},{"op":"replace","value":"ZDKConversationAgentAssigned","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationAgentAssigned"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/fragments"},{"op":"replace","value":[{"text":"ZDKConversationAgentAssigned","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationAgentAssigned\/navigatorTitle"}]}]}