{"metadata":{"modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","externalID":"s:10ZendeskSDK0A0C10initialize14withChannelKey16messagingFactory17completionHandlerySS_AA09MessagingH0_pSgys6ResultOyACs5Error_pGctFZ","title":"initialize(withChannelKey:messagingFactory:completionHandler:)","roleHeading":"Type Method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Initializes ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":" for the given ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"text":". A ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"},{"text":" can be optionally passed here","type":"text"},{"text":" ","type":"text"},{"text":"to add the ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"code":"completionHandler","type":"codeVoice"},{"text":" with the result.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withChannelKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"channelKey","content":[{"type":"paragraph","inlineContent":[{"text":"The key of your Messaging iOS channel","type":"text"}]}]},{"name":"messagingFactory","content":[{"type":"paragraph","inlineContent":[{"text":"Optional parameter to include the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" capability, pass an initialized ","type":"text"},{"type":"codeVoice","code":"DefaultMessagingFactory"},{"text":" here.","type":"text"}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"text":"A block that takes a ","type":"text"},{"type":"codeVoice","code":"Result"},{"text":" enum type. In the case of a success, a ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"text":" ","type":"text"},{"text":"instance will be returned, in the case of a failure an ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" type.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"aside","name":"Attention","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method must complete successfully before "},{"code":"Zendesk.instance","type":"codeVoice"},{"type":"text","text":" can be called."},{"type":"text","text":" "},{"type":"text","text":"After a successful call has been made, calling it again with the same "},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":" will succeed immediately"},{"type":"text","text":" "},{"type":"text","text":"without performing a network call."}]}]}]}],"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:completionHandler:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:completionHandler:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Initializes ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"text":" for the given ","type":"text"},{"type":"codeVoice","code":"channelKey"},{"text":". A ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"},{"text":" can be optionally passed here","type":"text"},{"text":" ","type":"text"},{"text":"to add the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"type":"codeVoice","code":"completionHandler"},{"text":" with the result.","type":"text"}],"type":"topic","title":"initialize(withChannelKey:messagingFactory:completionHandler:)","kind":"symbol","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:completionhandler:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","title":"Zendesk","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"url":"\/documentation\/zendesksdk\/zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"url":"\/documentation\/zendesksdk\/messagingfactory","abstract":[],"title":"MessagingFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"text":"MessagingFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/navigatorTitle","value":[{"text":"MessagingFactory","kind":"identifier"}],"op":"replace"}]}]}