{"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(channelkey:messagingfactory:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(channelkey:messagingfactory:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"channelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"externalID":"c:@CM@ZendeskSDK@objc(cs)Zendesk(cm)initializeWithChannelKey:messagingFactory:completionHandler:","platforms":[],"extendedModule":"ZendeskSDK","title":"initialize(channelKey:messagingFactory:completionHandler:)","symbolKind":"method","navigatorTitle":[{"text":"initializeWithChannelKey:messagingFactory:completionHandler:","kind":"identifier"}],"roleHeading":"Type Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(channelKey:messagingFactory:completionHandler:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"type":"codeVoice","code":"channelKey"},{"type":"text","text":". A "},{"type":"codeVoice","code":"MessagingFactory"},{"type":"text","text":" can be optionally passed here"},{"type":"text","text":" "},{"type":"text","text":"to add the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"channelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The key of your Messaging iOS channel","type":"text"}]}],"name":"channelKey"},{"content":[{"inlineContent":[{"text":"Optional parameter to include the ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":" capability, pass an initialized ","type":"text"},{"code":"DefaultMessagingFactory","type":"codeVoice"},{"text":" here.","type":"text"}],"type":"paragraph"}],"name":"messagingFactory"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block that takes  an optional ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":" ","type":"text"},{"text":"instance which will be non-nil in the case of a success and an optional ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" which will be non-nil in the case of a failure.","type":"text"}]}],"name":"completionHandler"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This method must complete successfully before ","type":"text"},{"code":"Zendesk.instance","type":"codeVoice"},{"text":" can be called.","type":"text"},{"text":" ","type":"text"},{"text":"After a successful call has been made, calling it again with the same ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"text":" will succeed immediately","type":"text"},{"text":" ","type":"text"},{"text":"without performing a network call.","type":"text"}]}],"name":"Attention"}],"kind":"content"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","title":"Zendesk","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"url":"\/documentation\/zendesksdk\/zendesk","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(channelKey:messagingFactory:completionHandler:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Initializes ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"text":" for the given ","type":"text"},{"type":"codeVoice","code":"channelKey"},{"text":". A ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"},{"text":" can be optionally passed here","type":"text"},{"text":" ","type":"text"},{"text":"to add the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"text":"that retrieves settings from the network that calls the ","type":"text"},{"type":"codeVoice","code":"completionHandler"},{"text":" with the result.","type":"text"}],"title":"initialize(channelKey:messagingFactory:completionHandler:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(channelkey:messagingfactory:completionhandler:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"channelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","text":"MessagingFactory","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initializeWithChannelKey:messagingFactory:completionHandler:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(channelKey:messagingFactory:completionHandler:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"url":"\/documentation\/zendesksdk\/messagingfactory","abstract":[],"title":"MessagingFactory"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initializeWithChannelKey:messagingFactory:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithChannelKey:messagingFactory:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initializeWithChannelKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"channelKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"messagingFactory:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MessagingFactory>","preciseIdentifier":"c:Qo@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"messagingFactory","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The key of your Messaging iOS channel","type":"text"}],"type":"paragraph"}],"name":"channelKey"},{"content":[{"inlineContent":[{"type":"text","text":"Optional parameter to include the "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" capability, pass an initialized "},{"code":"DefaultMessagingFactory","type":"codeVoice"},{"type":"text","text":" here."}],"type":"paragraph"}],"name":"messagingFactory"},{"content":[{"inlineContent":[{"text":"A block that takes  an optional ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":" ","type":"text"},{"text":"instance which will be non-nil in the case of a success and an optional ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" which will be non-nil in the case of a failure.","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"Zendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"kind":"identifier","text":"Zendesk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1initialize(channelKey:messagingFactory:completionHandler:)\/title","value":"initializeWithChannelKey:messagingFactory:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1initialize(channelKey:messagingFactory:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithChannelKey:messagingFactory:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"kind":"identifier","text":"MessagingFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/navigatorTitle","value":[{"text":"MessagingFactory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}