{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"channelKey","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","kind":"typeIdentifier","text":"MessagingFactory"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"messagingSwiftUIFactory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory","kind":"typeIdentifier","text":"MessagingSwiftUIFactory"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","kind":"typeIdentifier","text":"Zendesk"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"channelKey","content":[{"inlineContent":[{"text":"The key of your Messaging iOS channel","type":"text"}],"type":"paragraph"}]},{"name":"messagingFactory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional parameter to include the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" UIKit capability, pass an initialized "},{"type":"codeVoice","code":"DefaultMessagingFactory"},{"type":"text","text":" here."}]}]},{"name":"messagingSwiftUIFactory","content":[{"inlineContent":[{"text":"Optional parameter to include the ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" SwiftUI capability,","type":"text"},{"text":" ","type":"text"},{"text":"pass an initialized ","type":"text"},{"type":"codeVoice","code":"DefaultMessagingSwiftUIFactory"},{"text":" here.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This method must complete successfully before ","type":"text"},{"code":"Zendesk.instance","type":"codeVoice"},{"text":" can be called.","type":"text"},{"text":" ","type":"text"},{"text":"After a successful call has been made, calling it again with the same ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"text":" will succeed immediately","type":"text"},{"text":" ","type":"text"},{"text":"without performing a network call.","type":"text"}]}],"style":"note","type":"aside","name":"Attention"}]}],"abstract":[{"type":"text","text":"Initializes "},{"code":"Zendesk","type":"codeVoice"},{"type":"text","text":" for the given "},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":". A "},{"code":"MessagingFactory","type":"codeVoice"},{"type":"text","text":" for UIKit or "},{"code":"MessagingSwiftUIFactory","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"for SwiftUI can be optionally passed here to add the "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"code":"completionHandler","type":"codeVoice"},{"type":"text","text":" with the result."}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","extendedModule":"ZendeskSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"text":"?, ","kind":"text"},{"text":"messagingSwiftUIFactory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingSwiftUIFactory","kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","unavailable":false}],"title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","externalID":"s:10ZendeskSDK0A0C10initialize14withChannelKey16messagingFactory0G14SwiftUIFactoryACSS_AA09MessagingH0_pSgAA0kiJ0_pSgtYaKFZ"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingFactory","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","navigatorTitle":[{"text":"MessagingFactory","kind":"identifier"}],"title":"MessagingFactory","type":"topic","url":"\/documentation\/zendesksdk\/messagingfactory","abstract":[],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"title":"Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdk\/zendesk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withChannelKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messagingSwiftUIFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingSwiftUIFactory","preciseIdentifier":"s:10ZendeskSDK23MessagingSwiftUIFactoryP"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"}],"title":"initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","abstract":[{"type":"text","text":"Initializes "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"type":"codeVoice","code":"channelKey"},{"type":"text","text":". A "},{"type":"codeVoice","code":"MessagingFactory"},{"type":"text","text":" for UIKit or "},{"type":"codeVoice","code":"MessagingSwiftUIFactory"},{"type":"text","text":" "},{"type":"text","text":"for SwiftUI can be optionally passed here to add the "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" capability. This method is an asynchronous call"},{"type":"text","text":" "},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:messagingSwiftUIFactory:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:messagingswiftuifactory:)"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIFactory":{"abstract":[],"title":"MessagingSwiftUIFactory","url":"\/documentation\/zendesksdk\/messagingswiftuifactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIFactory","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSwiftUIFactory","kind":"identifier"}],"navigatorTitle":[{"text":"MessagingSwiftUIFactory","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","value":"MessagingFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"text":"MessagingFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/navigatorTitle","value":[{"text":"MessagingFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"kind":"identifier","text":"Zendesk"}]}]}]}