{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/init(conversationId:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/zendesksdk\/conversationagentassigneddetails\/init(conversationid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails"]]},"metadata":{"roleHeading":"Initializer","externalID":"s:10ZendeskSDK32ConversationAgentAssignedDetailsC14conversationIdACSS_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ZendeskSDK"}],"role":"symbol","symbolKind":"init","title":"init(conversationId:)"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails/init(conversationId:)":{"abstract":[],"title":"init(conversationId:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails\/init(conversationId:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails\/init(conversationid:)","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationAgentAssignedDetails":{"abstract":[],"title":"ConversationAgentAssignedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationAgentAssignedDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationAgentAssignedDetails","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk\/conversationagentassigneddetails","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/title","value":"ZDKConversationAgentAssignedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKConversationAgentAssignedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationAgentAssignedDetails\/navigatorTitle","value":[{"text":"ZDKConversationAgentAssignedDetails","kind":"identifier"}]}]}]}