{"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationstarted\/conversationid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationstarted\/conversationid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/conversationId","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"modules":[{"name":"ZendeskSDK"}],"title":"conversationId","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationStarted(py)conversationId","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted/conversationId":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"conversationId","url":"\/documentation\/zendesksdk\/zdkconversationstarted\/conversationid","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted\/conversationId","role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/zendesksdk","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationStarted":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationStarted"}],"navigatorTitle":[{"text":"ZDKConversationStarted","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"ZDKConversationStarted","url":"\/documentation\/zendesksdk\/zdkconversationstarted","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationStarted","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"conversationId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"conversationId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"conversationId","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1conversationId\/title","value":"conversationId"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/title","value":"ZDKConversationStarted"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationStarted\/fragments","op":"replace","value":[{"text":"ZDKConversationStarted","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}