{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/conversationservedbyagentdetails\/init(agentdisplayname:agentid:agentmessagesource:conversationid:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"agentDisplayName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"agentId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"agentMessageSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@AgentMessageSource","text":"AgentMessageSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"s:10ZendeskSDK32ConversationServedByAgentDetailsC16agentDisplayName0H2Id0H13MessageSource012conversationK0ACSS_SSAA0flM0OSStcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"agentDisplayName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"agentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"agentMessageSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgentMessageSource","preciseIdentifier":"c:@M@ZendeskSDK@E@AgentMessageSource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(agentDisplayName:agentId:agentMessageSource:conversationId:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/init(agentDisplayName:agentId:agentMessageSource:conversationId:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/AgentMessageSource":{"title":"AgentMessageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentMessageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum defining sources or platforms where an agent’s message originates."}],"navigatorTitle":[{"text":"AgentMessageSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/agentmessagesource","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/AgentMessageSource"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationServedByAgentDetails"}],"title":"ConversationServedByAgentDetails","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServedByAgentDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationServedByAgentDetails/init(agentDisplayName:agentId:agentMessageSource:conversationId:)":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationServedByAgentDetails\/init(agentDisplayName:agentId:agentMessageSource:conversationId:)","role":"symbol","title":"init(agentDisplayName:agentId:agentMessageSource:conversationId:)","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/conversationservedbyagentdetails\/init(agentdisplayname:agentid:agentmessagesource:conversationid:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agentDisplayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"agentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"agentMessageSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgentMessageSource","preciseIdentifier":"c:@M@ZendeskSDK@E@AgentMessageSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/title","value":"AgentMessageSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/fragments","value":[{"kind":"identifier","text":"AgentMessageSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1AgentMessageSource\/navigatorTitle","value":[{"kind":"identifier","text":"AgentMessageSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/title","value":"ZDKConversationServedByAgentDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/fragments","value":[{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationServedByAgentDetails\/navigatorTitle","value":[{"text":"ZDKConversationServedByAgentDetails","kind":"identifier"}],"op":"replace"}]}]}