{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/timestamp"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessagesShown(py)timestamp","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"timestamp"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkmessagesshown\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkmessagesshown\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown/timestamp":{"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"title":"timestamp","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown\/timestamp","abstract":[],"url":"\/documentation\/zendesksdk\/zdkmessagesshown\/timestamp","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKMessagesShown":{"url":"\/documentation\/zendesksdk\/zdkmessagesshown","abstract":[],"navigatorTitle":[{"text":"ZDKMessagesShown","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKMessagesShown","title":"ZDKMessagesShown","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessagesShown","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","url":"\/documentation\/zendesksdk","abstract":[],"type":"topic","title":"ZendeskSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timestamp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"timestamp","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/title","value":"ZDKMessagesShown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/fragments","value":[{"kind":"identifier","text":"ZDKMessagesShown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKMessagesShown\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessagesShown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}