{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logoutUser","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A block that takes an optional "},{"code":"Error","type":"codeVoice"},{"text":" which will be non-nil in the case of a failure.","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/logoutuser(completionhandler:)-55qal"]},{"paths":["\/documentation\/zendesksdk\/zendesk\/logoutuser(completionhandler:)-55qal"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Unauthenticate a user."}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-55qal","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"logoutUserWithCompletionHandler:"}],"role":"symbol","externalID":"c:@CM@ZendeskSDK@objc(cs)Zendesk(im)logoutUserWithCompletionHandler:","platforms":[],"extendedModule":"ZendeskSDK","title":"logoutUser(completionHandler:)","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logoutUser","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"title":"Zendesk","type":"topic","url":"\/documentation\/zendesksdk\/zendesk"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","role":"collection","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/logoutUser(completionHandler:)-55qal":{"url":"\/documentation\/zendesksdk\/zendesk\/logoutuser(completionhandler:)-55qal","abstract":[{"type":"text","text":"Unauthenticate a user."}],"role":"symbol","kind":"symbol","type":"topic","title":"logoutUser(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"logoutUserWithCompletionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logoutUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/logoutUser(completionHandler:)-55qal"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"logoutUserWithCompletionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logoutUserWithCompletionHandler:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"logoutUserWithCompletionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"text":"Zendesk","kind":"identifier"}]},{"value":"logoutUserWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1logoutUser(completionHandler:)-55qal\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk~1logoutUser(completionHandler:)-55qal\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logoutUserWithCompletionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}