{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/articleClicked","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleClicked"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"metadata":{"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventArticleClicked","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventArticleClicked"}],"symbolKind":"case","title":"ZDKZendeskEvent.articleClicked","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleClicked","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}]},"abstract":[{"type":"text","text":"Invoked when an end-user clicks on an article."}],"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/articleclicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/articleclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/articleClicked":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/articleClicked","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskEventArticleClicked","kind":"identifier"}],"title":"ZDKZendeskEvent.articleClicked","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleClicked","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent\/articleclicked","abstract":[{"text":"Invoked when an end-user clicks on an article.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"title":"ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskEventArticleClicked","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventArticleClicked"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKZendeskEventArticleClicked"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKZendeskEventArticleClicked","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1articleClicked\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventArticleClicked"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1articleClicked\/fragments"},{"op":"replace","value":"ZDKZendeskEvent","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}