{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationExtensionOpened","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensionopened"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensionopened"]}],"metadata":{"roleHeading":"Case","modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","role":"symbol","title":"ZDKZendeskEvent.conversationExtensionOpened","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventConversationExtensionOpened","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationExtensionOpened"}],"navigatorTitle":[{"text":"ZDKZendeskEventConversationExtensionOpened","kind":"identifier"}]},"abstract":[{"text":"Invoked when a conversation extension is opened by an end-user.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationExtensionOpened"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"title":"ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/conversationExtensionOpened":{"abstract":[{"type":"text","text":"Invoked when a conversation extension is opened by an end-user."}],"title":"ZDKZendeskEvent.conversationExtensionOpened","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/conversationextensionopened","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/conversationExtensionOpened","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationExtensionOpened"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionOpened"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKZendeskEventConversationExtensionOpened","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionOpened"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"ZDKZendeskEventConversationExtensionOpened","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKZendeskEvent","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"},{"op":"replace","value":"ZDKZendeskEventConversationExtensionOpened","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationExtensionOpened\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskEventConversationExtensionOpened"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1conversationExtensionOpened\/fragments"}]}]}