{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationButtonClicked"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventNewConversationButtonClicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationButtonClicked"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ZDKZendeskEventNewConversationButtonClicked","kind":"identifier"}],"title":"ZDKZendeskEvent.newConversationButtonClicked","symbolKind":"case"},"abstract":[{"text":"Invoked when the new conversation button is clicked by the end-user.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/newConversationButtonClicked","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/newconversationbuttonclicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/newconversationbuttonclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"abstract":[{"type":"text","text":"The set of events that can be emitted from Zendesk SDK."}],"title":"ZDKZendeskEvent","url":"\/documentation\/zendesksdk\/zdkzendeskevent","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEvent"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKZendeskEvent"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/newConversationButtonClicked":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/newConversationButtonClicked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"newConversationButtonClicked"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventNewConversationButtonClicked"}],"title":"ZDKZendeskEvent.newConversationButtonClicked","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/newconversationbuttonclicked","abstract":[{"type":"text","text":"Invoked when the new conversation button is clicked by the end-user."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEventNewConversationButtonClicked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventNewConversationButtonClicked"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKZendeskEventNewConversationButtonClicked"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title","value":"ZDKZendeskEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1newConversationButtonClicked\/title","value":"ZDKZendeskEventNewConversationButtonClicked"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1newConversationButtonClicked\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventNewConversationButtonClicked"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}