{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","text":"PostbackButtonClickedDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/data","interfaceLanguage":"swift"},"metadata":{"title":"data","role":"symbol","modules":[{"name":"ZendeskSDK"}],"navigatorTitle":[{"text":"data","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClicked(py)data","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PostbackButtonClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails","kind":"typeIdentifier"}]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/PostbackButtonClickedDetails":{"title":"PostbackButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"navigatorTitle":[{"text":"PostbackButtonClickedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdk\/postbackbuttonclickeddetails","abstract":[{"text":"Details of a postback button that was clicked by the end user.","type":"text"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked":{"navigatorTitle":[{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"title":"ZDKPostbackButtonClicked","url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKPostbackButtonClicked/data":{"role":"symbol","url":"\/documentation\/zendesksdk\/zdkpostbackbuttonclicked\/data","title":"data","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKPostbackButtonClicked\/data","navigatorTitle":[{"text":"data","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PostbackButtonClickedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"data","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"data"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKPostbackButtonClickedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/PostbackButtonClickedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKPostbackButtonClickedDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKPostbackButtonClickedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/title","op":"replace"},{"value":[{"text":"ZDKPostbackButtonClickedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKPostbackButtonClickedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1PostbackButtonClickedDetails\/navigatorTitle","op":"replace"},{"value":"ZDKPostbackButtonClicked","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/title","op":"replace"},{"value":[{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/fragments","op":"replace"},{"value":[{"text":"ZDKPostbackButtonClicked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked\/navigatorTitle","op":"replace"},{"value":"data","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1data\/title","op":"replace"},{"value":[{"kind":"identifier","text":"data"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKPostbackButtonClicked~1data\/fragments","op":"replace"}]}]}