{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"sections":[],"kind":"symbol","defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl"],"anchor":"MessagingSwiftUIDelegate-Implementations","title":"MessagingSwiftUIDelegate Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messaging","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldHandleURL","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"source","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLSource","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"messaging","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"MessagingSwiftUI","type":"codeVoice"},{"text":" instance","type":"text"}]}]},{"name":"url","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" the user actioned.","type":"text"}],"type":"paragraph"}]},{"name":"source","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" from which the user actioned the URL from.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if MessagingSwiftUI should handle the URL. Return "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if there is a specified URL flow."}]}],"kind":"content"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when there is no way to handle a specific URL and ","type":"text"},{"code":"MessagingSwiftUI","type":"codeVoice"},{"text":" will perform OS default behaviour of opening","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" in the default browser.","type":"text"}]}],"type":"aside"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)"]}],"metadata":{"externalID":"s:10ZendeskSDK24MessagingSwiftUIDelegateP9messaging_15shouldHandleURL4fromSbAA0cD2UIC_10Foundation0I0VAA9URLSourceOtF","role":"symbol","modules":[{"name":"ZendeskSDK"}],"title":"messaging(_:shouldHandleURL:from:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","text":"MessagingSwiftUI"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)":{"title":"messaging(_:shouldHandleURL:from:)","type":"topic","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)","kind":"symbol","required":true,"role":"symbol","defaultImplementations":1,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier","text":"MessagingSwiftUI"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate":{"abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate","title":"MessagingSwiftUIDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSwiftUIDelegate"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingSwiftUIDelegate"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"title":"URLSource","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLSource"}],"type":"topic","url":"\/documentation\/zendesksdk\/urlsource","role":"symbol","abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"URLSource"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUIDelegate/messaging(_:shouldHandleURL:from:)-4qszl":{"title":"messaging(_:shouldHandleURL:from:)","url":"\/documentation\/zendesksdk\/messagingswiftuidelegate\/messaging(_:shouldhandleurl:from:)-4qszl","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUIDelegate\/messaging(_:shouldHandleURL:from:)-4qszl","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10ZendeskSDK16MessagingSwiftUIC","kind":"typeIdentifier","text":"MessagingSwiftUI"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[],"role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSwiftUI":{"navigatorTitle":[{"kind":"identifier","text":"MessagingSwiftUI"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSwiftUI","role":"symbol","title":"MessagingSwiftUI","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingSwiftUI"}],"url":"\/documentation\/zendesksdk\/messagingswiftui","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/navigatorTitle","value":[{"text":"ZDKURLSource","kind":"identifier"}],"op":"replace"}]}]}