{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","text":"ConversationExtensionDisplayedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdk\/zdkconversationextensiondisplayed\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdkconversationextensiondisplayed\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionDisplayed\/data","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionDisplayed"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","kind":"typeIdentifier","text":"ConversationExtensionDisplayedDetails"}],"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayed(py)data","navigatorTitle":[{"kind":"identifier","text":"data"}],"title":"data","modules":[{"name":"ZendeskSDK"}],"symbolKind":"property"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionDisplayed":{"navigatorTitle":[{"text":"ZDKConversationExtensionDisplayed","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionDisplayed","url":"\/documentation\/zendesksdk\/zdkconversationextensiondisplayed","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationExtensionDisplayed","kind":"identifier"}],"title":"ZDKConversationExtensionDisplayed"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails":{"navigatorTitle":[{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","title":"ConversationExtensionDisplayedDetails","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Details of a conversation extension that was displayed to the end user."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKConversationExtensionDisplayed/data":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationExtensionDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdk\/zdkconversationextensiondisplayed\/data","abstract":[],"type":"topic","title":"data","kind":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKConversationExtensionDisplayed\/data","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","title":"ZendeskSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"data","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKConversationExtensionDisplayedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails"},{"text":" * ","kind":"text"},{"text":"data","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionDisplayed\/title","value":"ZDKConversationExtensionDisplayed","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionDisplayed\/fragments","value":[{"kind":"identifier","text":"ZDKConversationExtensionDisplayed"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionDisplayed\/navigatorTitle","value":[{"text":"ZDKConversationExtensionDisplayed","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/title","value":"ZDKConversationExtensionDisplayedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/fragments","value":[{"kind":"identifier","text":"ZDKConversationExtensionDisplayedDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/navigatorTitle","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionDisplayed~1data\/title","value":"data","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKConversationExtensionDisplayed~1data\/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"}]}]}