{"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-5q2jt","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ZendeskSDK@objc(pl)ZDKMessagingDelegate(im)messaging:shouldHandleURL:from:","role":"symbol","title":"messaging(_:shouldHandleURL:from:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"shouldHandleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"modules":[{"name":"ZendeskSDK"}],"symbolKind":"method"},"abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"Messaging"},{"kind":"text","text":", "},{"text":"shouldHandleURL","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"source","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","text":"URLSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"kind":"parameters","parameters":[{"name":"messaging","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" instance"}]}]},{"name":"url","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"URL","type":"codeVoice"},{"type":"text","text":" the user actioned."}]}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"source","type":"codeVoice"},{"type":"text","text":" from which the user actioned the URL from."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"code":"true","type":"codeVoice"},{"text":" if Messaging should handle the URL. Return ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" if there is a specified URL flow."}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"true"},{"text":" when there is no way to handle a specific URL and ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" will perform OS default behaviour of opening","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"codeVoice","code":"URL"},{"text":" in the default browser.","type":"text"}]}],"type":"aside","style":"note"}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18"],"title":"MessagingDelegate Implementations"}],"variants":[{"paths":["\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-5q2jt"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-5q2jt"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/zendesksdk\/messaging","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","title":"Messaging","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate":{"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessagingDelegate","kind":"identifier"}],"type":"topic","title":"MessagingDelegate","url":"\/documentation\/zendesksdk\/messagingdelegate","role":"symbol","abstract":[{"type":"text","text":"Delegate to receive callbacks from the SDK."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"role":"symbol","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/urlsource","abstract":[{"text":"An enum representing the source of actioned ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","title":"URLSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLSource","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)-5q2jt":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"messaging:shouldHandleURL:from:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"},{"kind":"text","text":", "},{"text":"shouldHandleURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","kind":"typeIdentifier","text":"URLSource"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"defaultImplementations":1,"type":"topic","title":"messaging(_:shouldHandleURL:from:)","url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-5q2jt","role":"symbol","abstract":[{"type":"text","text":"Optional delegate that allows custom URL link handling."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-5q2jt"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","role":"collection","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingDelegate/messaging(_:shouldHandleURL:from:)-97e18":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messaging"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"Messaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandleURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource","text":"URLSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/zendesksdk\/messagingdelegate\/messaging(_:shouldhandleurl:from:)-97e18","abstract":[{"text":"Optional delegate that allows custom URL link handling.","type":"text"}],"kind":"symbol","type":"topic","title":"messaging(_:shouldHandleURL:from:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingDelegate\/messaging(_:shouldHandleURL:from:)-97e18","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"messaging:shouldHandleURL:from:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messaging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","text":"ZDKMessaging","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messaging"},{"text":" ","kind":"text"},{"text":"shouldHandleURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","text":"ZDKURLSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKURLSource"},{"kind":"text","text":") "},{"kind":"internalParam","text":"source"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace","value":"ZDKMessaging"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments"},{"value":"ZDKMessagingDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","value":"ZDKURLSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments","value":[{"text":"ZDKURLSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)-5q2jt\/title","op":"replace","value":"messaging:shouldHandleURL:from:"},{"value":[{"text":"- ","kind":"text"},{"text":"messaging:shouldHandleURL:from:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingDelegate~1messaging(_:shouldHandleURL:from:)-5q2jt\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}