{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messagingfactoryparameters"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKMessagingFactoryParameters) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactoryParameters"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The set of parameters to be provided to Messaging(SwiftUI)Factory "},{"type":"codeVoice","code":"createMessaging"},{"text":" to create an instance of ","type":"text"},{"type":"codeVoice","code":"Messaging(SwiftUI)"},{"text":".","type":"text"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject","doc:\/\/com.zendesk.Zendesk\/s7CVarArgP","doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Zendesk\/SQ","doc:\/\/com.zendesk.Zendesk\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"modules":[{"name":"ZendeskSDK"}],"symbolKind":"class","role":"symbol","title":"MessagingFactoryParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingFactoryParameters","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","navigatorTitle":[{"kind":"identifier","text":"MessagingFactoryParameters"}]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/conversationKit","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/dispatchEvent","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/messagingSettings","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/theme"],"title":"Instance Properties"}],"references":{"doc://com.zendesk.Zendesk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.Zendesk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(pl)NSObject"},"doc://com.zendesk.Zendesk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.Zendesk\/s23CustomStringConvertibleP"},"doc://com.zendesk.Zendesk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Zendesk\/SH"},"doc://com.zendesk.Zendesk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","role":"collection","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.Zendesk\/s7CVarArgP"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/conversationKit":{"role":"symbol","title":"conversationKit","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/conversationKit","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationKit","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConversationKit","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC0P","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/conversationkit","kind":"symbol","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/theme":{"url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/theme","title":"theme","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"theme","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ZendeskSDK10ColorThemeV","text":"ColorTheme","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/theme","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters","title":"MessagingFactoryParameters","url":"\/documentation\/zendesksdk\/messagingfactoryparameters","abstract":[{"text":"The set of parameters to be provided to Messaging(SwiftUI)Factory ","type":"text"},{"code":"createMessaging","type":"codeVoice"},{"text":" to create an instance of ","type":"text"},{"code":"Messaging(SwiftUI)","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"MessagingFactoryParameters"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagingFactoryParameters","kind":"identifier"}]},"doc://com.zendesk.Zendesk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Zendesk\/SQ"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/dispatchEvent":{"title":"dispatchEvent","url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/dispatchevent","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/dispatchEvent","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispatchEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DispatchEvent","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKDispatchEvent"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactoryParameters/messagingSettings":{"role":"symbol","title":"messagingSettings","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdk\/messagingfactoryparameters\/messagingsettings","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactoryParameters\/messagingSettings","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingSettings","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingSettings","text":"MessagingSettings"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"ZDKMessagingFactoryParameters","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingFactoryParameters"}]},{"value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Zendesk\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKMessagingFactoryParameters"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/title","value":"ZDKMessagingFactoryParameters"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactoryParameters\/fragments","value":[{"text":"ZDKMessagingFactoryParameters","kind":"identifier"}],"op":"replace"}]}]}