{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/conversationwithagentrequesteddetails\/init(conversationid:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/init(conversationId:)"},"kind":"symbol","metadata":{"title":"init(conversationId:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"s:10ZendeskSDK37ConversationWithAgentRequestedDetailsC14conversationIdACSS_tcfc","symbolKind":"init","modules":[{"name":"ZendeskSDK"}],"role":"symbol"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails/init(conversationId:)":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails\/init(conversationid:)","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails\/init(conversationId:)","kind":"symbol","role":"symbol","title":"init(conversationId:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationWithAgentRequestedDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationWithAgentRequestedDetails","navigatorTitle":[{"text":"ConversationWithAgentRequestedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationwithagentrequesteddetails","type":"topic","kind":"symbol","title":"ConversationWithAgentRequestedDetails","abstract":[{"type":"text","text":"Details of a conversation where an agent was requested."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/title","op":"replace","value":"ConversationWithAgentRequestedDetails"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationWithAgentRequestedDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationWithAgentRequestedDetails"}]}]}]}