{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationUnreadCountChanged(py)unreadCountInConversation","title":"unreadCountInConversation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadCountInConversation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"unreadCountInConversation","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/unreadCountInConversation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadCountInConversation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange\/unreadcountinconversation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationunreadcountchange\/unreadcountinconversation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange"]]},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange":{"type":"topic","title":"ConversationUnreadCountChange","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUnreadCountChange","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange","url":"\/documentation\/zendesksdk\/conversationunreadcountchange","kind":"symbol","navigatorTitle":[{"text":"ConversationUnreadCountChange","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationUnreadCountChange/unreadCountInConversation":{"navigatorTitle":[{"text":"unreadCountInConversation","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/conversationunreadcountchange\/unreadcountinconversation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadCountInConversation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationUnreadCountChange\/unreadCountInConversation","kind":"symbol","title":"unreadCountInConversation","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"unreadCountInConversation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"unreadCountInConversation","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"unreadCountInConversation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/title","value":"ZDKConversationUnreadCountChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/fragments","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange\/navigatorTitle","value":[{"text":"ZDKConversationUnreadCountChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1unreadCountInConversation\/title","value":"unreadCountInConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationUnreadCountChange~1unreadCountInConversation\/fragments","value":[{"text":"unreadCountInConversation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}