{"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"identifier","role":"symbol","modules":[{"name":"ZendeskSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"s:10ZendeskSDK17MessagingSettingsC10identifierSSvp"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings"]]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/identifier","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdk\/messagingsettings\/identifier"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings/identifier":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings\/identifier","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"identifier","url":"\/documentation\/zendesksdk\/messagingsettings\/identifier"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingSettings":{"url":"\/documentation\/zendesksdk\/messagingsettings","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingSettings","kind":"identifier"}],"abstract":[],"type":"topic","title":"MessagingSettings","navigatorTitle":[{"text":"MessagingSettings","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/title","value":"ZDKMessagingSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/fragments","value":[{"kind":"identifier","text":"ZDKMessagingSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingSettings\/navigatorTitle","value":[{"text":"ZDKMessagingSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}