{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messagingfactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messagingfactory"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"]]},"metadata":{"role":"symbol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}],"modules":[{"name":"ZendeskSDK"}],"title":"MessagingFactory","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"externalID":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory\/createMessaging(with:)"],"generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","type":"topic","url":"\/documentation\/zendesksdk","abstract":[],"title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingFactory"}],"url":"\/documentation\/zendesksdk\/messagingfactory","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","navigatorTitle":[{"kind":"identifier","text":"MessagingFactory"}],"kind":"symbol","abstract":[],"title":"MessagingFactory","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory/createMessaging(with:)":{"required":true,"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory\/createMessaging(with:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMessaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier","text":"MessagingFactoryParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"}],"navigatorTitle":[{"kind":"identifier","text":"createMessagingWith:"}],"url":"\/documentation\/zendesksdk\/messagingfactory\/createmessaging(with:)","title":"createMessaging(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MessagingFactory","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MessagingFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MessagingFactory"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory\/createMessaging(with:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingFactory","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MessagingFactory","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title"},{"value":[{"text":"MessagingFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments"},{"value":[{"text":"MessagingFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/navigatorTitle"},{"value":"createMessagingWith:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory~1createMessaging(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMessagingWith:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory~1createMessaging(with:)\/fragments"}]}]}