{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"User selected "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" from a "},{"code":"file","type":"codeVoice"},{"text":" message on the conversation screen.","type":"text"}],"metadata":{"symbolKind":"case","modules":[{"name":"ZendeskSDK"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"ZDKURLSourceFile","kind":"identifier"}],"externalID":"c:@M@ZendeskSDK@E@ZDKURLSource@ZDKURLSourceFile","title":"URLSource.file","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/file"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"file"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/urlsource\/file"]},{"paths":["\/documentation\/zendesksdk\/urlsource\/file"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource"]]},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource","type":"topic","title":"URLSource","navigatorTitle":[{"text":"URLSource","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/urlsource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLSource","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum representing the source of actioned "},{"type":"codeVoice","code":"URL"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/URLSource/file":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/URLSource\/file","type":"topic","title":"URLSource.file","navigatorTitle":[{"text":"ZDKURLSourceFile","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/urlsource\/file","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"}],"abstract":[{"type":"text","text":"User selected "},{"code":"URL","type":"codeVoice"},{"type":"text","text":" from a "},{"type":"codeVoice","code":"file"},{"text":" message on the conversation screen.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","title":"ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKURLSourceFile"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKURLSourceFile"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKURLSourceFile"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKURLSource","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKURLSource"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource\/fragments"},{"value":"ZDKURLSourceFile","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1file\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1URLSource~1file\/fragments","value":[{"text":"ZDKURLSourceFile","kind":"identifier"}],"op":"replace"}]}]}