{"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging(im)getUnreadMessageCount","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUnreadMessageCount"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"getUnreadMessageCount","kind":"identifier"}],"title":"getUnreadMessageCount()","roleHeading":"Instance Method","modules":[{"name":"ZendeskSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/messaging\/getunreadmessagecount()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/messaging\/getunreadmessagecount()"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getUnreadMessageCount","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/getUnreadMessageCount()"},"abstract":[{"text":"Returns the current total number of unread messages.","type":"text"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging":{"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging","url":"\/documentation\/zendesksdk\/messaging","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Messaging","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"role":"symbol","title":"Messaging","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Messaging/getUnreadMessageCount()":{"title":"getUnreadMessageCount()","url":"\/documentation\/zendesksdk\/messaging\/getunreadmessagecount()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUnreadMessageCount"}],"abstract":[{"text":"Returns the current total number of unread messages.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Messaging\/getUnreadMessageCount()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUnreadMessageCount"},{"kind":"text","text":"() -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getUnreadMessageCount","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getUnreadMessageCount"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"getUnreadMessageCount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/title","op":"replace","value":"ZDKMessaging"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging\/fragments","value":[{"text":"ZDKMessaging","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"getUnreadMessageCount","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1getUnreadMessageCount()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Messaging~1getUnreadMessageCount()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUnreadMessageCount"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}