{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"сonversationUnreadMessageCountChanged"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"ZendeskSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"сonversationUnreadMessageCountChanged"}],"title":"ZDKZendeskEvent.сonversationUnreadMessageCountChanged","externalID":"c:@M@ZendeskSDK@E@ZDKZendeskEvent@ZDKZendeskEventсonversationUnreadMessageCountChanged","navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventсonversationUnreadMessageCountChanged"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/_onversationUnreadMessageCountChanged"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/_onversationunreadmessagecountchanged"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zdkzendeskevent\/_onversationunreadmessagecountchanged"]}],"abstract":[{"text":"Invoked when the number of unread messages has changed","type":"text"}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent/_onversationUnreadMessageCountChanged":{"navigatorTitle":[{"kind":"identifier","text":"ZDKZendeskEventсonversationUnreadMessageCountChanged"}],"abstract":[{"text":"Invoked when the number of unread messages has changed","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"сonversationUnreadMessageCountChanged"}],"title":"ZDKZendeskEvent.сonversationUnreadMessageCountChanged","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent\/_onversationUnreadMessageCountChanged","kind":"symbol","url":"\/documentation\/zendesksdk\/zdkzendeskevent\/_onversationunreadmessagecountchanged","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","abstract":[],"title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKZendeskEvent":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKZendeskEvent","abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"type":"topic","role":"symbol","title":"ZDKZendeskEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKZendeskEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zdkzendeskevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKZendeskEventсonversationUnreadMessageCountChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKZendeskEventсonversationUnreadMessageCountChanged"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKZendeskEventсonversationUnreadMessageCountChanged","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1_onversationUnreadMessageCountChanged\/title","value":"ZDKZendeskEventсonversationUnreadMessageCountChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent~1_onversationUnreadMessageCountChanged\/fragments","value":[{"text":"ZDKZendeskEventсonversationUnreadMessageCountChanged","kind":"identifier"}]},{"op":"replace","value":"ZDKZendeskEvent","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/title"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/fragments"},{"op":"replace","value":[{"text":"ZDKZendeskEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKZendeskEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}