{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationOpened"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationOpenedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpenedDetails","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdk\/zdknotificationopened\/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/zdknotificationopened\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpened(py)data","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationOpenedDetails","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpenedDetails","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"data"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"title":"data","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationOpened\/data"},"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKNotificationOpened/data":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationOpened\/data","url":"\/documentation\/zendesksdk\/zdknotificationopened\/data","title":"data","navigatorTitle":[{"text":"data","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationOpenedDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpenedDetails"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationOpenedDetails":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails","title":"NotificationOpenedDetails","navigatorTitle":[{"text":"NotificationOpenedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/notificationopeneddetails","role":"symbol","abstract":[{"type":"text","text":"Details of a notification that was opened by the end user."}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationOpenedDetails","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"url":"\/documentation\/zendesksdk","kind":"symbol","title":"ZendeskSDK","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","role":"collection","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZDKNotificationOpened":{"url":"\/documentation\/zendesksdk\/zdknotificationopened","kind":"symbol","navigatorTitle":[{"text":"ZDKNotificationOpened","kind":"identifier"}],"role":"symbol","title":"ZDKNotificationOpened","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNotificationOpened","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZDKNotificationOpened"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"data"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"data","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKNotificationOpenedDetails","text":"ZDKNotificationOpenedDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationOpenedDetails"},{"text":" * ","kind":"text"},{"text":"data","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationOpened~1data\/title","op":"replace","value":"data"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationOpened~1data\/fragments","op":"replace","value":[{"kind":"identifier","text":"data"}]},{"value":"ZDKNotificationOpenedDetails","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/title","op":"replace"},{"value":[{"text":"ZDKNotificationOpenedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKNotificationOpenedDetails"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationOpenedDetails\/navigatorTitle","op":"replace"},{"value":"ZDKNotificationOpened","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationOpened\/title","op":"replace"},{"value":[{"text":"ZDKNotificationOpened","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationOpened\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKNotificationOpened"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZDKNotificationOpened\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}