{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"The URL of the conversation extension","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails"]]},"sections":[],"variants":[{"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/url"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"title":"url","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKConversationExtensionDisplayedDetails(py)url","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"url","kind":"identifier"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/url","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails/url":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails\/url","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails\/url","type":"topic","abstract":[{"type":"text","text":"The URL of the conversation extension"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"url"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ConversationExtensionDisplayedDetails":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ConversationExtensionDisplayedDetails","url":"\/documentation\/zendesksdk\/conversationextensiondisplayeddetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationExtensionDisplayedDetails"}],"title":"ConversationExtensionDisplayedDetails","navigatorTitle":[{"kind":"identifier","text":"ConversationExtensionDisplayedDetails"}],"type":"topic","abstract":[{"type":"text","text":"Details of a conversation extension that was displayed to the end user."}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/zendesksdk","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","title":"ZendeskSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"url"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"url","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"url"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1url\/title","op":"replace","value":"url"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails~1url\/fragments","op":"replace","value":[{"kind":"identifier","text":"url"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/title","op":"replace","value":"ZDKConversationExtensionDisplayedDetails"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/fragments","op":"replace","value":[{"text":"ZDKConversationExtensionDisplayedDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ConversationExtensionDisplayedDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationExtensionDisplayedDetails"}]}]}]}