{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/connectionStatusChanged(connectionStatus:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","text":"ZendeskConnectionStatus","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new "},{"type":"codeVoice","code":"ConnectionStatus"}]}],"name":"connectionStatus"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The SDK "},{"type":"codeVoice","code":"ConnectionStatus"},{"type":"text","text":" has changed due to an action or another event."}],"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","text":"ZendeskConnectionStatus"},{"kind":"text","text":")"}],"modules":[{"name":"ZendeskSDK"}],"role":"symbol","title":"ZendeskEvent.connectionStatusChanged(connectionStatus:)","externalID":"s:10ZendeskSDK0A5EventO23connectionStatusChangedyAcA0a10ConnectionE0O_tcACmF"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskevent\/connectionstatuschanged(connectionstatus:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent/connectionStatusChanged(connectionStatus:)":{"abstract":[{"type":"text","text":"The SDK "},{"type":"codeVoice","code":"ConnectionStatus"},{"type":"text","text":" has changed due to an action or another event."}],"type":"topic","title":"ZendeskEvent.connectionStatusChanged(connectionStatus:)","role":"symbol","url":"\/documentation\/zendesksdk\/zendeskevent\/connectionstatuschanged(connectionstatus:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@E@ZDKZendeskConnectionStatus","text":"ZendeskConnectionStatus"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent\/connectionStatusChanged(connectionStatus:)","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskEvent":{"url":"\/documentation\/zendesksdk\/zendeskevent","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskEvent","title":"ZendeskEvent","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskEvent","kind":"identifier"}],"abstract":[{"text":"The set of events that can be emitted from Zendesk SDK.","type":"text"}],"navigatorTitle":[{"text":"ZendeskEvent","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskConnectionStatus":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskConnectionStatus","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskConnectionStatus","kind":"identifier"}],"title":"ZendeskConnectionStatus","navigatorTitle":[{"text":"ZendeskConnectionStatus","kind":"identifier"}],"abstract":[{"text":"A representation of the current connection status of the SDK.","type":"text"}],"url":"\/documentation\/zendesksdk\/zendeskconnectionstatus","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKZendeskConnectionStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/title"},{"value":[{"text":"ZDKZendeskConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/fragments"},{"value":[{"kind":"identifier","text":"ZDKZendeskConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskConnectionStatus\/navigatorTitle"}]}]}