{"metadata":{"modules":[{"name":"ZendeskSDK"}],"title":"init(conversationId:messageReceivedTimestamp:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messageReceivedTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"s:10ZendeskSDK28NotificationDisplayedDetailsC14conversationId24messageReceivedTimestampACSS_Sdtcfc"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/init(conversationId:messageReceivedTimestamp:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageReceivedTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/notificationdisplayeddetails\/init(conversationid:messagereceivedtimestamp:)"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails/init(conversationId:messageReceivedTimestamp:)":{"title":"init(conversationId:messageReceivedTimestamp:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"messageReceivedTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails\/init(conversationId:messageReceivedTimestamp:)","type":"topic","url":"\/documentation\/zendesksdk\/notificationdisplayeddetails\/init(conversationid:messagereceivedtimestamp:)","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/NotificationDisplayedDetails":{"title":"NotificationDisplayedDetails","abstract":[{"type":"text","text":"Details of a notification that was displayed."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationDisplayedDetails","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/notificationdisplayeddetails","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/NotificationDisplayedDetails","navigatorTitle":[{"text":"NotificationDisplayedDetails","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/title","value":"ZDKNotificationDisplayedDetails","op":"replace"},{"value":[{"text":"ZDKNotificationDisplayedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/fragments"},{"value":[{"kind":"identifier","text":"ZDKNotificationDisplayedDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1NotificationDisplayedDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}