{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:)"},"abstract":[{"text":"Initializes ","type":"text"},{"code":"Zendesk","type":"codeVoice"},{"text":" for the given ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"text":". A ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"},{"type":"text","text":" can be optionally passed here"},{"text":" ","type":"text"},{"type":"text","text":"to add the "},{"code":"Messaging","type":"codeVoice"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"channelKey","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"messagingFactory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessagingFactory","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier"},{"text":"? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","text":"Zendesk","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"channelKey","content":[{"inlineContent":[{"text":"The key of your Messaging iOS channel","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional parameter to include the "},{"type":"codeVoice","code":"Messaging"},{"text":" capability, pass an initialized ","type":"text"},{"code":"DefaultMessagingFactory","type":"codeVoice"},{"text":" here.","type":"text"}]}],"name":"messagingFactory"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" instance will be returned."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"This method must complete successfully before "},{"type":"codeVoice","code":"Zendesk.instance"},{"type":"text","text":" can be called."},{"text":" ","type":"text"},{"text":"After a successful call has been made, calling it again with the same ","type":"text"},{"code":"channelKey","type":"codeVoice"},{"type":"text","text":" will succeed immediately"},{"type":"text","text":" "},{"type":"text","text":"without performing a network call."}],"type":"paragraph"}],"type":"aside","name":"Attention"},{"name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"This will throw an error of type ","type":"text"},{"type":"codeVoice","code":"Error"},{"type":"text","text":" in case of failure."}]}],"type":"aside","style":"note"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"metadata":{"extendedModule":"ZendeskSDK","platforms":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"method","modules":[{"name":"ZendeskSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withChannelKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messagingFactory"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory","kind":"typeIdentifier","text":"MessagingFactory"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk"}],"roleHeading":"Type Method","externalID":"s:10ZendeskSDK0A0C10initialize14withChannelKey16messagingFactoryACSS_AA09MessagingH0_pSgtYaKFZ","title":"initialize(withChannelKey:messagingFactory:)","role":"symbol"},"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/MessagingFactory":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/MessagingFactory","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MessagingFactory","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/messagingfactory","title":"MessagingFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessagingFactory","kind":"identifier"}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/initialize(withChannelKey:messagingFactory:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/initialize(withChannelKey:messagingFactory:)","url":"\/documentation\/zendesksdk\/zendesk\/initialize(withchannelkey:messagingfactory:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withChannelKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"messagingFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingFactory","preciseIdentifier":"c:@M@ZendeskSDK@objc(pl)MessagingFactory"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)Zendesk","text":"Zendesk","kind":"typeIdentifier"}],"type":"topic","title":"initialize(withChannelKey:messagingFactory:)","kind":"symbol","abstract":[{"text":"Initializes ","type":"text"},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" for the given "},{"type":"codeVoice","code":"channelKey"},{"text":". A ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"},{"type":"text","text":" can be optionally passed here"},{"type":"text","text":" "},{"type":"text","text":"to add the "},{"code":"Messaging","type":"codeVoice"},{"text":" capability. This method is an asynchronous call","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that retrieves settings from the network that calls the "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" with the result."}]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdk","title":"ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"title":"Zendesk","url":"\/documentation\/zendesksdk\/zendesk","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","type":"topic","abstract":[{"type":"text","text":"The entry point to execute SDK actions. To obtain an instance use "},{"type":"codeVoice","code":"Zendesk.initialize(channelKey:completionHandler:)"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MessagingFactory","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1MessagingFactory\/fragments","value":[{"kind":"identifier","text":"MessagingFactory"}]},{"value":"Zendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"}]}]}