{"metadata":{"roleHeading":"Type Property","externalID":"s:10ZendeskSDK0A0C22authenticationDelegate0A18SDKConversationKit014AuthenticationD0_pSgvpZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit22AuthenticationDelegateP","kind":"typeIdentifier","text":"AuthenticationDelegate"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"symbolKind":"property","title":"authenticationDelegate"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/authenticationDelegate"},"abstract":[{"text":"A delegate that gets notified about failed requests due to invalid credentials.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit22AuthenticationDelegateP","kind":"typeIdentifier","text":"AuthenticationDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk"]]},"variants":[{"paths":["\/documentation\/zendesksdk\/zendesk\/authenticationdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk/authenticationDelegate":{"url":"\/documentation\/zendesksdk\/zendesk\/authenticationdelegate","abstract":[{"type":"text","text":"A delegate that gets notified about failed requests due to invalid credentials."}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk\/authenticationDelegate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"authenticationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationDelegate","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit22AuthenticationDelegateP"},{"text":"?","kind":"text"}],"kind":"symbol","title":"authenticationDelegate","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","role":"collection","url":"\/documentation\/zendesksdk","abstract":[],"type":"topic","title":"ZendeskSDK","kind":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/Zendesk":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/Zendesk","url":"\/documentation\/zendesksdk\/zendesk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"abstract":[{"text":"The entry point to execute SDK actions. To obtain an instance use ","type":"text"},{"code":"Zendesk.initialize(channelKey:completionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"Zendesk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/title","value":"Zendesk","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"Zendesk"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1Zendesk\/navigatorTitle","value":[{"text":"Zendesk","kind":"identifier"}],"op":"replace"}]}]}