{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationType","preciseIdentifier":"s:25ZendeskSDKConversationKit18AuthenticationTypeO","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/authenticationType","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationType","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit18AuthenticationTypeO"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ZendeskSDK"}],"externalID":"s:10ZendeskSDK0A4UserC18authenticationType0A18SDKConversationKit014AuthenticationE0Ovp","title":"authenticationType","role":"symbol"},"abstract":[{"type":"text","text":"The authentication type of the "},{"type":"codeVoice","code":"User"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskuser\/authenticationtype"]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskUser","kind":"identifier"}],"title":"ZendeskUser","navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","abstract":[]},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/authenticationType":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationType","preciseIdentifier":"s:25ZendeskSDKConversationKit18AuthenticationTypeO","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The authentication type of the "},{"code":"User","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/authenticationType","type":"topic","url":"\/documentation\/zendesksdk\/zendeskuser\/authenticationtype","title":"authenticationType","role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","type":"topic","kind":"symbol","title":"ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title","op":"replace","value":"ZDKZendeskUser"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskUser"}]},{"op":"replace","value":[{"text":"ZDKZendeskUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/navigatorTitle"}]}]}