{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskuser\/externalid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskuser\/externalid"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskUser(py)externalId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"externalId","navigatorTitle":[{"text":"externalId","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/externalId","interfaceLanguage":"swift"},"abstract":[{"text":"The external id of the ","type":"text"},{"type":"codeVoice","code":"User"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"externalId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser":{"type":"topic","title":"ZendeskUser","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser","url":"\/documentation\/zendesksdk\/zendeskuser","navigatorTitle":[{"text":"ZendeskUser","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZendeskUser","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"type":"topic","title":"ZendeskSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","url":"\/documentation\/zendesksdk","role":"collection"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskUser/externalId":{"title":"externalId","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"externalId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdk\/zendeskuser\/externalid","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskUser\/externalId","type":"topic","abstract":[{"type":"text","text":"The external id of the "},{"code":"User","type":"codeVoice"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"externalId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"externalId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"externalId","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKZendeskUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKZendeskUser"}],"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser~1externalId\/title","value":"externalId"},{"value":[{"text":"externalId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskUser~1externalId\/fragments"}]}]}