{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdk\/zendeskmessage\/timestamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdk\/zendeskmessage\/timestamp"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK","doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/timestamp"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"title":"timestamp","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"role":"symbol","modules":[{"name":"ZendeskSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDK@objc(cs)ZDKZendeskMessage(py)timestamp"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The date the message was created at.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage":{"role":"symbol","type":"topic","title":"ZendeskMessage","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZendeskMessage","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZendeskMessage","kind":"identifier"}],"url":"\/documentation\/zendesksdk\/zendeskmessage"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK":{"title":"ZendeskSDK","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/zendesksdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK"},"doc://com.zendesk.Zendesk/documentation/ZendeskSDK/ZendeskMessage/timestamp":{"identifier":"doc:\/\/com.zendesk.Zendesk\/documentation\/ZendeskSDK\/ZendeskMessage\/timestamp","url":"\/documentation\/zendesksdk\/zendeskmessage\/timestamp","role":"symbol","title":"timestamp","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"abstract":[{"text":"The date the message was created at.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/title","value":"ZDKZendeskMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/fragments","value":[{"text":"ZDKZendeskMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKZendeskMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1timestamp\/title","value":"timestamp","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Zendesk~1documentation~1ZendeskSDK~1ZendeskMessage~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}